/* Generated by gloam. DO NOT EDIT. */

#ifndef GLOAM_GLX_H
#define GLOAM_GLX_H

#ifdef GLX_H
  #error GLX (glx.h) header already included (API: glx), remove previous include!
#endif
#define GLX_H 1

#ifdef __linux

#include <X11/X.h>
#include <X11/Xlib.h>
#include <X11/Xutil.h>

#include <gloam/gl.h>

#include <stddef.h>
#include <stdint.h>


#ifdef __cplusplus
extern "C" {
#endif

/* Calling convention */
#ifndef APIENTRY
#  if defined(_WIN32)
#    define APIENTRY __stdcall
#  else
#    define APIENTRY
#  endif
#endif
#ifndef APIENTRYP
#  define APIENTRYP APIENTRY *
#endif
#ifndef GLAPI
#  define GLAPI extern
#endif

/* Calling convention for GL callback function pointers (e.g. debug callbacks,
   blob cache functions).  Piggybacks on APIENTRY if already defined so that
   code which defines APIENTRY before including this header gets consistent
   behaviour.  Guard against redefinition so multiple gloam headers included
   in the same translation unit don't conflict. */
#ifndef GLOAM_API_PTR
#  ifdef APIENTRY
#    define GLOAM_API_PTR APIENTRY
#  elif defined(_WIN32)
#    define GLOAM_API_PTR __stdcall
#  else
#    define GLOAM_API_PTR
#  endif
#endif
#ifndef GLAPIENTRY
#  define GLAPIENTRY GLOAM_API_PTR
#endif
/* ---- Constants ----------------------------------------------------------- */
#define GLX_EXTENSION_NAME "GLX" /* This is modest abuse of the enum tag mechanism, maybe a string tag? */
#define GLX_VENDOR 0x1
#define GLX_VERSION 0x2
#define GLX_EXTENSIONS 0x3
#define GLX_3DFX_WINDOW_MODE_MESA 0x1
#define GLX_3DFX_FULLSCREEN_MODE_MESA 0x2
#define GLX_PbufferClobber 0
#define GLX_BufferSwapComplete 1
#define __GLX_NUMBER_EVENTS 17
#define GLX_BAD_SCREEN 1
#define GLX_BAD_ATTRIBUTE 2
#define GLX_NO_EXTENSION 3
#define GLX_BAD_VISUAL 4
#define GLX_BAD_CONTEXT 5
#define GLX_BAD_VALUE 6
#define GLX_BAD_ENUM 7
#define GLX_BAD_HYPERPIPE_CONFIG_SGIX 91
#define GLX_BAD_HYPERPIPE_SGIX 92
#define GLX_STEREO_NOTIFY_EXT 0x00000000
#define GLX_WINDOW_BIT 0x00000001
#define GLX_WINDOW_BIT_SGIX 0x00000001
#define GLX_PIXMAP_BIT 0x00000002
#define GLX_PIXMAP_BIT_SGIX 0x00000002
#define GLX_PBUFFER_BIT 0x00000004
#define GLX_PBUFFER_BIT_SGIX 0x00000004
#define GLX_RGBA_BIT 0x00000001
#define GLX_RGBA_BIT_SGIX 0x00000001
#define GLX_COLOR_INDEX_BIT 0x00000002
#define GLX_COLOR_INDEX_BIT_SGIX 0x00000002
#define GLX_RGBA_FLOAT_BIT_ARB 0x00000004
#define GLX_RGBA_UNSIGNED_FLOAT_BIT_EXT 0x00000008
#define GLX_SYNC_FRAME_SGIX 0x00000000
#define GLX_SYNC_SWAP_SGIX 0x00000001
#define GLX_STEREO_NOTIFY_MASK_EXT 0x00000001
#define GLX_BUFFER_SWAP_COMPLETE_INTEL_MASK 0x04000000
#define GLX_PBUFFER_CLOBBER_MASK 0x08000000
#define GLX_BUFFER_CLOBBER_MASK_SGIX 0x08000000
#define GLX_FRONT_LEFT_BUFFER_BIT 0x00000001
#define GLX_FRONT_LEFT_BUFFER_BIT_SGIX 0x00000001
#define GLX_FRONT_RIGHT_BUFFER_BIT 0x00000002
#define GLX_FRONT_RIGHT_BUFFER_BIT_SGIX 0x00000002
#define GLX_BACK_LEFT_BUFFER_BIT 0x00000004
#define GLX_BACK_LEFT_BUFFER_BIT_SGIX 0x00000004
#define GLX_BACK_RIGHT_BUFFER_BIT 0x00000008
#define GLX_BACK_RIGHT_BUFFER_BIT_SGIX 0x00000008
#define GLX_AUX_BUFFERS_BIT 0x00000010
#define GLX_AUX_BUFFERS_BIT_SGIX 0x00000010
#define GLX_DEPTH_BUFFER_BIT 0x00000020
#define GLX_DEPTH_BUFFER_BIT_SGIX 0x00000020
#define GLX_STENCIL_BUFFER_BIT 0x00000040
#define GLX_STENCIL_BUFFER_BIT_SGIX 0x00000040
#define GLX_ACCUM_BUFFER_BIT 0x00000080
#define GLX_ACCUM_BUFFER_BIT_SGIX 0x00000080
#define GLX_SAMPLE_BUFFERS_BIT_SGIX 0x00000100
#define GLX_HYPERPIPE_DISPLAY_PIPE_SGIX 0x00000001
#define GLX_HYPERPIPE_RENDER_PIPE_SGIX 0x00000002
#define GLX_PIPE_RECT_SGIX 0x00000001
#define GLX_PIPE_RECT_LIMITS_SGIX 0x00000002
#define GLX_HYPERPIPE_STEREO_SGIX 0x00000003
#define GLX_HYPERPIPE_PIXEL_AVERAGE_SGIX 0x00000004
#define GLX_TEXTURE_1D_BIT_EXT 0x00000001
#define GLX_TEXTURE_2D_BIT_EXT 0x00000002
#define GLX_TEXTURE_RECTANGLE_BIT_EXT 0x00000004
#define GLX_CONTEXT_DEBUG_BIT_ARB 0x00000001
#define GLX_CONTEXT_FORWARD_COMPATIBLE_BIT_ARB 0x00000002
#define GLX_CONTEXT_ROBUST_ACCESS_BIT_ARB 0x00000004
#define GLX_CONTEXT_RESET_ISOLATION_BIT_ARB 0x00000008
#define GLX_CONTEXT_CORE_PROFILE_BIT_ARB 0x00000001
#define GLX_CONTEXT_COMPATIBILITY_PROFILE_BIT_ARB 0x00000002
#define GLX_CONTEXT_ES_PROFILE_BIT_EXT 0x00000004
#define GLX_CONTEXT_ES2_PROFILE_BIT_EXT 0x00000004
#define GLX_HYPERPIPE_PIPE_NAME_LENGTH_SGIX 80
#define GLX_CONTEXT_RELEASE_BEHAVIOR_NONE_ARB 0
#define GLX_DONT_CARE 0xFFFFFFFF /* For ChooseFBConfig attributes */
#define GLX_USE_GL 1
#define GLX_BUFFER_SIZE 2
#define GLX_LEVEL 3
#define GLX_RGBA 4
#define GLX_DOUBLEBUFFER 5
#define GLX_STEREO 6
#define GLX_AUX_BUFFERS 7
#define GLX_RED_SIZE 8
#define GLX_GREEN_SIZE 9
#define GLX_BLUE_SIZE 10
#define GLX_ALPHA_SIZE 11
#define GLX_DEPTH_SIZE 12
#define GLX_STENCIL_SIZE 13
#define GLX_ACCUM_RED_SIZE 14
#define GLX_ACCUM_GREEN_SIZE 15
#define GLX_ACCUM_BLUE_SIZE 16
#define GLX_ACCUM_ALPHA_SIZE 17
#define GLX_CONFIG_CAVEAT 0x20
#define GLX_VISUAL_CAVEAT_EXT 0x20
#define GLX_X_VISUAL_TYPE 0x22
#define GLX_X_VISUAL_TYPE_EXT 0x22
#define GLX_TRANSPARENT_TYPE 0x23
#define GLX_TRANSPARENT_TYPE_EXT 0x23
#define GLX_TRANSPARENT_INDEX_VALUE 0x24
#define GLX_TRANSPARENT_INDEX_VALUE_EXT 0x24
#define GLX_TRANSPARENT_RED_VALUE 0x25
#define GLX_TRANSPARENT_RED_VALUE_EXT 0x25
#define GLX_TRANSPARENT_GREEN_VALUE 0x26
#define GLX_TRANSPARENT_GREEN_VALUE_EXT 0x26
#define GLX_TRANSPARENT_BLUE_VALUE 0x27
#define GLX_TRANSPARENT_BLUE_VALUE_EXT 0x27
#define GLX_TRANSPARENT_ALPHA_VALUE 0x28
#define GLX_TRANSPARENT_ALPHA_VALUE_EXT 0x28
#define GLX_GPU_VENDOR_AMD 0x1F00
#define GLX_GPU_RENDERER_STRING_AMD 0x1F01
#define GLX_GPU_OPENGL_VERSION_STRING_AMD 0x1F02
#define GLX_CONTEXT_MAJOR_VERSION_ARB 0x2091
#define GLX_CONTEXT_MINOR_VERSION_ARB 0x2092
#define GLX_CONTEXT_FLAGS_ARB 0x2094
#define GLX_CONTEXT_ALLOW_BUFFER_BYTE_ORDER_MISMATCH_ARB 0x2095
#define GLX_CONTEXT_RELEASE_BEHAVIOR_ARB 0x2097
#define GLX_CONTEXT_RELEASE_BEHAVIOR_FLUSH_ARB 0x2098
#define GLX_CONTEXT_MULTIGPU_ATTRIB_NV 0x20AA
#define GLX_CONTEXT_MULTIGPU_ATTRIB_SINGLE_NV 0x20AB
#define GLX_CONTEXT_MULTIGPU_ATTRIB_AFR_NV 0x20AC
#define GLX_CONTEXT_MULTIGPU_ATTRIB_MULTICAST_NV 0x20AD
#define GLX_CONTEXT_MULTIGPU_ATTRIB_MULTI_DISPLAY_MULTICAST_NV 0x20AE
#define GLX_FLOAT_COMPONENTS_NV 0x20B0
#define GLX_RGBA_UNSIGNED_FLOAT_TYPE_EXT 0x20B1
#define GLX_FRAMEBUFFER_SRGB_CAPABLE_ARB 0x20B2
#define GLX_FRAMEBUFFER_SRGB_CAPABLE_EXT 0x20B2
#define GLX_COLOR_SAMPLES_NV 0x20B3
#define GLX_RGBA_FLOAT_TYPE_ARB 0x20B9
#define GLX_VIDEO_OUT_COLOR_NV 0x20C3
#define GLX_VIDEO_OUT_ALPHA_NV 0x20C4
#define GLX_VIDEO_OUT_DEPTH_NV 0x20C5
#define GLX_VIDEO_OUT_COLOR_AND_ALPHA_NV 0x20C6
#define GLX_VIDEO_OUT_COLOR_AND_DEPTH_NV 0x20C7
#define GLX_VIDEO_OUT_FRAME_NV 0x20C8
#define GLX_VIDEO_OUT_FIELD_1_NV 0x20C9
#define GLX_VIDEO_OUT_FIELD_2_NV 0x20CA
#define GLX_VIDEO_OUT_STACKED_FIELDS_1_2_NV 0x20CB
#define GLX_VIDEO_OUT_STACKED_FIELDS_2_1_NV 0x20CC
#define GLX_DEVICE_ID_NV 0x20CD
#define GLX_UNIQUE_ID_NV 0x20CE
#define GLX_NUM_VIDEO_CAPTURE_SLOTS_NV 0x20CF
#define GLX_BIND_TO_TEXTURE_RGB_EXT 0x20D0
#define GLX_BIND_TO_TEXTURE_RGBA_EXT 0x20D1
#define GLX_BIND_TO_MIPMAP_TEXTURE_EXT 0x20D2
#define GLX_BIND_TO_TEXTURE_TARGETS_EXT 0x20D3
#define GLX_Y_INVERTED_EXT 0x20D4
#define GLX_TEXTURE_FORMAT_EXT 0x20D5
#define GLX_TEXTURE_TARGET_EXT 0x20D6
#define GLX_MIPMAP_TEXTURE_EXT 0x20D7
#define GLX_TEXTURE_FORMAT_NONE_EXT 0x20D8
#define GLX_TEXTURE_FORMAT_RGB_EXT 0x20D9
#define GLX_TEXTURE_FORMAT_RGBA_EXT 0x20DA
#define GLX_TEXTURE_1D_EXT 0x20DB
#define GLX_TEXTURE_2D_EXT 0x20DC
#define GLX_TEXTURE_RECTANGLE_EXT 0x20DD
#define GLX_FRONT_LEFT_EXT 0x20DE
#define GLX_FRONT_RIGHT_EXT 0x20DF
#define GLX_BACK_LEFT_EXT 0x20E0
#define GLX_BACK_RIGHT_EXT 0x20E1
#define GLX_FRONT_EXT 0x20DE
#define GLX_BACK_EXT 0x20E0
#define GLX_AUX0_EXT 0x20E2
#define GLX_AUX1_EXT 0x20E3
#define GLX_AUX2_EXT 0x20E4
#define GLX_AUX3_EXT 0x20E5
#define GLX_AUX4_EXT 0x20E6
#define GLX_AUX5_EXT 0x20E7
#define GLX_AUX6_EXT 0x20E8
#define GLX_AUX7_EXT 0x20E9
#define GLX_AUX8_EXT 0x20EA
#define GLX_AUX9_EXT 0x20EB
#define GLX_NUM_VIDEO_SLOTS_NV 0x20F0
#define GLX_SWAP_INTERVAL_EXT 0x20F1
#define GLX_MAX_SWAP_INTERVAL_EXT 0x20F2
#define GLX_LATE_SWAPS_TEAR_EXT 0x20F3
#define GLX_BACK_BUFFER_AGE_EXT 0x20F4
#define GLX_STEREO_TREE_EXT 0x20F5
#define GLX_VENDOR_NAMES_EXT 0x20F6
#define GLX_GENERATE_RESET_ON_VIDEO_MEMORY_PURGE_NV 0x20F7
#define GLX_GPU_FASTEST_TARGET_GPUS_AMD 0x21A2
#define GLX_GPU_RAM_AMD 0x21A3
#define GLX_GPU_CLOCK_AMD 0x21A4
#define GLX_GPU_NUM_PIPES_AMD 0x21A5
#define GLX_GPU_NUM_SIMD_AMD 0x21A6
#define GLX_GPU_NUM_RB_AMD 0x21A7
#define GLX_GPU_NUM_SPI_AMD 0x21A8
#define GLX_CONTEXT_PRIORITY_LEVEL_EXT 0x3100
#define GLX_CONTEXT_PRIORITY_HIGH_EXT 0x3101
#define GLX_CONTEXT_PRIORITY_MEDIUM_EXT 0x3102
#define GLX_CONTEXT_PRIORITY_LOW_EXT 0x3103
#define GLX_CONTEXT_OPENGL_NO_ERROR_ARB 0x31B3
#define GLX_NONE 0x8000 /* Attribute value */
#define GLX_SLOW_CONFIG 0x8001 /* CONFIG_CAVEAT attribute value */
#define GLX_TRUE_COLOR 0x8002 /* X_VISUAL_TYPE attribute value */
#define GLX_DIRECT_COLOR 0x8003 /* X_VISUAL_TYPE attribute value */
#define GLX_PSEUDO_COLOR 0x8004 /* X_VISUAL_TYPE attribute value */
#define GLX_STATIC_COLOR 0x8005 /* X_VISUAL_TYPE attribute value */
#define GLX_GRAY_SCALE 0x8006 /* X_VISUAL_TYPE attribute value */
#define GLX_STATIC_GRAY 0x8007 /* X_VISUAL_TYPE attribute value */
#define GLX_TRANSPARENT_RGB 0x8008 /* TRANSPARENT_TYPE attribute value */
#define GLX_TRANSPARENT_INDEX 0x8009 /* TRANSPARENT_TYPE attribute value */
#define GLX_VISUAL_ID 0x800B /* Context attribute */
#define GLX_SCREEN 0x800C /* Context attribute */
#define GLX_NON_CONFORMANT_CONFIG 0x800D /* CONFIG_CAVEAT attribute value */
#define GLX_DRAWABLE_TYPE 0x8010 /* FBConfig attribute */
#define GLX_RENDER_TYPE 0x8011 /* FBConfig attribute */
#define GLX_X_RENDERABLE 0x8012 /* FBConfig attribute */
#define GLX_FBCONFIG_ID 0x8013 /* FBConfig attribute */
#define GLX_RGBA_TYPE 0x8014 /* CreateNewContext render_type value */
#define GLX_COLOR_INDEX_TYPE 0x8015 /* CreateNewContext render_type value */
#define GLX_MAX_PBUFFER_WIDTH 0x8016 /* FBConfig attribute */
#define GLX_MAX_PBUFFER_HEIGHT 0x8017 /* FBConfig attribute */
#define GLX_MAX_PBUFFER_PIXELS 0x8018 /* FBConfig attribute */
#define GLX_PRESERVED_CONTENTS 0x801B /* CreateGLXPbuffer attribute */
#define GLX_LARGEST_PBUFFER 0x801C /* CreateGLXPbuffer attribute */
#define GLX_WIDTH 0x801D /* Drawable attribute */
#define GLX_HEIGHT 0x801E /* Drawable attribute */
#define GLX_EVENT_MASK 0x801F /* Drawable attribute */
#define GLX_DAMAGED 0x8020 /* PbufferClobber event_type value */
#define GLX_SAVED 0x8021 /* PbufferClobber event_type value */
#define GLX_WINDOW 0x8022 /* PbufferClobber draw_type value */
#define GLX_PBUFFER 0x8023 /* PbufferClobber draw_type value */
#define GLX_NONE_EXT 0x8000 /* several EXT attribute values */
#define GLX_SLOW_VISUAL_EXT 0x8001 /* VISUAL_CAVEAT_EXT attribute value */
#define GLX_TRUE_COLOR_EXT 0x8002 /* X_VISUAL_TYPE_EXT attribute value */
#define GLX_DIRECT_COLOR_EXT 0x8003 /* X_VISUAL_TYPE_EXT attribute value */
#define GLX_PSEUDO_COLOR_EXT 0x8004 /* X_VISUAL_TYPE_EXT attribute value */
#define GLX_STATIC_COLOR_EXT 0x8005 /* X_VISUAL_TYPE_EXT attribute value */
#define GLX_GRAY_SCALE_EXT 0x8006 /* X_VISUAL_TYPE_EXT attribute value */
#define GLX_STATIC_GRAY_EXT 0x8007 /* X_VISUAL_TYPE_EXT attribute value */
#define GLX_TRANSPARENT_RGB_EXT 0x8008 /* TRANSPARENT_TYPE_EXT attribute value */
#define GLX_TRANSPARENT_INDEX_EXT 0x8009 /* TRANSPARENT_TYPE_EXT attribute value */
#define GLX_SHARE_CONTEXT_EXT 0x800A /* QueryContextInfoEXT attribute */
#define GLX_VISUAL_ID_EXT 0x800B /* QueryContextInfoEXT attribute */
#define GLX_SCREEN_EXT 0x800C /* QueryContextInfoEXT attribute */
#define GLX_NON_CONFORMANT_VISUAL_EXT 0x800D /* VISUAL_CAVEAT_EXT attribute value */
#define GLX_DRAWABLE_TYPE_SGIX 0x8010 /* FBConfigSGIX attribute */
#define GLX_RENDER_TYPE_SGIX 0x8011 /* FBConfigSGIX attribute */
#define GLX_X_RENDERABLE_SGIX 0x8012 /* FBConfigSGIX attribute */
#define GLX_FBCONFIG_ID_SGIX 0x8013 /* FBConfigSGIX attribute */
#define GLX_RGBA_TYPE_SGIX 0x8014 /* CreateContextWithConfigSGIX render_type value */
#define GLX_COLOR_INDEX_TYPE_SGIX 0x8015 /* CreateContextWithConfigSGIX render_type value */
#define GLX_MAX_PBUFFER_WIDTH_SGIX 0x8016 /* FBConfigSGIX attribute */
#define GLX_MAX_PBUFFER_HEIGHT_SGIX 0x8017 /* FBConfigSGIX attribute */
#define GLX_MAX_PBUFFER_PIXELS_SGIX 0x8018 /* FBConfigSGIX attribute */
#define GLX_OPTIMAL_PBUFFER_WIDTH_SGIX 0x8019 /* FBConfigSGIX attribute */
#define GLX_OPTIMAL_PBUFFER_HEIGHT_SGIX 0x801A /* FBConfigSGIX attribute */
#define GLX_PRESERVED_CONTENTS_SGIX 0x801B /* PbufferSGIX attribute */
#define GLX_LARGEST_PBUFFER_SGIX 0x801C /* PbufferSGIX attribute */
#define GLX_WIDTH_SGIX 0x801D /* PbufferSGIX attribute */
#define GLX_HEIGHT_SGIX 0x801E /* PbufferSGIX attribute */
#define GLX_EVENT_MASK_SGIX 0x801F /* PbufferSGIX attribute */
#define GLX_DAMAGED_SGIX 0x8020 /* BufferClobberSGIX event_type value */
#define GLX_SAVED_SGIX 0x8021 /* BufferClobberSGIX event_type value */
#define GLX_WINDOW_SGIX 0x8022 /* BufferClobberSGIX draw_type value */
#define GLX_PBUFFER_SGIX 0x8023 /* BufferClobberSGIX draw_type value */
#define GLX_BLENDED_RGBA_SGIS 0x8025 /* TRANSPARENT_TYPE_EXT attribute value */
#define GLX_MULTISAMPLE_SUB_RECT_WIDTH_SGIS 0x8026 /* Visual attribute (shared_multisample) */
#define GLX_MULTISAMPLE_SUB_RECT_HEIGHT_SGIS 0x8027 /* Visual attribute (shared_multisample) */
#define GLX_VISUAL_SELECT_GROUP_SGIX 0x8028 /* Visual attribute (visual_select_group) */
#define GLX_HYPERPIPE_ID_SGIX 0x8030
#define GLX_PBUFFER_HEIGHT 0x8040 /* CreateGLXPbuffer attribute */
#define GLX_PBUFFER_WIDTH 0x8041 /* CreateGLXPbuffer attribute */
#define GLX_SAMPLE_BUFFERS_3DFX 0x8050
#define GLX_SAMPLES_3DFX 0x8051
#define GLX_SWAP_METHOD_OML 0x8060
#define GLX_SWAP_EXCHANGE_OML 0x8061
#define GLX_SWAP_COPY_OML 0x8062
#define GLX_SWAP_UNDEFINED_OML 0x8063
#define GLX_EXCHANGE_COMPLETE_INTEL 0x8180
#define GLX_COPY_COMPLETE_INTEL 0x8181
#define GLX_FLIP_COMPLETE_INTEL 0x8182
#define GLX_RENDERER_VENDOR_ID_MESA 0x8183
#define GLX_RENDERER_DEVICE_ID_MESA 0x8184
#define GLX_RENDERER_VERSION_MESA 0x8185
#define GLX_RENDERER_ACCELERATED_MESA 0x8186
#define GLX_RENDERER_VIDEO_MEMORY_MESA 0x8187
#define GLX_RENDERER_UNIFIED_MEMORY_ARCHITECTURE_MESA 0x8188
#define GLX_RENDERER_PREFERRED_PROFILE_MESA 0x8189
#define GLX_RENDERER_OPENGL_CORE_PROFILE_VERSION_MESA 0x818A
#define GLX_RENDERER_OPENGL_COMPATIBILITY_PROFILE_VERSION_MESA 0x818B
#define GLX_RENDERER_OPENGL_ES_PROFILE_VERSION_MESA 0x818C
#define GLX_RENDERER_OPENGL_ES2_PROFILE_VERSION_MESA 0x818D
#define GLX_LOSE_CONTEXT_ON_RESET_ARB 0x8252
#define GLX_CONTEXT_RESET_NOTIFICATION_STRATEGY_ARB 0x8256
#define GLX_NO_RESET_NOTIFICATION_ARB 0x8261
#define GLX_CONTEXT_PROFILE_MASK_ARB 0x9126 /* Value shared with GL */
#define GLX_SAMPLE_BUFFERS 100000
#define GLX_SAMPLE_BUFFERS_ARB 100000
#define GLX_SAMPLE_BUFFERS_SGIS 100000
#define GLX_SAMPLES 100001
#define GLX_SAMPLES_ARB 100001
#define GLX_SAMPLES_SGIS 100001
#define GLX_COVERAGE_SAMPLES_NV 100001


/* ---- Types ----------------------------------------------------------------
   Emitted in topological dependency order. */

#if defined(__ENVIRONMENT_MAC_OS_X_VERSION_MIN_REQUIRED__) \
&& (__ENVIRONMENT_MAC_OS_X_VERSION_MIN_REQUIRED__ > 1060)
typedef long GLintptr;
#else
typedef ptrdiff_t GLintptr;
#endif

#if defined(__ENVIRONMENT_MAC_OS_X_VERSION_MIN_REQUIRED__) \
&& (__ENVIRONMENT_MAC_OS_X_VERSION_MIN_REQUIRED__ > 1060)
typedef long GLsizeiptr;
#else
typedef ptrdiff_t GLsizeiptr;
#endif

typedef struct __GLXFBConfigRec *GLXFBConfig;

typedef struct __GLXcontextRec *GLXContext;

typedef void (APIENTRY *__GLXextFuncPtr)(void);

typedef unsigned int GLXVideoDeviceNV;

typedef struct __GLXFBConfigRec *GLXFBConfigSGIX;

typedef struct {
    char    pipeName[80]; /* Should be [GLX_HYPERPIPE_PIPE_NAME_LENGTH_SGIX] */
    int     networkId;
} GLXHyperpipeNetworkSGIX;

typedef struct {
    char    pipeName[80]; /* Should be [GLX_HYPERPIPE_PIPE_NAME_LENGTH_SGIX] */
    int     channel;
    unsigned int participationType;
    int     timeSlice;
} GLXHyperpipeConfigSGIX;

typedef struct {
    char pipeName[80]; /* Should be [GLX_HYPERPIPE_PIPE_NAME_LENGTH_SGIX] */
    int srcXOrigin, srcYOrigin, srcWidth, srcHeight;
    int destXOrigin, destYOrigin, destWidth, destHeight;
} GLXPipeRect;

typedef struct {
    char pipeName[80]; /* Should be [GLX_HYPERPIPE_PIPE_NAME_LENGTH_SGIX] */
    int XOrigin, YOrigin, maxHeight, maxWidth;
} GLXPipeRectLimits;

typedef XID GLXFBConfigID;

typedef XID GLXContextID;

typedef XID GLXPixmap;

typedef XID GLXDrawable;

typedef XID GLXWindow;

typedef XID GLXPbuffer;

typedef XID GLXVideoCaptureDeviceNV;

typedef XID GLXVideoSourceSGIX;

typedef XID GLXFBConfigIDSGIX;

typedef XID GLXPbufferSGIX;

typedef struct {
    int event_type;             /* GLX_DAMAGED or GLX_SAVED */
    int draw_type;              /* GLX_WINDOW or GLX_PBUFFER */
    unsigned long serial;       /* # of last request processed by server */
    Bool send_event;            /* true if this came for SendEvent request */
    Display *display;           /* display the event was read from */
    GLXDrawable drawable;       /* XID of Drawable */
    unsigned int buffer_mask;   /* mask indicating which buffers are affected */
    unsigned int aux_buffer;    /* which aux buffer was affected */
    int x, y;
    int width, height;
    int count;                  /* if nonzero, at least this many more */
} GLXPbufferClobberEvent;

typedef struct {
    int type;
    unsigned long serial;
    Bool send_event;
    Display *display;
    int extension;
    int evtype;
    GLXDrawable window;
    Bool stereo_tree;
} GLXStereoNotifyEventEXT;

typedef struct {
    int type;
    unsigned long serial;   /* # of last request processed by server */
    Bool send_event;        /* true if this came for SendEvent request */
    Display *display;       /* display the event was read from */
    GLXDrawable drawable;   /* i.d. of Drawable */
    int event_type;         /* GLX_DAMAGED_SGIX or GLX_SAVED_SGIX */
    int draw_type;          /* GLX_WINDOW_SGIX or GLX_PBUFFER_SGIX */
    unsigned int mask;      /* mask indicating which buffers are affected*/
    int x, y;
    int width, height;
    int count;              /* if nonzero, at least this many more */
} GLXBufferClobberEventSGIX;

typedef struct {
    int type;
    unsigned long serial;       /* # of last request processed by server */
    Bool send_event;            /* true if this came from a SendEvent request */
    Display *display;           /* Display the event was read from */
    GLXDrawable drawable;       /* drawable on which event was requested in event mask */
    int event_type;
    int64_t ust;
    int64_t msc;
    int64_t sbc;
} GLXBufferSwapComplete;

typedef union __GLXEvent {
    GLXPbufferClobberEvent glxpbufferclobber;
    GLXBufferSwapComplete glxbufferswapcomplete;
    long pad[24];
} GLXEvent;


/* ---- PFN typedefs -------------------------------------------------------- */
typedef XVisualInfo * (APIENTRYP PFNGLXCHOOSEVISUALPROC)(Display * dpy, int screen, int * attribList);
typedef GLXContext (APIENTRYP PFNGLXCREATECONTEXTPROC)(Display * dpy, XVisualInfo * vis, GLXContext shareList, Bool direct);
typedef void (APIENTRYP PFNGLXDESTROYCONTEXTPROC)(Display * dpy, GLXContext ctx);
typedef Bool (APIENTRYP PFNGLXMAKECURRENTPROC)(Display * dpy, GLXDrawable drawable, GLXContext ctx);
typedef void (APIENTRYP PFNGLXCOPYCONTEXTPROC)(Display * dpy, GLXContext src, GLXContext dst, unsigned long mask);
typedef void (APIENTRYP PFNGLXSWAPBUFFERSPROC)(Display * dpy, GLXDrawable drawable);
typedef GLXPixmap (APIENTRYP PFNGLXCREATEGLXPIXMAPPROC)(Display * dpy, XVisualInfo * visual, Pixmap pixmap);
typedef void (APIENTRYP PFNGLXDESTROYGLXPIXMAPPROC)(Display * dpy, GLXPixmap pixmap);
typedef Bool (APIENTRYP PFNGLXQUERYEXTENSIONPROC)(Display * dpy, int * errorb, int * event);
typedef Bool (APIENTRYP PFNGLXQUERYVERSIONPROC)(Display * dpy, int * maj, int * min);
typedef Bool (APIENTRYP PFNGLXISDIRECTPROC)(Display * dpy, GLXContext ctx);
typedef int (APIENTRYP PFNGLXGETCONFIGPROC)(Display * dpy, XVisualInfo * visual, int attrib, int * value);
typedef GLXContext (APIENTRYP PFNGLXGETCURRENTCONTEXTPROC)(void);
typedef GLXDrawable (APIENTRYP PFNGLXGETCURRENTDRAWABLEPROC)(void);
typedef void (APIENTRYP PFNGLXWAITGLPROC)(void);
typedef void (APIENTRYP PFNGLXWAITXPROC)(void);
typedef void (APIENTRYP PFNGLXUSEXFONTPROC)(Font font, int first, int count, int list);
typedef const char * (APIENTRYP PFNGLXQUERYEXTENSIONSSTRINGPROC)(Display * dpy, int screen);
typedef const char * (APIENTRYP PFNGLXQUERYSERVERSTRINGPROC)(Display * dpy, int screen, int name);
typedef const char * (APIENTRYP PFNGLXGETCLIENTSTRINGPROC)(Display * dpy, int name);
typedef Display * (APIENTRYP PFNGLXGETCURRENTDISPLAYPROC)(void);
typedef GLXFBConfig * (APIENTRYP PFNGLXGETFBCONFIGSPROC)(Display * dpy, int screen, int * nelements);
typedef GLXFBConfig * (APIENTRYP PFNGLXCHOOSEFBCONFIGPROC)(Display * dpy, int screen, const int * attrib_list, int * nelements);
typedef int (APIENTRYP PFNGLXGETFBCONFIGATTRIBPROC)(Display * dpy, GLXFBConfig config, int attribute, int * value);
typedef XVisualInfo * (APIENTRYP PFNGLXGETVISUALFROMFBCONFIGPROC)(Display * dpy, GLXFBConfig config);
typedef GLXWindow (APIENTRYP PFNGLXCREATEWINDOWPROC)(Display * dpy, GLXFBConfig config, Window win, const int * attrib_list);
typedef void (APIENTRYP PFNGLXDESTROYWINDOWPROC)(Display * dpy, GLXWindow win);
typedef GLXPixmap (APIENTRYP PFNGLXCREATEPIXMAPPROC)(Display * dpy, GLXFBConfig config, Pixmap pixmap, const int * attrib_list);
typedef void (APIENTRYP PFNGLXDESTROYPIXMAPPROC)(Display * dpy, GLXPixmap pixmap);
typedef GLXPbuffer (APIENTRYP PFNGLXCREATEPBUFFERPROC)(Display * dpy, GLXFBConfig config, const int * attrib_list);
typedef void (APIENTRYP PFNGLXDESTROYPBUFFERPROC)(Display * dpy, GLXPbuffer pbuf);
typedef void (APIENTRYP PFNGLXQUERYDRAWABLEPROC)(Display * dpy, GLXDrawable draw, int attribute, unsigned int * value);
typedef GLXContext (APIENTRYP PFNGLXCREATENEWCONTEXTPROC)(Display * dpy, GLXFBConfig config, int render_type, GLXContext share_list, Bool direct);
typedef Bool (APIENTRYP PFNGLXMAKECONTEXTCURRENTPROC)(Display * dpy, GLXDrawable draw, GLXDrawable read, GLXContext ctx);
typedef GLXDrawable (APIENTRYP PFNGLXGETCURRENTREADDRAWABLEPROC)(void);
typedef int (APIENTRYP PFNGLXQUERYCONTEXTPROC)(Display * dpy, GLXContext ctx, int attribute, int * value);
typedef void (APIENTRYP PFNGLXSELECTEVENTPROC)(Display * dpy, GLXDrawable draw, unsigned long event_mask);
typedef void (APIENTRYP PFNGLXGETSELECTEDEVENTPROC)(Display * dpy, GLXDrawable draw, unsigned long * event_mask);
typedef __GLXextFuncPtr (APIENTRYP PFNGLXGETPROCADDRESSPROC)(const GLubyte * procName);
typedef unsigned int (APIENTRYP PFNGLXGETGPUIDSAMDPROC)(unsigned int maxCount, unsigned int * ids);
typedef int (APIENTRYP PFNGLXGETGPUINFOAMDPROC)(unsigned int id, int property, GLenum dataType, unsigned int size, void * data);
typedef unsigned int (APIENTRYP PFNGLXGETCONTEXTGPUIDAMDPROC)(GLXContext ctx);
typedef GLXContext (APIENTRYP PFNGLXCREATEASSOCIATEDCONTEXTAMDPROC)(unsigned int id, GLXContext share_list);
typedef GLXContext (APIENTRYP PFNGLXCREATEASSOCIATEDCONTEXTATTRIBSAMDPROC)(unsigned int id, GLXContext share_context, const int * attribList);
typedef Bool (APIENTRYP PFNGLXDELETEASSOCIATEDCONTEXTAMDPROC)(GLXContext ctx);
typedef Bool (APIENTRYP PFNGLXMAKEASSOCIATEDCONTEXTCURRENTAMDPROC)(GLXContext ctx);
typedef GLXContext (APIENTRYP PFNGLXGETCURRENTASSOCIATEDCONTEXTAMDPROC)(void);
typedef void (APIENTRYP PFNGLXBLITCONTEXTFRAMEBUFFERAMDPROC)(GLXContext dstCtx, GLint srcX0, GLint srcY0, GLint srcX1, GLint srcY1, GLint dstX0, GLint dstY0, GLint dstX1, GLint dstY1, GLbitfield mask, GLenum filter);
typedef GLXContext (APIENTRYP PFNGLXCREATECONTEXTATTRIBSARBPROC)(Display * dpy, GLXFBConfig config, GLXContext share_context, Bool direct, const int * attrib_list);
typedef __GLXextFuncPtr (APIENTRYP PFNGLXGETPROCADDRESSARBPROC)(const GLubyte * procName);
typedef Display * (APIENTRYP PFNGLXGETCURRENTDISPLAYEXTPROC)(void);
typedef int (APIENTRYP PFNGLXQUERYCONTEXTINFOEXTPROC)(Display * dpy, GLXContext context, int attribute, int * value);
typedef GLXContextID (APIENTRYP PFNGLXGETCONTEXTIDEXTPROC)(const GLXContext context);
typedef GLXContext (APIENTRYP PFNGLXIMPORTCONTEXTEXTPROC)(Display * dpy, GLXContextID contextID);
typedef void (APIENTRYP PFNGLXFREECONTEXTEXTPROC)(Display * dpy, GLXContext context);
typedef void (APIENTRYP PFNGLXSWAPINTERVALEXTPROC)(Display * dpy, GLXDrawable drawable, int interval);
typedef void (APIENTRYP PFNGLXBINDTEXIMAGEEXTPROC)(Display * dpy, GLXDrawable drawable, int buffer, const int * attrib_list);
typedef void (APIENTRYP PFNGLXRELEASETEXIMAGEEXTPROC)(Display * dpy, GLXDrawable drawable, int buffer);
typedef unsigned int (APIENTRYP PFNGLXGETAGPOFFSETMESAPROC)(const void * pointer);
typedef void (APIENTRYP PFNGLXCOPYSUBBUFFERMESAPROC)(Display * dpy, GLXDrawable drawable, int x, int y, int width, int height);
typedef GLXPixmap (APIENTRYP PFNGLXCREATEGLXPIXMAPMESAPROC)(Display * dpy, XVisualInfo * visual, Pixmap pixmap, Colormap cmap);
typedef Bool (APIENTRYP PFNGLXQUERYCURRENTRENDERERINTEGERMESAPROC)(int attribute, unsigned int * value);
typedef const char * (APIENTRYP PFNGLXQUERYCURRENTRENDERERSTRINGMESAPROC)(int attribute);
typedef Bool (APIENTRYP PFNGLXQUERYRENDERERINTEGERMESAPROC)(Display * dpy, int screen, int renderer, int attribute, unsigned int * value);
typedef const char * (APIENTRYP PFNGLXQUERYRENDERERSTRINGMESAPROC)(Display * dpy, int screen, int renderer, int attribute);
typedef Bool (APIENTRYP PFNGLXRELEASEBUFFERSMESAPROC)(Display * dpy, GLXDrawable drawable);
typedef GLboolean (APIENTRYP PFNGLXSET3DFXMODEMESAPROC)(GLint mode);
typedef int (APIENTRYP PFNGLXGETSWAPINTERVALMESAPROC)(void);
typedef int (APIENTRYP PFNGLXSWAPINTERVALMESAPROC)(unsigned int interval);
typedef void (APIENTRYP PFNGLXCOPYBUFFERSUBDATANVPROC)(Display * dpy, GLXContext readCtx, GLXContext writeCtx, GLenum readTarget, GLenum writeTarget, GLintptr readOffset, GLintptr writeOffset, GLsizeiptr size);
typedef void (APIENTRYP PFNGLXNAMEDCOPYBUFFERSUBDATANVPROC)(Display * dpy, GLXContext readCtx, GLXContext writeCtx, GLuint readBuffer, GLuint writeBuffer, GLintptr readOffset, GLintptr writeOffset, GLsizeiptr size);
typedef void (APIENTRYP PFNGLXCOPYIMAGESUBDATANVPROC)(Display * dpy, GLXContext srcCtx, GLuint srcName, GLenum srcTarget, GLint srcLevel, GLint srcX, GLint srcY, GLint srcZ, GLXContext dstCtx, GLuint dstName, GLenum dstTarget, GLint dstLevel, GLint dstX, GLint dstY, GLint dstZ, GLsizei width, GLsizei height, GLsizei depth);
typedef Bool (APIENTRYP PFNGLXDELAYBEFORESWAPNVPROC)(Display * dpy, GLXDrawable drawable, GLfloat seconds);
typedef unsigned int * (APIENTRYP PFNGLXENUMERATEVIDEODEVICESNVPROC)(Display * dpy, int screen, int * nelements);
typedef int (APIENTRYP PFNGLXBINDVIDEODEVICENVPROC)(Display * dpy, unsigned int video_slot, unsigned int video_device, const int * attrib_list);
typedef Bool (APIENTRYP PFNGLXJOINSWAPGROUPNVPROC)(Display * dpy, GLXDrawable drawable, GLuint group);
typedef Bool (APIENTRYP PFNGLXBINDSWAPBARRIERNVPROC)(Display * dpy, GLuint group, GLuint barrier);
typedef Bool (APIENTRYP PFNGLXQUERYSWAPGROUPNVPROC)(Display * dpy, GLXDrawable drawable, GLuint * group, GLuint * barrier);
typedef Bool (APIENTRYP PFNGLXQUERYMAXSWAPGROUPSNVPROC)(Display * dpy, int screen, GLuint * maxGroups, GLuint * maxBarriers);
typedef Bool (APIENTRYP PFNGLXQUERYFRAMECOUNTNVPROC)(Display * dpy, int screen, GLuint * count);
typedef Bool (APIENTRYP PFNGLXRESETFRAMECOUNTNVPROC)(Display * dpy, int screen);
typedef int (APIENTRYP PFNGLXBINDVIDEOCAPTUREDEVICENVPROC)(Display * dpy, unsigned int video_capture_slot, GLXVideoCaptureDeviceNV device);
typedef GLXVideoCaptureDeviceNV * (APIENTRYP PFNGLXENUMERATEVIDEOCAPTUREDEVICESNVPROC)(Display * dpy, int screen, int * nelements);
typedef void (APIENTRYP PFNGLXLOCKVIDEOCAPTUREDEVICENVPROC)(Display * dpy, GLXVideoCaptureDeviceNV device);
typedef int (APIENTRYP PFNGLXQUERYVIDEOCAPTUREDEVICENVPROC)(Display * dpy, GLXVideoCaptureDeviceNV device, int attribute, int * value);
typedef void (APIENTRYP PFNGLXRELEASEVIDEOCAPTUREDEVICENVPROC)(Display * dpy, GLXVideoCaptureDeviceNV device);
typedef int (APIENTRYP PFNGLXGETVIDEODEVICENVPROC)(Display * dpy, int screen, int numVideoDevices, GLXVideoDeviceNV * pVideoDevice);
typedef int (APIENTRYP PFNGLXRELEASEVIDEODEVICENVPROC)(Display * dpy, int screen, GLXVideoDeviceNV VideoDevice);
typedef int (APIENTRYP PFNGLXBINDVIDEOIMAGENVPROC)(Display * dpy, GLXVideoDeviceNV VideoDevice, GLXPbuffer pbuf, int iVideoBuffer);
typedef int (APIENTRYP PFNGLXRELEASEVIDEOIMAGENVPROC)(Display * dpy, GLXPbuffer pbuf);
typedef int (APIENTRYP PFNGLXSENDPBUFFERTOVIDEONVPROC)(Display * dpy, GLXPbuffer pbuf, int iBufferType, unsigned long * pulCounterPbuffer, GLboolean bBlock);
typedef int (APIENTRYP PFNGLXGETVIDEOINFONVPROC)(Display * dpy, int screen, GLXVideoDeviceNV VideoDevice, unsigned long * pulCounterOutputPbuffer, unsigned long * pulCounterOutputVideo);
typedef Bool (APIENTRYP PFNGLXGETSYNCVALUESOMLPROC)(Display * dpy, GLXDrawable drawable, int64_t * ust, int64_t * msc, int64_t * sbc);
typedef Bool (APIENTRYP PFNGLXGETMSCRATEOMLPROC)(Display * dpy, GLXDrawable drawable, int32_t * numerator, int32_t * denominator);
typedef int64_t (APIENTRYP PFNGLXSWAPBUFFERSMSCOMLPROC)(Display * dpy, GLXDrawable drawable, int64_t target_msc, int64_t divisor, int64_t remainder);
typedef Bool (APIENTRYP PFNGLXWAITFORMSCOMLPROC)(Display * dpy, GLXDrawable drawable, int64_t target_msc, int64_t divisor, int64_t remainder, int64_t * ust, int64_t * msc, int64_t * sbc);
typedef Bool (APIENTRYP PFNGLXWAITFORSBCOMLPROC)(Display * dpy, GLXDrawable drawable, int64_t target_sbc, int64_t * ust, int64_t * msc, int64_t * sbc);
typedef void (APIENTRYP PFNGLXCUSHIONSGIPROC)(Display * dpy, Window window, float cushion);
typedef Bool (APIENTRYP PFNGLXMAKECURRENTREADSGIPROC)(Display * dpy, GLXDrawable draw, GLXDrawable read, GLXContext ctx);
typedef GLXDrawable (APIENTRYP PFNGLXGETCURRENTREADDRAWABLESGIPROC)(void);
typedef int (APIENTRYP PFNGLXSWAPINTERVALSGIPROC)(int interval);
typedef int (APIENTRYP PFNGLXGETVIDEOSYNCSGIPROC)(unsigned int * count);
typedef int (APIENTRYP PFNGLXWAITVIDEOSYNCSGIPROC)(int divisor, int remainder, unsigned int * count);
typedef int (APIENTRYP PFNGLXGETFBCONFIGATTRIBSGIXPROC)(Display * dpy, GLXFBConfigSGIX config, int attribute, int * value);
typedef GLXFBConfigSGIX * (APIENTRYP PFNGLXCHOOSEFBCONFIGSGIXPROC)(Display * dpy, int screen, int * attrib_list, int * nelements);
typedef GLXPixmap (APIENTRYP PFNGLXCREATEGLXPIXMAPWITHCONFIGSGIXPROC)(Display * dpy, GLXFBConfigSGIX config, Pixmap pixmap);
typedef GLXContext (APIENTRYP PFNGLXCREATECONTEXTWITHCONFIGSGIXPROC)(Display * dpy, GLXFBConfigSGIX config, int render_type, GLXContext share_list, Bool direct);
typedef XVisualInfo * (APIENTRYP PFNGLXGETVISUALFROMFBCONFIGSGIXPROC)(Display * dpy, GLXFBConfigSGIX config);
typedef GLXFBConfigSGIX (APIENTRYP PFNGLXGETFBCONFIGFROMVISUALSGIXPROC)(Display * dpy, XVisualInfo * vis);
typedef GLXHyperpipeNetworkSGIX * (APIENTRYP PFNGLXQUERYHYPERPIPENETWORKSGIXPROC)(Display * dpy, int * npipes);
typedef int (APIENTRYP PFNGLXHYPERPIPECONFIGSGIXPROC)(Display * dpy, int networkId, int npipes, GLXHyperpipeConfigSGIX * cfg, int * hpId);
typedef GLXHyperpipeConfigSGIX * (APIENTRYP PFNGLXQUERYHYPERPIPECONFIGSGIXPROC)(Display * dpy, int hpId, int * npipes);
typedef int (APIENTRYP PFNGLXDESTROYHYPERPIPECONFIGSGIXPROC)(Display * dpy, int hpId);
typedef int (APIENTRYP PFNGLXBINDHYPERPIPESGIXPROC)(Display * dpy, int hpId);
typedef int (APIENTRYP PFNGLXQUERYHYPERPIPEBESTATTRIBSGIXPROC)(Display * dpy, int timeSlice, int attrib, int size, void * attribList, void * returnAttribList);
typedef int (APIENTRYP PFNGLXHYPERPIPEATTRIBSGIXPROC)(Display * dpy, int timeSlice, int attrib, int size, void * attribList);
typedef int (APIENTRYP PFNGLXQUERYHYPERPIPEATTRIBSGIXPROC)(Display * dpy, int timeSlice, int attrib, int size, void * returnAttribList);
typedef GLXPbufferSGIX (APIENTRYP PFNGLXCREATEGLXPBUFFERSGIXPROC)(Display * dpy, GLXFBConfigSGIX config, unsigned int width, unsigned int height, int * attrib_list);
typedef void (APIENTRYP PFNGLXDESTROYGLXPBUFFERSGIXPROC)(Display * dpy, GLXPbufferSGIX pbuf);
typedef void (APIENTRYP PFNGLXQUERYGLXPBUFFERSGIXPROC)(Display * dpy, GLXPbufferSGIX pbuf, int attribute, unsigned int * value);
typedef void (APIENTRYP PFNGLXSELECTEVENTSGIXPROC)(Display * dpy, GLXDrawable drawable, unsigned long mask);
typedef void (APIENTRYP PFNGLXGETSELECTEDEVENTSGIXPROC)(Display * dpy, GLXDrawable drawable, unsigned long * mask);
typedef void (APIENTRYP PFNGLXBINDSWAPBARRIERSGIXPROC)(Display * dpy, GLXDrawable drawable, int barrier);
typedef Bool (APIENTRYP PFNGLXQUERYMAXSWAPBARRIERSSGIXPROC)(Display * dpy, int screen, int * max);
typedef void (APIENTRYP PFNGLXJOINSWAPGROUPSGIXPROC)(Display * dpy, GLXDrawable drawable, GLXDrawable member);
typedef int (APIENTRYP PFNGLXBINDCHANNELTOWINDOWSGIXPROC)(Display * display, int screen, int channel, Window window);
typedef int (APIENTRYP PFNGLXCHANNELRECTSGIXPROC)(Display * display, int screen, int channel, int x, int y, int w, int h);
typedef int (APIENTRYP PFNGLXQUERYCHANNELRECTSGIXPROC)(Display * display, int screen, int channel, int * dx, int * dy, int * dw, int * dh);
typedef int (APIENTRYP PFNGLXQUERYCHANNELDELTASSGIXPROC)(Display * display, int screen, int channel, int * x, int * y, int * w, int * h);
typedef int (APIENTRYP PFNGLXCHANNELRECTSYNCSGIXPROC)(Display * display, int screen, int channel, GLenum synctype);
typedef Status (APIENTRYP PFNGLXGETTRANSPARENTINDEXSUNPROC)(Display * dpy, Window overlay, Window underlay, unsigned long * pTransparentIndex);



/* ---- Context struct ------------------------------------------------------
   Three anonymous unions give both indexed (array) and named (struct member)
   access to the same memory, at zero runtime cost.

   featArray / extArray: unsigned char flags, one per feature / extension.
   pfnArray: function pointer slots, one per command.

   Anonymous structs inside the unions are a C11 / GCC extension; they are
   universally supported on our target compilers. */
typedef struct GloamGLXContext {
    union {
        unsigned char featArray[5];
        struct {
        /*    0 */ unsigned char VERSION_1_0;
        /*    1 */ unsigned char VERSION_1_1;
        /*    2 */ unsigned char VERSION_1_2;
        /*    3 */ unsigned char VERSION_1_3;
        /*    4 */ unsigned char VERSION_1_4;
        };
    };

    union {
        unsigned char extArray[66];
        struct {
        /*    0 */ unsigned char _3DFX_multisample;
        /*    1 */ unsigned char AMD_gpu_association;
        /*    2 */ unsigned char ARB_context_flush_control;
        /*    3 */ unsigned char ARB_create_context;
        /*    4 */ unsigned char ARB_create_context_no_error;
        /*    5 */ unsigned char ARB_create_context_profile;
        /*    6 */ unsigned char ARB_create_context_robustness;
        /*    7 */ unsigned char ARB_fbconfig_float;
        /*    8 */ unsigned char ARB_framebuffer_sRGB;
        /*    9 */ unsigned char ARB_get_proc_address;
        /*   10 */ unsigned char ARB_multisample;
        /*   11 */ unsigned char ARB_robustness_application_isolation;
        /*   12 */ unsigned char ARB_robustness_share_group_isolation;
        /*   13 */ unsigned char ARB_vertex_buffer_object;
        /*   14 */ unsigned char EXT_buffer_age;
        /*   15 */ unsigned char EXT_context_priority;
        /*   16 */ unsigned char EXT_create_context_es2_profile;
        /*   17 */ unsigned char EXT_create_context_es_profile;
        /*   18 */ unsigned char EXT_fbconfig_packed_float;
        /*   19 */ unsigned char EXT_framebuffer_sRGB;
        /*   20 */ unsigned char EXT_get_drawable_type;
        /*   21 */ unsigned char EXT_import_context;
        /*   22 */ unsigned char EXT_libglvnd;
        /*   23 */ unsigned char EXT_no_config_context;
        /*   24 */ unsigned char EXT_stereo_tree;
        /*   25 */ unsigned char EXT_swap_control;
        /*   26 */ unsigned char EXT_swap_control_tear;
        /*   27 */ unsigned char EXT_texture_from_pixmap;
        /*   28 */ unsigned char EXT_visual_info;
        /*   29 */ unsigned char EXT_visual_rating;
        /*   30 */ unsigned char INTEL_swap_event;
        /*   31 */ unsigned char MESA_agp_offset;
        /*   32 */ unsigned char MESA_copy_sub_buffer;
        /*   33 */ unsigned char MESA_pixmap_colormap;
        /*   34 */ unsigned char MESA_query_renderer;
        /*   35 */ unsigned char MESA_release_buffers;
        /*   36 */ unsigned char MESA_set_3dfx_mode;
        /*   37 */ unsigned char MESA_swap_control;
        /*   38 */ unsigned char NV_copy_buffer;
        /*   39 */ unsigned char NV_copy_image;
        /*   40 */ unsigned char NV_delay_before_swap;
        /*   41 */ unsigned char NV_float_buffer;
        /*   42 */ unsigned char NV_multigpu_context;
        /*   43 */ unsigned char NV_multisample_coverage;
        /*   44 */ unsigned char NV_present_video;
        /*   45 */ unsigned char NV_robustness_video_memory_purge;
        /*   46 */ unsigned char NV_swap_group;
        /*   47 */ unsigned char NV_video_capture;
        /*   48 */ unsigned char NV_video_out;
        /*   49 */ unsigned char OML_swap_method;
        /*   50 */ unsigned char OML_sync_control;
        /*   51 */ unsigned char SGIS_blended_overlay;
        /*   52 */ unsigned char SGIS_multisample;
        /*   53 */ unsigned char SGIS_shared_multisample;
        /*   54 */ unsigned char SGIX_fbconfig;
        /*   55 */ unsigned char SGIX_hyperpipe;
        /*   56 */ unsigned char SGIX_pbuffer;
        /*   57 */ unsigned char SGIX_swap_barrier;
        /*   58 */ unsigned char SGIX_swap_group;
        /*   59 */ unsigned char SGIX_video_resize;
        /*   60 */ unsigned char SGIX_visual_select_group;
        /*   61 */ unsigned char SGI_cushion;
        /*   62 */ unsigned char SGI_make_current_read;
        /*   63 */ unsigned char SGI_swap_control;
        /*   64 */ unsigned char SGI_video_sync;
        /*   65 */ unsigned char SUN_get_transparent_index;
        };
    };

    union {
        void *pfnArray[131];
        struct {
        /*    0 */ PFNGLXCHOOSEVISUALPROC ChooseVisual;
        /*    1 */ PFNGLXCREATECONTEXTPROC CreateContext;
        /*    2 */ PFNGLXDESTROYCONTEXTPROC DestroyContext;
        /*    3 */ PFNGLXMAKECURRENTPROC MakeCurrent;
        /*    4 */ PFNGLXCOPYCONTEXTPROC CopyContext;
        /*    5 */ PFNGLXSWAPBUFFERSPROC SwapBuffers;
        /*    6 */ PFNGLXCREATEGLXPIXMAPPROC CreateGLXPixmap;
        /*    7 */ PFNGLXDESTROYGLXPIXMAPPROC DestroyGLXPixmap;
        /*    8 */ PFNGLXQUERYEXTENSIONPROC QueryExtension;
        /*    9 */ PFNGLXQUERYVERSIONPROC QueryVersion;
        /*   10 */ PFNGLXISDIRECTPROC IsDirect;
        /*   11 */ PFNGLXGETCONFIGPROC GetConfig;
        /*   12 */ PFNGLXGETCURRENTCONTEXTPROC GetCurrentContext;
        /*   13 */ PFNGLXGETCURRENTDRAWABLEPROC GetCurrentDrawable;
        /*   14 */ PFNGLXWAITGLPROC WaitGL;
        /*   15 */ PFNGLXWAITXPROC WaitX;
        /*   16 */ PFNGLXUSEXFONTPROC UseXFont;
        /*   17 */ PFNGLXQUERYEXTENSIONSSTRINGPROC QueryExtensionsString;
        /*   18 */ PFNGLXQUERYSERVERSTRINGPROC QueryServerString;
        /*   19 */ PFNGLXGETCLIENTSTRINGPROC GetClientString;
        /*   20 */ PFNGLXGETCURRENTDISPLAYPROC GetCurrentDisplay;
        /*   21 */ PFNGLXGETFBCONFIGSPROC GetFBConfigs;
        /*   22 */ PFNGLXCHOOSEFBCONFIGPROC ChooseFBConfig;
        /*   23 */ PFNGLXGETFBCONFIGATTRIBPROC GetFBConfigAttrib;
        /*   24 */ PFNGLXGETVISUALFROMFBCONFIGPROC GetVisualFromFBConfig;
        /*   25 */ PFNGLXCREATEWINDOWPROC CreateWindow;
        /*   26 */ PFNGLXDESTROYWINDOWPROC DestroyWindow;
        /*   27 */ PFNGLXCREATEPIXMAPPROC CreatePixmap;
        /*   28 */ PFNGLXDESTROYPIXMAPPROC DestroyPixmap;
        /*   29 */ PFNGLXCREATEPBUFFERPROC CreatePbuffer;
        /*   30 */ PFNGLXDESTROYPBUFFERPROC DestroyPbuffer;
        /*   31 */ PFNGLXQUERYDRAWABLEPROC QueryDrawable;
        /*   32 */ PFNGLXCREATENEWCONTEXTPROC CreateNewContext;
        /*   33 */ PFNGLXMAKECONTEXTCURRENTPROC MakeContextCurrent;
        /*   34 */ PFNGLXGETCURRENTREADDRAWABLEPROC GetCurrentReadDrawable;
        /*   35 */ PFNGLXQUERYCONTEXTPROC QueryContext;
        /*   36 */ PFNGLXSELECTEVENTPROC SelectEvent;
        /*   37 */ PFNGLXGETSELECTEDEVENTPROC GetSelectedEvent;
        /*   38 */ PFNGLXGETPROCADDRESSPROC GetProcAddress;
        /*   39 */ PFNGLXGETGPUIDSAMDPROC GetGPUIDsAMD;
        /*   40 */ PFNGLXGETGPUINFOAMDPROC GetGPUInfoAMD;
        /*   41 */ PFNGLXGETCONTEXTGPUIDAMDPROC GetContextGPUIDAMD;
        /*   42 */ PFNGLXCREATEASSOCIATEDCONTEXTAMDPROC CreateAssociatedContextAMD;
        /*   43 */ PFNGLXCREATEASSOCIATEDCONTEXTATTRIBSAMDPROC CreateAssociatedContextAttribsAMD;
        /*   44 */ PFNGLXDELETEASSOCIATEDCONTEXTAMDPROC DeleteAssociatedContextAMD;
        /*   45 */ PFNGLXMAKEASSOCIATEDCONTEXTCURRENTAMDPROC MakeAssociatedContextCurrentAMD;
        /*   46 */ PFNGLXGETCURRENTASSOCIATEDCONTEXTAMDPROC GetCurrentAssociatedContextAMD;
        /*   47 */ PFNGLXBLITCONTEXTFRAMEBUFFERAMDPROC BlitContextFramebufferAMD;
        /*   48 */ PFNGLXCREATECONTEXTATTRIBSARBPROC CreateContextAttribsARB;
        /*   49 */ PFNGLXGETPROCADDRESSARBPROC GetProcAddressARB;
        /*   50 */ PFNGLXGETCURRENTDISPLAYEXTPROC GetCurrentDisplayEXT;
        /*   51 */ PFNGLXQUERYCONTEXTINFOEXTPROC QueryContextInfoEXT;
        /*   52 */ PFNGLXGETCONTEXTIDEXTPROC GetContextIDEXT;
        /*   53 */ PFNGLXIMPORTCONTEXTEXTPROC ImportContextEXT;
        /*   54 */ PFNGLXFREECONTEXTEXTPROC FreeContextEXT;
        /*   55 */ PFNGLXSWAPINTERVALEXTPROC SwapIntervalEXT;
        /*   56 */ PFNGLXBINDTEXIMAGEEXTPROC BindTexImageEXT;
        /*   57 */ PFNGLXRELEASETEXIMAGEEXTPROC ReleaseTexImageEXT;
        /*   58 */ PFNGLXGETAGPOFFSETMESAPROC GetAGPOffsetMESA;
        /*   59 */ PFNGLXCOPYSUBBUFFERMESAPROC CopySubBufferMESA;
        /*   60 */ PFNGLXCREATEGLXPIXMAPMESAPROC CreateGLXPixmapMESA;
        /*   61 */ PFNGLXQUERYCURRENTRENDERERINTEGERMESAPROC QueryCurrentRendererIntegerMESA;
        /*   62 */ PFNGLXQUERYCURRENTRENDERERSTRINGMESAPROC QueryCurrentRendererStringMESA;
        /*   63 */ PFNGLXQUERYRENDERERINTEGERMESAPROC QueryRendererIntegerMESA;
        /*   64 */ PFNGLXQUERYRENDERERSTRINGMESAPROC QueryRendererStringMESA;
        /*   65 */ PFNGLXRELEASEBUFFERSMESAPROC ReleaseBuffersMESA;
        /*   66 */ PFNGLXSET3DFXMODEMESAPROC Set3DfxModeMESA;
        /*   67 */ PFNGLXGETSWAPINTERVALMESAPROC GetSwapIntervalMESA;
        /*   68 */ PFNGLXSWAPINTERVALMESAPROC SwapIntervalMESA;
        /*   69 */ PFNGLXCOPYBUFFERSUBDATANVPROC CopyBufferSubDataNV;
        /*   70 */ PFNGLXNAMEDCOPYBUFFERSUBDATANVPROC NamedCopyBufferSubDataNV;
        /*   71 */ PFNGLXCOPYIMAGESUBDATANVPROC CopyImageSubDataNV;
        /*   72 */ PFNGLXDELAYBEFORESWAPNVPROC DelayBeforeSwapNV;
        /*   73 */ PFNGLXENUMERATEVIDEODEVICESNVPROC EnumerateVideoDevicesNV;
        /*   74 */ PFNGLXBINDVIDEODEVICENVPROC BindVideoDeviceNV;
        /*   75 */ PFNGLXJOINSWAPGROUPNVPROC JoinSwapGroupNV;
        /*   76 */ PFNGLXBINDSWAPBARRIERNVPROC BindSwapBarrierNV;
        /*   77 */ PFNGLXQUERYSWAPGROUPNVPROC QuerySwapGroupNV;
        /*   78 */ PFNGLXQUERYMAXSWAPGROUPSNVPROC QueryMaxSwapGroupsNV;
        /*   79 */ PFNGLXQUERYFRAMECOUNTNVPROC QueryFrameCountNV;
        /*   80 */ PFNGLXRESETFRAMECOUNTNVPROC ResetFrameCountNV;
        /*   81 */ PFNGLXBINDVIDEOCAPTUREDEVICENVPROC BindVideoCaptureDeviceNV;
        /*   82 */ PFNGLXENUMERATEVIDEOCAPTUREDEVICESNVPROC EnumerateVideoCaptureDevicesNV;
        /*   83 */ PFNGLXLOCKVIDEOCAPTUREDEVICENVPROC LockVideoCaptureDeviceNV;
        /*   84 */ PFNGLXQUERYVIDEOCAPTUREDEVICENVPROC QueryVideoCaptureDeviceNV;
        /*   85 */ PFNGLXRELEASEVIDEOCAPTUREDEVICENVPROC ReleaseVideoCaptureDeviceNV;
        /*   86 */ PFNGLXGETVIDEODEVICENVPROC GetVideoDeviceNV;
        /*   87 */ PFNGLXRELEASEVIDEODEVICENVPROC ReleaseVideoDeviceNV;
        /*   88 */ PFNGLXBINDVIDEOIMAGENVPROC BindVideoImageNV;
        /*   89 */ PFNGLXRELEASEVIDEOIMAGENVPROC ReleaseVideoImageNV;
        /*   90 */ PFNGLXSENDPBUFFERTOVIDEONVPROC SendPbufferToVideoNV;
        /*   91 */ PFNGLXGETVIDEOINFONVPROC GetVideoInfoNV;
        /*   92 */ PFNGLXGETSYNCVALUESOMLPROC GetSyncValuesOML;
        /*   93 */ PFNGLXGETMSCRATEOMLPROC GetMscRateOML;
        /*   94 */ PFNGLXSWAPBUFFERSMSCOMLPROC SwapBuffersMscOML;
        /*   95 */ PFNGLXWAITFORMSCOMLPROC WaitForMscOML;
        /*   96 */ PFNGLXWAITFORSBCOMLPROC WaitForSbcOML;
        /*   97 */ PFNGLXCUSHIONSGIPROC CushionSGI;
        /*   98 */ PFNGLXMAKECURRENTREADSGIPROC MakeCurrentReadSGI;
        /*   99 */ PFNGLXGETCURRENTREADDRAWABLESGIPROC GetCurrentReadDrawableSGI;
        /*  100 */ PFNGLXSWAPINTERVALSGIPROC SwapIntervalSGI;
        /*  101 */ PFNGLXGETVIDEOSYNCSGIPROC GetVideoSyncSGI;
        /*  102 */ PFNGLXWAITVIDEOSYNCSGIPROC WaitVideoSyncSGI;
        /*  103 */ PFNGLXGETFBCONFIGATTRIBSGIXPROC GetFBConfigAttribSGIX;
        /*  104 */ PFNGLXCHOOSEFBCONFIGSGIXPROC ChooseFBConfigSGIX;
        /*  105 */ PFNGLXCREATEGLXPIXMAPWITHCONFIGSGIXPROC CreateGLXPixmapWithConfigSGIX;
        /*  106 */ PFNGLXCREATECONTEXTWITHCONFIGSGIXPROC CreateContextWithConfigSGIX;
        /*  107 */ PFNGLXGETVISUALFROMFBCONFIGSGIXPROC GetVisualFromFBConfigSGIX;
        /*  108 */ PFNGLXGETFBCONFIGFROMVISUALSGIXPROC GetFBConfigFromVisualSGIX;
        /*  109 */ PFNGLXQUERYHYPERPIPENETWORKSGIXPROC QueryHyperpipeNetworkSGIX;
        /*  110 */ PFNGLXHYPERPIPECONFIGSGIXPROC HyperpipeConfigSGIX;
        /*  111 */ PFNGLXQUERYHYPERPIPECONFIGSGIXPROC QueryHyperpipeConfigSGIX;
        /*  112 */ PFNGLXDESTROYHYPERPIPECONFIGSGIXPROC DestroyHyperpipeConfigSGIX;
        /*  113 */ PFNGLXBINDHYPERPIPESGIXPROC BindHyperpipeSGIX;
        /*  114 */ PFNGLXQUERYHYPERPIPEBESTATTRIBSGIXPROC QueryHyperpipeBestAttribSGIX;
        /*  115 */ PFNGLXHYPERPIPEATTRIBSGIXPROC HyperpipeAttribSGIX;
        /*  116 */ PFNGLXQUERYHYPERPIPEATTRIBSGIXPROC QueryHyperpipeAttribSGIX;
        /*  117 */ PFNGLXCREATEGLXPBUFFERSGIXPROC CreateGLXPbufferSGIX;
        /*  118 */ PFNGLXDESTROYGLXPBUFFERSGIXPROC DestroyGLXPbufferSGIX;
        /*  119 */ PFNGLXQUERYGLXPBUFFERSGIXPROC QueryGLXPbufferSGIX;
        /*  120 */ PFNGLXSELECTEVENTSGIXPROC SelectEventSGIX;
        /*  121 */ PFNGLXGETSELECTEDEVENTSGIXPROC GetSelectedEventSGIX;
        /*  122 */ PFNGLXBINDSWAPBARRIERSGIXPROC BindSwapBarrierSGIX;
        /*  123 */ PFNGLXQUERYMAXSWAPBARRIERSSGIXPROC QueryMaxSwapBarriersSGIX;
        /*  124 */ PFNGLXJOINSWAPGROUPSGIXPROC JoinSwapGroupSGIX;
        /*  125 */ PFNGLXBINDCHANNELTOWINDOWSGIXPROC BindChannelToWindowSGIX;
        /*  126 */ PFNGLXCHANNELRECTSGIXPROC ChannelRectSGIX;
        /*  127 */ PFNGLXQUERYCHANNELRECTSGIXPROC QueryChannelRectSGIX;
        /*  128 */ PFNGLXQUERYCHANNELDELTASSGIXPROC QueryChannelDeltasSGIX;
        /*  129 */ PFNGLXCHANNELRECTSYNCSGIXPROC ChannelRectSyncSGIX;
        /*  130 */ PFNGLXGETTRANSPARENTINDEXSUNPROC GetTransparentIndexSUN;
        };
    };
    /* Built-in loader library handle.  Set by gloamLoaderLoad*Context when it
       opens the platform library.  Pre-populate before calling that function
       to supply your own handle (dlopen is then skipped); zero it before
       calling gloamLoaderUnload*Context to prevent it closing a handle you
       still own.  Present on all context types so user code can use a single
       field name regardless of API. */
    void *gloam_loader_handle;


} GloamGLXContext;

/* Global context instance — a value, not a pointer, so the compiler knows
   its address is fixed and does not re-load it on every access. */
extern GloamGLXContext gloam_glx_context;

/* ---- Feature presence macros --------------------------------------------
   Test whether a versioned feature was detected at load time. */
#define GLOAM_GLX_VERSION_1_0 (gloam_glx_context.VERSION_1_0)
#define GLOAM_GLX_VERSION_1_1 (gloam_glx_context.VERSION_1_1)
#define GLOAM_GLX_VERSION_1_2 (gloam_glx_context.VERSION_1_2)
#define GLOAM_GLX_VERSION_1_3 (gloam_glx_context.VERSION_1_3)
#define GLOAM_GLX_VERSION_1_4 (gloam_glx_context.VERSION_1_4)

/* ---- Extension presence macros ------------------------------------------ */
#define GLOAM_GLX_3DFX_multisample (gloam_glx_context._3DFX_multisample)
#define GLOAM_GLX_AMD_gpu_association (gloam_glx_context.AMD_gpu_association)
#define GLOAM_GLX_ARB_context_flush_control (gloam_glx_context.ARB_context_flush_control)
#define GLOAM_GLX_ARB_create_context (gloam_glx_context.ARB_create_context)
#define GLOAM_GLX_ARB_create_context_no_error (gloam_glx_context.ARB_create_context_no_error)
#define GLOAM_GLX_ARB_create_context_profile (gloam_glx_context.ARB_create_context_profile)
#define GLOAM_GLX_ARB_create_context_robustness (gloam_glx_context.ARB_create_context_robustness)
#define GLOAM_GLX_ARB_fbconfig_float (gloam_glx_context.ARB_fbconfig_float)
#define GLOAM_GLX_ARB_framebuffer_sRGB (gloam_glx_context.ARB_framebuffer_sRGB)
#define GLOAM_GLX_ARB_get_proc_address (gloam_glx_context.ARB_get_proc_address)
#define GLOAM_GLX_ARB_multisample (gloam_glx_context.ARB_multisample)
#define GLOAM_GLX_ARB_robustness_application_isolation (gloam_glx_context.ARB_robustness_application_isolation)
#define GLOAM_GLX_ARB_robustness_share_group_isolation (gloam_glx_context.ARB_robustness_share_group_isolation)
#define GLOAM_GLX_ARB_vertex_buffer_object (gloam_glx_context.ARB_vertex_buffer_object)
#define GLOAM_GLX_EXT_buffer_age (gloam_glx_context.EXT_buffer_age)
#define GLOAM_GLX_EXT_context_priority (gloam_glx_context.EXT_context_priority)
#define GLOAM_GLX_EXT_create_context_es2_profile (gloam_glx_context.EXT_create_context_es2_profile)
#define GLOAM_GLX_EXT_create_context_es_profile (gloam_glx_context.EXT_create_context_es_profile)
#define GLOAM_GLX_EXT_fbconfig_packed_float (gloam_glx_context.EXT_fbconfig_packed_float)
#define GLOAM_GLX_EXT_framebuffer_sRGB (gloam_glx_context.EXT_framebuffer_sRGB)
#define GLOAM_GLX_EXT_get_drawable_type (gloam_glx_context.EXT_get_drawable_type)
#define GLOAM_GLX_EXT_import_context (gloam_glx_context.EXT_import_context)
#define GLOAM_GLX_EXT_libglvnd (gloam_glx_context.EXT_libglvnd)
#define GLOAM_GLX_EXT_no_config_context (gloam_glx_context.EXT_no_config_context)
#define GLOAM_GLX_EXT_stereo_tree (gloam_glx_context.EXT_stereo_tree)
#define GLOAM_GLX_EXT_swap_control (gloam_glx_context.EXT_swap_control)
#define GLOAM_GLX_EXT_swap_control_tear (gloam_glx_context.EXT_swap_control_tear)
#define GLOAM_GLX_EXT_texture_from_pixmap (gloam_glx_context.EXT_texture_from_pixmap)
#define GLOAM_GLX_EXT_visual_info (gloam_glx_context.EXT_visual_info)
#define GLOAM_GLX_EXT_visual_rating (gloam_glx_context.EXT_visual_rating)
#define GLOAM_GLX_INTEL_swap_event (gloam_glx_context.INTEL_swap_event)
#define GLOAM_GLX_MESA_agp_offset (gloam_glx_context.MESA_agp_offset)
#define GLOAM_GLX_MESA_copy_sub_buffer (gloam_glx_context.MESA_copy_sub_buffer)
#define GLOAM_GLX_MESA_pixmap_colormap (gloam_glx_context.MESA_pixmap_colormap)
#define GLOAM_GLX_MESA_query_renderer (gloam_glx_context.MESA_query_renderer)
#define GLOAM_GLX_MESA_release_buffers (gloam_glx_context.MESA_release_buffers)
#define GLOAM_GLX_MESA_set_3dfx_mode (gloam_glx_context.MESA_set_3dfx_mode)
#define GLOAM_GLX_MESA_swap_control (gloam_glx_context.MESA_swap_control)
#define GLOAM_GLX_NV_copy_buffer (gloam_glx_context.NV_copy_buffer)
#define GLOAM_GLX_NV_copy_image (gloam_glx_context.NV_copy_image)
#define GLOAM_GLX_NV_delay_before_swap (gloam_glx_context.NV_delay_before_swap)
#define GLOAM_GLX_NV_float_buffer (gloam_glx_context.NV_float_buffer)
#define GLOAM_GLX_NV_multigpu_context (gloam_glx_context.NV_multigpu_context)
#define GLOAM_GLX_NV_multisample_coverage (gloam_glx_context.NV_multisample_coverage)
#define GLOAM_GLX_NV_present_video (gloam_glx_context.NV_present_video)
#define GLOAM_GLX_NV_robustness_video_memory_purge (gloam_glx_context.NV_robustness_video_memory_purge)
#define GLOAM_GLX_NV_swap_group (gloam_glx_context.NV_swap_group)
#define GLOAM_GLX_NV_video_capture (gloam_glx_context.NV_video_capture)
#define GLOAM_GLX_NV_video_out (gloam_glx_context.NV_video_out)
#define GLOAM_GLX_OML_swap_method (gloam_glx_context.OML_swap_method)
#define GLOAM_GLX_OML_sync_control (gloam_glx_context.OML_sync_control)
#define GLOAM_GLX_SGIS_blended_overlay (gloam_glx_context.SGIS_blended_overlay)
#define GLOAM_GLX_SGIS_multisample (gloam_glx_context.SGIS_multisample)
#define GLOAM_GLX_SGIS_shared_multisample (gloam_glx_context.SGIS_shared_multisample)
#define GLOAM_GLX_SGIX_fbconfig (gloam_glx_context.SGIX_fbconfig)
#define GLOAM_GLX_SGIX_hyperpipe (gloam_glx_context.SGIX_hyperpipe)
#define GLOAM_GLX_SGIX_pbuffer (gloam_glx_context.SGIX_pbuffer)
#define GLOAM_GLX_SGIX_swap_barrier (gloam_glx_context.SGIX_swap_barrier)
#define GLOAM_GLX_SGIX_swap_group (gloam_glx_context.SGIX_swap_group)
#define GLOAM_GLX_SGIX_video_resize (gloam_glx_context.SGIX_video_resize)
#define GLOAM_GLX_SGIX_visual_select_group (gloam_glx_context.SGIX_visual_select_group)
#define GLOAM_GLX_SGI_cushion (gloam_glx_context.SGI_cushion)
#define GLOAM_GLX_SGI_make_current_read (gloam_glx_context.SGI_make_current_read)
#define GLOAM_GLX_SGI_swap_control (gloam_glx_context.SGI_swap_control)
#define GLOAM_GLX_SGI_video_sync (gloam_glx_context.SGI_video_sync)
#define GLOAM_GLX_SUN_get_transparent_index (gloam_glx_context.SUN_get_transparent_index)


/* ---- Dispatch macros and IntelliSense prototypes -------------------------
   Under __INTELLISENSE__ we expose real function declarations so IDEs can
   provide parameter info and type checking.  In normal compilation the macros
   dispatch directly through the global context struct. */
#ifdef __INTELLISENSE__
XVisualInfo * glXChooseVisual(Display * dpy, int screen, int * attribList);
GLXContext glXCreateContext(Display * dpy, XVisualInfo * vis, GLXContext shareList, Bool direct);
void glXDestroyContext(Display * dpy, GLXContext ctx);
Bool glXMakeCurrent(Display * dpy, GLXDrawable drawable, GLXContext ctx);
void glXCopyContext(Display * dpy, GLXContext src, GLXContext dst, unsigned long mask);
void glXSwapBuffers(Display * dpy, GLXDrawable drawable);
GLXPixmap glXCreateGLXPixmap(Display * dpy, XVisualInfo * visual, Pixmap pixmap);
void glXDestroyGLXPixmap(Display * dpy, GLXPixmap pixmap);
Bool glXQueryExtension(Display * dpy, int * errorb, int * event);
Bool glXQueryVersion(Display * dpy, int * maj, int * min);
Bool glXIsDirect(Display * dpy, GLXContext ctx);
int glXGetConfig(Display * dpy, XVisualInfo * visual, int attrib, int * value);
GLXContext glXGetCurrentContext(void);
GLXDrawable glXGetCurrentDrawable(void);
void glXWaitGL(void);
void glXWaitX(void);
void glXUseXFont(Font font, int first, int count, int list);
const char * glXQueryExtensionsString(Display * dpy, int screen);
const char * glXQueryServerString(Display * dpy, int screen, int name);
const char * glXGetClientString(Display * dpy, int name);
Display * glXGetCurrentDisplay(void);
GLXFBConfig * glXGetFBConfigs(Display * dpy, int screen, int * nelements);
GLXFBConfig * glXChooseFBConfig(Display * dpy, int screen, const int * attrib_list, int * nelements);
int glXGetFBConfigAttrib(Display * dpy, GLXFBConfig config, int attribute, int * value);
XVisualInfo * glXGetVisualFromFBConfig(Display * dpy, GLXFBConfig config);
GLXWindow glXCreateWindow(Display * dpy, GLXFBConfig config, Window win, const int * attrib_list);
void glXDestroyWindow(Display * dpy, GLXWindow win);
GLXPixmap glXCreatePixmap(Display * dpy, GLXFBConfig config, Pixmap pixmap, const int * attrib_list);
void glXDestroyPixmap(Display * dpy, GLXPixmap pixmap);
GLXPbuffer glXCreatePbuffer(Display * dpy, GLXFBConfig config, const int * attrib_list);
void glXDestroyPbuffer(Display * dpy, GLXPbuffer pbuf);
void glXQueryDrawable(Display * dpy, GLXDrawable draw, int attribute, unsigned int * value);
GLXContext glXCreateNewContext(Display * dpy, GLXFBConfig config, int render_type, GLXContext share_list, Bool direct);
Bool glXMakeContextCurrent(Display * dpy, GLXDrawable draw, GLXDrawable read, GLXContext ctx);
GLXDrawable glXGetCurrentReadDrawable(void);
int glXQueryContext(Display * dpy, GLXContext ctx, int attribute, int * value);
void glXSelectEvent(Display * dpy, GLXDrawable draw, unsigned long event_mask);
void glXGetSelectedEvent(Display * dpy, GLXDrawable draw, unsigned long * event_mask);
__GLXextFuncPtr glXGetProcAddress(const GLubyte * procName);
unsigned int glXGetGPUIDsAMD(unsigned int maxCount, unsigned int * ids);
int glXGetGPUInfoAMD(unsigned int id, int property, GLenum dataType, unsigned int size, void * data);
unsigned int glXGetContextGPUIDAMD(GLXContext ctx);
GLXContext glXCreateAssociatedContextAMD(unsigned int id, GLXContext share_list);
GLXContext glXCreateAssociatedContextAttribsAMD(unsigned int id, GLXContext share_context, const int * attribList);
Bool glXDeleteAssociatedContextAMD(GLXContext ctx);
Bool glXMakeAssociatedContextCurrentAMD(GLXContext ctx);
GLXContext glXGetCurrentAssociatedContextAMD(void);
void glXBlitContextFramebufferAMD(GLXContext dstCtx, GLint srcX0, GLint srcY0, GLint srcX1, GLint srcY1, GLint dstX0, GLint dstY0, GLint dstX1, GLint dstY1, GLbitfield mask, GLenum filter);
GLXContext glXCreateContextAttribsARB(Display * dpy, GLXFBConfig config, GLXContext share_context, Bool direct, const int * attrib_list);
__GLXextFuncPtr glXGetProcAddressARB(const GLubyte * procName);
Display * glXGetCurrentDisplayEXT(void);
int glXQueryContextInfoEXT(Display * dpy, GLXContext context, int attribute, int * value);
GLXContextID glXGetContextIDEXT(const GLXContext context);
GLXContext glXImportContextEXT(Display * dpy, GLXContextID contextID);
void glXFreeContextEXT(Display * dpy, GLXContext context);
void glXSwapIntervalEXT(Display * dpy, GLXDrawable drawable, int interval);
void glXBindTexImageEXT(Display * dpy, GLXDrawable drawable, int buffer, const int * attrib_list);
void glXReleaseTexImageEXT(Display * dpy, GLXDrawable drawable, int buffer);
unsigned int glXGetAGPOffsetMESA(const void * pointer);
void glXCopySubBufferMESA(Display * dpy, GLXDrawable drawable, int x, int y, int width, int height);
GLXPixmap glXCreateGLXPixmapMESA(Display * dpy, XVisualInfo * visual, Pixmap pixmap, Colormap cmap);
Bool glXQueryCurrentRendererIntegerMESA(int attribute, unsigned int * value);
const char * glXQueryCurrentRendererStringMESA(int attribute);
Bool glXQueryRendererIntegerMESA(Display * dpy, int screen, int renderer, int attribute, unsigned int * value);
const char * glXQueryRendererStringMESA(Display * dpy, int screen, int renderer, int attribute);
Bool glXReleaseBuffersMESA(Display * dpy, GLXDrawable drawable);
GLboolean glXSet3DfxModeMESA(GLint mode);
int glXGetSwapIntervalMESA(void);
int glXSwapIntervalMESA(unsigned int interval);
void glXCopyBufferSubDataNV(Display * dpy, GLXContext readCtx, GLXContext writeCtx, GLenum readTarget, GLenum writeTarget, GLintptr readOffset, GLintptr writeOffset, GLsizeiptr size);
void glXNamedCopyBufferSubDataNV(Display * dpy, GLXContext readCtx, GLXContext writeCtx, GLuint readBuffer, GLuint writeBuffer, GLintptr readOffset, GLintptr writeOffset, GLsizeiptr size);
void glXCopyImageSubDataNV(Display * dpy, GLXContext srcCtx, GLuint srcName, GLenum srcTarget, GLint srcLevel, GLint srcX, GLint srcY, GLint srcZ, GLXContext dstCtx, GLuint dstName, GLenum dstTarget, GLint dstLevel, GLint dstX, GLint dstY, GLint dstZ, GLsizei width, GLsizei height, GLsizei depth);
Bool glXDelayBeforeSwapNV(Display * dpy, GLXDrawable drawable, GLfloat seconds);
unsigned int * glXEnumerateVideoDevicesNV(Display * dpy, int screen, int * nelements);
int glXBindVideoDeviceNV(Display * dpy, unsigned int video_slot, unsigned int video_device, const int * attrib_list);
Bool glXJoinSwapGroupNV(Display * dpy, GLXDrawable drawable, GLuint group);
Bool glXBindSwapBarrierNV(Display * dpy, GLuint group, GLuint barrier);
Bool glXQuerySwapGroupNV(Display * dpy, GLXDrawable drawable, GLuint * group, GLuint * barrier);
Bool glXQueryMaxSwapGroupsNV(Display * dpy, int screen, GLuint * maxGroups, GLuint * maxBarriers);
Bool glXQueryFrameCountNV(Display * dpy, int screen, GLuint * count);
Bool glXResetFrameCountNV(Display * dpy, int screen);
int glXBindVideoCaptureDeviceNV(Display * dpy, unsigned int video_capture_slot, GLXVideoCaptureDeviceNV device);
GLXVideoCaptureDeviceNV * glXEnumerateVideoCaptureDevicesNV(Display * dpy, int screen, int * nelements);
void glXLockVideoCaptureDeviceNV(Display * dpy, GLXVideoCaptureDeviceNV device);
int glXQueryVideoCaptureDeviceNV(Display * dpy, GLXVideoCaptureDeviceNV device, int attribute, int * value);
void glXReleaseVideoCaptureDeviceNV(Display * dpy, GLXVideoCaptureDeviceNV device);
int glXGetVideoDeviceNV(Display * dpy, int screen, int numVideoDevices, GLXVideoDeviceNV * pVideoDevice);
int glXReleaseVideoDeviceNV(Display * dpy, int screen, GLXVideoDeviceNV VideoDevice);
int glXBindVideoImageNV(Display * dpy, GLXVideoDeviceNV VideoDevice, GLXPbuffer pbuf, int iVideoBuffer);
int glXReleaseVideoImageNV(Display * dpy, GLXPbuffer pbuf);
int glXSendPbufferToVideoNV(Display * dpy, GLXPbuffer pbuf, int iBufferType, unsigned long * pulCounterPbuffer, GLboolean bBlock);
int glXGetVideoInfoNV(Display * dpy, int screen, GLXVideoDeviceNV VideoDevice, unsigned long * pulCounterOutputPbuffer, unsigned long * pulCounterOutputVideo);
Bool glXGetSyncValuesOML(Display * dpy, GLXDrawable drawable, int64_t * ust, int64_t * msc, int64_t * sbc);
Bool glXGetMscRateOML(Display * dpy, GLXDrawable drawable, int32_t * numerator, int32_t * denominator);
int64_t glXSwapBuffersMscOML(Display * dpy, GLXDrawable drawable, int64_t target_msc, int64_t divisor, int64_t remainder);
Bool glXWaitForMscOML(Display * dpy, GLXDrawable drawable, int64_t target_msc, int64_t divisor, int64_t remainder, int64_t * ust, int64_t * msc, int64_t * sbc);
Bool glXWaitForSbcOML(Display * dpy, GLXDrawable drawable, int64_t target_sbc, int64_t * ust, int64_t * msc, int64_t * sbc);
void glXCushionSGI(Display * dpy, Window window, float cushion);
Bool glXMakeCurrentReadSGI(Display * dpy, GLXDrawable draw, GLXDrawable read, GLXContext ctx);
GLXDrawable glXGetCurrentReadDrawableSGI(void);
int glXSwapIntervalSGI(int interval);
int glXGetVideoSyncSGI(unsigned int * count);
int glXWaitVideoSyncSGI(int divisor, int remainder, unsigned int * count);
int glXGetFBConfigAttribSGIX(Display * dpy, GLXFBConfigSGIX config, int attribute, int * value);
GLXFBConfigSGIX * glXChooseFBConfigSGIX(Display * dpy, int screen, int * attrib_list, int * nelements);
GLXPixmap glXCreateGLXPixmapWithConfigSGIX(Display * dpy, GLXFBConfigSGIX config, Pixmap pixmap);
GLXContext glXCreateContextWithConfigSGIX(Display * dpy, GLXFBConfigSGIX config, int render_type, GLXContext share_list, Bool direct);
XVisualInfo * glXGetVisualFromFBConfigSGIX(Display * dpy, GLXFBConfigSGIX config);
GLXFBConfigSGIX glXGetFBConfigFromVisualSGIX(Display * dpy, XVisualInfo * vis);
GLXHyperpipeNetworkSGIX * glXQueryHyperpipeNetworkSGIX(Display * dpy, int * npipes);
int glXHyperpipeConfigSGIX(Display * dpy, int networkId, int npipes, GLXHyperpipeConfigSGIX * cfg, int * hpId);
GLXHyperpipeConfigSGIX * glXQueryHyperpipeConfigSGIX(Display * dpy, int hpId, int * npipes);
int glXDestroyHyperpipeConfigSGIX(Display * dpy, int hpId);
int glXBindHyperpipeSGIX(Display * dpy, int hpId);
int glXQueryHyperpipeBestAttribSGIX(Display * dpy, int timeSlice, int attrib, int size, void * attribList, void * returnAttribList);
int glXHyperpipeAttribSGIX(Display * dpy, int timeSlice, int attrib, int size, void * attribList);
int glXQueryHyperpipeAttribSGIX(Display * dpy, int timeSlice, int attrib, int size, void * returnAttribList);
GLXPbufferSGIX glXCreateGLXPbufferSGIX(Display * dpy, GLXFBConfigSGIX config, unsigned int width, unsigned int height, int * attrib_list);
void glXDestroyGLXPbufferSGIX(Display * dpy, GLXPbufferSGIX pbuf);
void glXQueryGLXPbufferSGIX(Display * dpy, GLXPbufferSGIX pbuf, int attribute, unsigned int * value);
void glXSelectEventSGIX(Display * dpy, GLXDrawable drawable, unsigned long mask);
void glXGetSelectedEventSGIX(Display * dpy, GLXDrawable drawable, unsigned long * mask);
void glXBindSwapBarrierSGIX(Display * dpy, GLXDrawable drawable, int barrier);
Bool glXQueryMaxSwapBarriersSGIX(Display * dpy, int screen, int * max);
void glXJoinSwapGroupSGIX(Display * dpy, GLXDrawable drawable, GLXDrawable member);
int glXBindChannelToWindowSGIX(Display * display, int screen, int channel, Window window);
int glXChannelRectSGIX(Display * display, int screen, int channel, int x, int y, int w, int h);
int glXQueryChannelRectSGIX(Display * display, int screen, int channel, int * dx, int * dy, int * dw, int * dh);
int glXQueryChannelDeltasSGIX(Display * display, int screen, int channel, int * x, int * y, int * w, int * h);
int glXChannelRectSyncSGIX(Display * display, int screen, int channel, GLenum synctype);
Status glXGetTransparentIndexSUN(Display * dpy, Window overlay, Window underlay, unsigned long * pTransparentIndex);
#else
#define glXChooseVisual (gloam_glx_context.ChooseVisual)
#define glXCreateContext (gloam_glx_context.CreateContext)
#define glXDestroyContext (gloam_glx_context.DestroyContext)
#define glXMakeCurrent (gloam_glx_context.MakeCurrent)
#define glXCopyContext (gloam_glx_context.CopyContext)
#define glXSwapBuffers (gloam_glx_context.SwapBuffers)
#define glXCreateGLXPixmap (gloam_glx_context.CreateGLXPixmap)
#define glXDestroyGLXPixmap (gloam_glx_context.DestroyGLXPixmap)
#define glXQueryExtension (gloam_glx_context.QueryExtension)
#define glXQueryVersion (gloam_glx_context.QueryVersion)
#define glXIsDirect (gloam_glx_context.IsDirect)
#define glXGetConfig (gloam_glx_context.GetConfig)
#define glXGetCurrentContext (gloam_glx_context.GetCurrentContext)
#define glXGetCurrentDrawable (gloam_glx_context.GetCurrentDrawable)
#define glXWaitGL (gloam_glx_context.WaitGL)
#define glXWaitX (gloam_glx_context.WaitX)
#define glXUseXFont (gloam_glx_context.UseXFont)
#define glXQueryExtensionsString (gloam_glx_context.QueryExtensionsString)
#define glXQueryServerString (gloam_glx_context.QueryServerString)
#define glXGetClientString (gloam_glx_context.GetClientString)
#define glXGetCurrentDisplay (gloam_glx_context.GetCurrentDisplay)
#define glXGetFBConfigs (gloam_glx_context.GetFBConfigs)
#define glXChooseFBConfig (gloam_glx_context.ChooseFBConfig)
#define glXGetFBConfigAttrib (gloam_glx_context.GetFBConfigAttrib)
#define glXGetVisualFromFBConfig (gloam_glx_context.GetVisualFromFBConfig)
#define glXCreateWindow (gloam_glx_context.CreateWindow)
#define glXDestroyWindow (gloam_glx_context.DestroyWindow)
#define glXCreatePixmap (gloam_glx_context.CreatePixmap)
#define glXDestroyPixmap (gloam_glx_context.DestroyPixmap)
#define glXCreatePbuffer (gloam_glx_context.CreatePbuffer)
#define glXDestroyPbuffer (gloam_glx_context.DestroyPbuffer)
#define glXQueryDrawable (gloam_glx_context.QueryDrawable)
#define glXCreateNewContext (gloam_glx_context.CreateNewContext)
#define glXMakeContextCurrent (gloam_glx_context.MakeContextCurrent)
#define glXGetCurrentReadDrawable (gloam_glx_context.GetCurrentReadDrawable)
#define glXQueryContext (gloam_glx_context.QueryContext)
#define glXSelectEvent (gloam_glx_context.SelectEvent)
#define glXGetSelectedEvent (gloam_glx_context.GetSelectedEvent)
#define glXGetProcAddress (gloam_glx_context.GetProcAddress)
#define glXGetGPUIDsAMD (gloam_glx_context.GetGPUIDsAMD)
#define glXGetGPUInfoAMD (gloam_glx_context.GetGPUInfoAMD)
#define glXGetContextGPUIDAMD (gloam_glx_context.GetContextGPUIDAMD)
#define glXCreateAssociatedContextAMD (gloam_glx_context.CreateAssociatedContextAMD)
#define glXCreateAssociatedContextAttribsAMD (gloam_glx_context.CreateAssociatedContextAttribsAMD)
#define glXDeleteAssociatedContextAMD (gloam_glx_context.DeleteAssociatedContextAMD)
#define glXMakeAssociatedContextCurrentAMD (gloam_glx_context.MakeAssociatedContextCurrentAMD)
#define glXGetCurrentAssociatedContextAMD (gloam_glx_context.GetCurrentAssociatedContextAMD)
#define glXBlitContextFramebufferAMD (gloam_glx_context.BlitContextFramebufferAMD)
#define glXCreateContextAttribsARB (gloam_glx_context.CreateContextAttribsARB)
#define glXGetProcAddressARB (gloam_glx_context.GetProcAddressARB)
#define glXGetCurrentDisplayEXT (gloam_glx_context.GetCurrentDisplayEXT)
#define glXQueryContextInfoEXT (gloam_glx_context.QueryContextInfoEXT)
#define glXGetContextIDEXT (gloam_glx_context.GetContextIDEXT)
#define glXImportContextEXT (gloam_glx_context.ImportContextEXT)
#define glXFreeContextEXT (gloam_glx_context.FreeContextEXT)
#define glXSwapIntervalEXT (gloam_glx_context.SwapIntervalEXT)
#define glXBindTexImageEXT (gloam_glx_context.BindTexImageEXT)
#define glXReleaseTexImageEXT (gloam_glx_context.ReleaseTexImageEXT)
#define glXGetAGPOffsetMESA (gloam_glx_context.GetAGPOffsetMESA)
#define glXCopySubBufferMESA (gloam_glx_context.CopySubBufferMESA)
#define glXCreateGLXPixmapMESA (gloam_glx_context.CreateGLXPixmapMESA)
#define glXQueryCurrentRendererIntegerMESA (gloam_glx_context.QueryCurrentRendererIntegerMESA)
#define glXQueryCurrentRendererStringMESA (gloam_glx_context.QueryCurrentRendererStringMESA)
#define glXQueryRendererIntegerMESA (gloam_glx_context.QueryRendererIntegerMESA)
#define glXQueryRendererStringMESA (gloam_glx_context.QueryRendererStringMESA)
#define glXReleaseBuffersMESA (gloam_glx_context.ReleaseBuffersMESA)
#define glXSet3DfxModeMESA (gloam_glx_context.Set3DfxModeMESA)
#define glXGetSwapIntervalMESA (gloam_glx_context.GetSwapIntervalMESA)
#define glXSwapIntervalMESA (gloam_glx_context.SwapIntervalMESA)
#define glXCopyBufferSubDataNV (gloam_glx_context.CopyBufferSubDataNV)
#define glXNamedCopyBufferSubDataNV (gloam_glx_context.NamedCopyBufferSubDataNV)
#define glXCopyImageSubDataNV (gloam_glx_context.CopyImageSubDataNV)
#define glXDelayBeforeSwapNV (gloam_glx_context.DelayBeforeSwapNV)
#define glXEnumerateVideoDevicesNV (gloam_glx_context.EnumerateVideoDevicesNV)
#define glXBindVideoDeviceNV (gloam_glx_context.BindVideoDeviceNV)
#define glXJoinSwapGroupNV (gloam_glx_context.JoinSwapGroupNV)
#define glXBindSwapBarrierNV (gloam_glx_context.BindSwapBarrierNV)
#define glXQuerySwapGroupNV (gloam_glx_context.QuerySwapGroupNV)
#define glXQueryMaxSwapGroupsNV (gloam_glx_context.QueryMaxSwapGroupsNV)
#define glXQueryFrameCountNV (gloam_glx_context.QueryFrameCountNV)
#define glXResetFrameCountNV (gloam_glx_context.ResetFrameCountNV)
#define glXBindVideoCaptureDeviceNV (gloam_glx_context.BindVideoCaptureDeviceNV)
#define glXEnumerateVideoCaptureDevicesNV (gloam_glx_context.EnumerateVideoCaptureDevicesNV)
#define glXLockVideoCaptureDeviceNV (gloam_glx_context.LockVideoCaptureDeviceNV)
#define glXQueryVideoCaptureDeviceNV (gloam_glx_context.QueryVideoCaptureDeviceNV)
#define glXReleaseVideoCaptureDeviceNV (gloam_glx_context.ReleaseVideoCaptureDeviceNV)
#define glXGetVideoDeviceNV (gloam_glx_context.GetVideoDeviceNV)
#define glXReleaseVideoDeviceNV (gloam_glx_context.ReleaseVideoDeviceNV)
#define glXBindVideoImageNV (gloam_glx_context.BindVideoImageNV)
#define glXReleaseVideoImageNV (gloam_glx_context.ReleaseVideoImageNV)
#define glXSendPbufferToVideoNV (gloam_glx_context.SendPbufferToVideoNV)
#define glXGetVideoInfoNV (gloam_glx_context.GetVideoInfoNV)
#define glXGetSyncValuesOML (gloam_glx_context.GetSyncValuesOML)
#define glXGetMscRateOML (gloam_glx_context.GetMscRateOML)
#define glXSwapBuffersMscOML (gloam_glx_context.SwapBuffersMscOML)
#define glXWaitForMscOML (gloam_glx_context.WaitForMscOML)
#define glXWaitForSbcOML (gloam_glx_context.WaitForSbcOML)
#define glXCushionSGI (gloam_glx_context.CushionSGI)
#define glXMakeCurrentReadSGI (gloam_glx_context.MakeCurrentReadSGI)
#define glXGetCurrentReadDrawableSGI (gloam_glx_context.GetCurrentReadDrawableSGI)
#define glXSwapIntervalSGI (gloam_glx_context.SwapIntervalSGI)
#define glXGetVideoSyncSGI (gloam_glx_context.GetVideoSyncSGI)
#define glXWaitVideoSyncSGI (gloam_glx_context.WaitVideoSyncSGI)
#define glXGetFBConfigAttribSGIX (gloam_glx_context.GetFBConfigAttribSGIX)
#define glXChooseFBConfigSGIX (gloam_glx_context.ChooseFBConfigSGIX)
#define glXCreateGLXPixmapWithConfigSGIX (gloam_glx_context.CreateGLXPixmapWithConfigSGIX)
#define glXCreateContextWithConfigSGIX (gloam_glx_context.CreateContextWithConfigSGIX)
#define glXGetVisualFromFBConfigSGIX (gloam_glx_context.GetVisualFromFBConfigSGIX)
#define glXGetFBConfigFromVisualSGIX (gloam_glx_context.GetFBConfigFromVisualSGIX)
#define glXQueryHyperpipeNetworkSGIX (gloam_glx_context.QueryHyperpipeNetworkSGIX)
#define glXHyperpipeConfigSGIX (gloam_glx_context.HyperpipeConfigSGIX)
#define glXQueryHyperpipeConfigSGIX (gloam_glx_context.QueryHyperpipeConfigSGIX)
#define glXDestroyHyperpipeConfigSGIX (gloam_glx_context.DestroyHyperpipeConfigSGIX)
#define glXBindHyperpipeSGIX (gloam_glx_context.BindHyperpipeSGIX)
#define glXQueryHyperpipeBestAttribSGIX (gloam_glx_context.QueryHyperpipeBestAttribSGIX)
#define glXHyperpipeAttribSGIX (gloam_glx_context.HyperpipeAttribSGIX)
#define glXQueryHyperpipeAttribSGIX (gloam_glx_context.QueryHyperpipeAttribSGIX)
#define glXCreateGLXPbufferSGIX (gloam_glx_context.CreateGLXPbufferSGIX)
#define glXDestroyGLXPbufferSGIX (gloam_glx_context.DestroyGLXPbufferSGIX)
#define glXQueryGLXPbufferSGIX (gloam_glx_context.QueryGLXPbufferSGIX)
#define glXSelectEventSGIX (gloam_glx_context.SelectEventSGIX)
#define glXGetSelectedEventSGIX (gloam_glx_context.GetSelectedEventSGIX)
#define glXBindSwapBarrierSGIX (gloam_glx_context.BindSwapBarrierSGIX)
#define glXQueryMaxSwapBarriersSGIX (gloam_glx_context.QueryMaxSwapBarriersSGIX)
#define glXJoinSwapGroupSGIX (gloam_glx_context.JoinSwapGroupSGIX)
#define glXBindChannelToWindowSGIX (gloam_glx_context.BindChannelToWindowSGIX)
#define glXChannelRectSGIX (gloam_glx_context.ChannelRectSGIX)
#define glXQueryChannelRectSGIX (gloam_glx_context.QueryChannelRectSGIX)
#define glXQueryChannelDeltasSGIX (gloam_glx_context.QueryChannelDeltasSGIX)
#define glXChannelRectSyncSGIX (gloam_glx_context.ChannelRectSyncSGIX)
#define glXGetTransparentIndexSUN (gloam_glx_context.GetTransparentIndexSUN)
#endif /* __INTELLISENSE__ */

/* ---- API declarations ---------------------------------------------------- */

/* Opaque function pointer type — the common return type for all load
   callbacks.  Callers cast to the specific PFN type they need. */
typedef void (*GloamAPIProc)(void);

/* Load function pointer type (GL / EGL / GLX / WGL). */
typedef GloamAPIProc (*GloamLoadFunc)(const char *name);
int gloamLoadGLXContext(GloamGLXContext *context, Display *display, int screen, GloamLoadFunc getProcAddr);
int gloamLoadGLX(Display *display, int screen, GloamLoadFunc getProcAddr);
/* Built-in loader: opens the platform library if needed and calls Load for you.
   Each Load function may be called multiple times (additive, same contract as
   the underlying gloamLoad* functions).  Pre-populate context->gloam_loader_handle
   to supply your own library handle; zero it before Unload to retain ownership. */
int  gloamLoaderLoadGLXContext(GloamGLXContext *context, Display *display, int screen);
int  gloamLoaderLoadGLX(Display *display, int screen);
void gloamLoaderUnloadGLXContext(GloamGLXContext *context);
void gloamLoaderUnloadGLX(void);
void gloamLoaderResetGLXContext(GloamGLXContext *context);
void gloamLoaderResetGLX(void);

#ifdef __cplusplus
}
#endif

#endif /* __linux */

#endif /* GLOAM_GLX_H */