/*
 * Generated by gloam 0.3.0. DO NOT EDIT.
 *
 *   gloam --extensions=all,-GL_EXT_direct_state_access,-GL_EXT_separate_shader_objects,-GL_EXT_vertex_shader,-GL_SUNX_constant_data,-GL_SUN_convolution_border_modes,-GL_SUN_global_alpha,-GL_SUN_mesh_array,-GL_SUN_slice_accum,-GL_SUN_triangle_list,-GL_SUN_vertex,-GL_SGIX_async,-GL_SGIX_async_histogram,-GL_SGIX_async_pixel,-GL_SGIX_blend_alpha_minmax,-GL_SGIX_calligraphic_fragment,-GL_SGIX_clipmap,-GL_SGIX_convolution_accuracy,-GL_SGIX_depth_pass_instrument,-GL_SGIX_depth_texture,-GL_SGIX_flush_raster,-GL_SGIX_fog_offset,-GL_SGIX_fragment_lighting,-GL_SGIX_framezoom,-GL_SGIX_igloo_interface,-GL_SGIX_instruments,-GL_SGIX_interlace,-GL_SGIX_ir_instrument1,-GL_SGIX_list_priority,-GL_SGIX_pixel_texture,-GL_SGIX_pixel_tiles,-GL_SGIX_polynomial_ffd,-GL_SGIX_reference_plane,-GL_SGIX_resample,-GL_SGIX_scalebias_hint,-GL_SGIX_shadow,-GL_SGIX_shadow_ambient,-GL_SGIX_sprite,-GL_SGIX_subsample,-GL_SGIX_tag_sample_buffer,-GL_SGIX_texture_add_env,-GL_SGIX_texture_coordinate_clamp,-GL_SGIX_texture_lod_bias,-GL_SGIX_texture_multi_buffer,-GL_SGIX_texture_scale_bias,-GL_SGIX_vertex_preclip,-GL_SGIX_ycrcb,-GL_SGIX_ycrcb_subsample,-GL_SGIX_ycrcba,-GL_NV_half_float,-GL_OES_byte_coordinates,-GL_ANGLE_robust_client_memory,-GL_ANGLE_shader_pixel_local_storage, --predecessors --promoted --api=gl:core,gles2,vulkan,egl,glx,wgl --baseline=gl:core=3.3,gles2=3.0 --out-path D:\dev\darwinia\contrib\gloam --merge c --alias --loader
 *
 * Extensions: all, 52 excluded explicitly (57 included)
 *   excluded explicitly: GL_ANGLE_robust_client_memory, GL_ANGLE_shader_pixel_local_storage, GL_EXT_direct_state_access, GL_EXT_separate_shader_objects, GL_EXT_vertex_shader, GL_NV_half_float, GL_OES_byte_coordinates, GL_SGIX_async, GL_SGIX_async_histogram, GL_SGIX_async_pixel, GL_SGIX_blend_alpha_minmax, GL_SGIX_calligraphic_fragment, GL_SGIX_clipmap, GL_SGIX_convolution_accuracy, GL_SGIX_depth_pass_instrument, GL_SGIX_depth_texture, GL_SGIX_flush_raster, GL_SGIX_fog_offset, GL_SGIX_fragment_lighting, GL_SGIX_framezoom, GL_SGIX_igloo_interface, GL_SGIX_instruments, GL_SGIX_interlace, GL_SGIX_ir_instrument1, GL_SGIX_list_priority, GL_SGIX_pixel_texture, GL_SGIX_pixel_tiles, GL_SGIX_polynomial_ffd, GL_SGIX_reference_plane, GL_SGIX_resample, GL_SGIX_scalebias_hint, GL_SGIX_shadow, GL_SGIX_shadow_ambient, GL_SGIX_sprite, GL_SGIX_subsample, GL_SGIX_tag_sample_buffer, GL_SGIX_texture_add_env, GL_SGIX_texture_coordinate_clamp, GL_SGIX_texture_lod_bias, GL_SGIX_texture_multi_buffer, GL_SGIX_texture_scale_bias, GL_SGIX_vertex_preclip, GL_SGIX_ycrcb, GL_SGIX_ycrcb_subsample, GL_SGIX_ycrcba, GL_SUNX_constant_data, GL_SUN_convolution_border_modes, GL_SUN_global_alpha, GL_SUN_mesh_array, GL_SUN_slice_accum, GL_SUN_triangle_list, GL_SUN_vertex
 *
 * Copyright (c) 2026 Steven Noonan
 * SPDX-License-Identifier: MIT
 *
 * Portions derived from Khronos Group XML API Registry specifications.
 * Copyright (c) 2013-2026 The Khronos Group Inc.
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef GLOAM_WGL_H
#define GLOAM_WGL_H

#ifdef __wgl_h_
  #error WGL (wgl.h) header already included (API: wgl), remove previous include!
#endif
#define __wgl_h_ 1

#ifdef _WIN32
#ifndef WIN32_LEAN_AND_MEAN
#define WIN32_LEAN_AND_MEAN
#endif
#include <windows.h>

#include <gloam/gl.h>
/* These are defined in wingdi.h and we're redefining them. */
#undef wglUseFontBitmaps
#undef wglUseFontOutlines

#include <stddef.h>
#include <stdint.h>


#ifdef __cplusplus
extern "C" {
#endif

/* Calling convention */
#ifndef APIENTRY
#  if defined(_WIN32)
#    define APIENTRY __stdcall
#  else
#    define APIENTRY
#  endif
#endif
#ifndef APIENTRYP
#  define APIENTRYP APIENTRY *
#endif
#ifndef GLAPI
#  define GLAPI extern
#endif

/* Calling convention for GL callback function pointers (e.g. debug callbacks,
   blob cache functions).  Piggybacks on APIENTRY if already defined so that
   code which defines APIENTRY before including this header gets consistent
   behaviour.  Guard against redefinition so multiple gloam headers included
   in the same translation unit don't conflict. */
#ifndef GLOAM_API_PTR
#  ifdef APIENTRY
#    define GLOAM_API_PTR APIENTRY
#  elif defined(_WIN32)
#    define GLOAM_API_PTR __stdcall
#  else
#    define GLOAM_API_PTR
#  endif
#endif
#ifndef GLAPIENTRY
#  define GLAPIENTRY GLOAM_API_PTR
#endif/* ---- Version feature guards ----------------------------------------------
   These mirror the upstream vulkan_core.h / gl.h definitions so that code
   guarded by e.g. #ifdef GL_VERSION_3_3 compiles correctly against this
   header. */
#define WGL_VERSION_1_0 1

/* ---- Extension compile-time guards ---------------------------------------
   These mirror the definitions in standard glext.h/gl2ext.h/eglext.h so
   that code guarded by e.g. #ifdef GL_ARB_draw_indirect compiles correctly
   against this header. */
#define WGL_3DFX_multisample 1
#define WGL_3DL_stereo_control 1
#define WGL_AMD_gpu_association 1
#define WGL_ARB_buffer_region 1
#define WGL_ARB_context_flush_control 1
#define WGL_ARB_create_context 1
#define WGL_ARB_create_context_no_error 1
#define WGL_ARB_create_context_profile 1
#define WGL_ARB_create_context_robustness 1
#define WGL_ARB_extensions_string 1
#define WGL_ARB_framebuffer_sRGB 1
#define WGL_ARB_make_current_read 1
#define WGL_ARB_multisample 1
#define WGL_ARB_pbuffer 1
#define WGL_ARB_pixel_format 1
#define WGL_ARB_pixel_format_float 1
#define WGL_ARB_render_texture 1
#define WGL_ARB_robustness_application_isolation 1
#define WGL_ARB_robustness_share_group_isolation 1
#define WGL_ATI_pixel_format_float 1
#define WGL_ATI_render_texture_rectangle 1
#define WGL_EXT_colorspace 1
#define WGL_EXT_create_context_es2_profile 1
#define WGL_EXT_create_context_es_profile 1
#define WGL_EXT_depth_float 1
#define WGL_EXT_display_color_table 1
#define WGL_EXT_extensions_string 1
#define WGL_EXT_framebuffer_sRGB 1
#define WGL_EXT_make_current_read 1
#define WGL_EXT_multisample 1
#define WGL_EXT_pbuffer 1
#define WGL_EXT_pixel_format 1
#define WGL_EXT_pixel_format_packed_float 1
#define WGL_EXT_swap_control 1
#define WGL_EXT_swap_control_tear 1
#define WGL_I3D_digital_video_control 1
#define WGL_I3D_gamma 1
#define WGL_I3D_genlock 1
#define WGL_I3D_image_buffer 1
#define WGL_I3D_swap_frame_lock 1
#define WGL_I3D_swap_frame_usage 1
#define WGL_NV_DX_interop 1
#define WGL_NV_DX_interop2 1
#define WGL_NV_copy_image 1
#define WGL_NV_delay_before_swap 1
#define WGL_NV_float_buffer 1
#define WGL_NV_gpu_affinity 1
#define WGL_NV_multigpu_context 1
#define WGL_NV_multisample_coverage 1
#define WGL_NV_present_video 1
#define WGL_NV_render_depth_texture 1
#define WGL_NV_render_texture_rectangle 1
#define WGL_NV_swap_group 1
#define WGL_NV_vertex_array_range 1
#define WGL_NV_video_capture 1
#define WGL_NV_video_output 1
#define WGL_OML_sync_control 1

/* ---- Constants ----------------------------------------------------------- */
#define WGL_SWAP_MAIN_PLANE 0x00000001
#define WGL_SWAP_OVERLAY1 0x00000002
#define WGL_SWAP_OVERLAY2 0x00000004
#define WGL_SWAP_OVERLAY3 0x00000008
#define WGL_SWAP_OVERLAY4 0x00000010
#define WGL_SWAP_OVERLAY5 0x00000020
#define WGL_SWAP_OVERLAY6 0x00000040
#define WGL_SWAP_OVERLAY7 0x00000080
#define WGL_SWAP_OVERLAY8 0x00000100
#define WGL_SWAP_OVERLAY9 0x00000200
#define WGL_SWAP_OVERLAY10 0x00000400
#define WGL_SWAP_OVERLAY11 0x00000800
#define WGL_SWAP_OVERLAY12 0x00001000
#define WGL_SWAP_OVERLAY13 0x00002000
#define WGL_SWAP_OVERLAY14 0x00004000
#define WGL_SWAP_OVERLAY15 0x00008000
#define WGL_SWAP_UNDERLAY1 0x00010000
#define WGL_SWAP_UNDERLAY2 0x00020000
#define WGL_SWAP_UNDERLAY3 0x00040000
#define WGL_SWAP_UNDERLAY4 0x00080000
#define WGL_SWAP_UNDERLAY5 0x00100000
#define WGL_SWAP_UNDERLAY6 0x00200000
#define WGL_SWAP_UNDERLAY7 0x00400000
#define WGL_SWAP_UNDERLAY8 0x00800000
#define WGL_SWAP_UNDERLAY9 0x01000000
#define WGL_SWAP_UNDERLAY10 0x02000000
#define WGL_SWAP_UNDERLAY11 0x04000000
#define WGL_SWAP_UNDERLAY12 0x08000000
#define WGL_SWAP_UNDERLAY13 0x10000000
#define WGL_SWAP_UNDERLAY14 0x20000000
#define WGL_SWAP_UNDERLAY15 0x40000000
#define WGL_FRONT_COLOR_BUFFER_BIT_ARB 0x00000001
#define WGL_BACK_COLOR_BUFFER_BIT_ARB 0x00000002
#define WGL_DEPTH_BUFFER_BIT_ARB 0x00000004
#define WGL_STENCIL_BUFFER_BIT_ARB 0x00000008
#define WGL_CONTEXT_DEBUG_BIT_ARB 0x00000001
#define WGL_CONTEXT_FORWARD_COMPATIBLE_BIT_ARB 0x00000002
#define WGL_CONTEXT_ROBUST_ACCESS_BIT_ARB 0x00000004
#define WGL_CONTEXT_RESET_ISOLATION_BIT_ARB 0x00000008
#define WGL_CONTEXT_CORE_PROFILE_BIT_ARB 0x00000001
#define WGL_CONTEXT_COMPATIBILITY_PROFILE_BIT_ARB 0x00000002
#define WGL_CONTEXT_ES_PROFILE_BIT_EXT 0x00000004
#define WGL_CONTEXT_ES2_PROFILE_BIT_EXT 0x00000004
#define WGL_IMAGE_BUFFER_MIN_ACCESS_I3D 0x00000001
#define WGL_IMAGE_BUFFER_LOCK_I3D 0x00000002
#define WGL_ACCESS_READ_ONLY_NV 0x00000000
#define WGL_ACCESS_READ_WRITE_NV 0x00000001
#define WGL_ACCESS_WRITE_DISCARD_NV 0x00000002
#define WGL_CONTEXT_RELEASE_BEHAVIOR_NONE_ARB 0
#define WGL_FONT_LINES 0
#define WGL_FONT_POLYGONS 1
#define WGL_GPU_VENDOR_AMD 0x1F00
#define WGL_GPU_RENDERER_STRING_AMD 0x1F01
#define WGL_GPU_OPENGL_VERSION_STRING_AMD 0x1F02
#define WGL_NUMBER_PIXEL_FORMATS_ARB 0x2000
#define WGL_NUMBER_PIXEL_FORMATS_EXT 0x2000
#define WGL_DRAW_TO_WINDOW_ARB 0x2001
#define WGL_DRAW_TO_WINDOW_EXT 0x2001
#define WGL_DRAW_TO_BITMAP_ARB 0x2002
#define WGL_DRAW_TO_BITMAP_EXT 0x2002
#define WGL_ACCELERATION_ARB 0x2003
#define WGL_ACCELERATION_EXT 0x2003
#define WGL_NEED_PALETTE_ARB 0x2004
#define WGL_NEED_PALETTE_EXT 0x2004
#define WGL_NEED_SYSTEM_PALETTE_ARB 0x2005
#define WGL_NEED_SYSTEM_PALETTE_EXT 0x2005
#define WGL_SWAP_LAYER_BUFFERS_ARB 0x2006
#define WGL_SWAP_LAYER_BUFFERS_EXT 0x2006
#define WGL_SWAP_METHOD_ARB 0x2007
#define WGL_SWAP_METHOD_EXT 0x2007
#define WGL_NUMBER_OVERLAYS_ARB 0x2008
#define WGL_NUMBER_OVERLAYS_EXT 0x2008
#define WGL_NUMBER_UNDERLAYS_ARB 0x2009
#define WGL_NUMBER_UNDERLAYS_EXT 0x2009
#define WGL_TRANSPARENT_ARB 0x200A
#define WGL_TRANSPARENT_EXT 0x200A
#define WGL_TRANSPARENT_VALUE_EXT 0x200B
#define WGL_SHARE_DEPTH_ARB 0x200C
#define WGL_SHARE_DEPTH_EXT 0x200C
#define WGL_SHARE_STENCIL_ARB 0x200D
#define WGL_SHARE_STENCIL_EXT 0x200D
#define WGL_SHARE_ACCUM_ARB 0x200E
#define WGL_SHARE_ACCUM_EXT 0x200E
#define WGL_SUPPORT_GDI_ARB 0x200F
#define WGL_SUPPORT_GDI_EXT 0x200F
#define WGL_SUPPORT_OPENGL_ARB 0x2010
#define WGL_SUPPORT_OPENGL_EXT 0x2010
#define WGL_DOUBLE_BUFFER_ARB 0x2011
#define WGL_DOUBLE_BUFFER_EXT 0x2011
#define WGL_STEREO_ARB 0x2012
#define WGL_STEREO_EXT 0x2012
#define WGL_PIXEL_TYPE_ARB 0x2013
#define WGL_PIXEL_TYPE_EXT 0x2013
#define WGL_COLOR_BITS_ARB 0x2014
#define WGL_COLOR_BITS_EXT 0x2014
#define WGL_RED_BITS_ARB 0x2015
#define WGL_RED_BITS_EXT 0x2015
#define WGL_RED_SHIFT_ARB 0x2016
#define WGL_RED_SHIFT_EXT 0x2016
#define WGL_GREEN_BITS_ARB 0x2017
#define WGL_GREEN_BITS_EXT 0x2017
#define WGL_GREEN_SHIFT_ARB 0x2018
#define WGL_GREEN_SHIFT_EXT 0x2018
#define WGL_BLUE_BITS_ARB 0x2019
#define WGL_BLUE_BITS_EXT 0x2019
#define WGL_BLUE_SHIFT_ARB 0x201A
#define WGL_BLUE_SHIFT_EXT 0x201A
#define WGL_ALPHA_BITS_ARB 0x201B
#define WGL_ALPHA_BITS_EXT 0x201B
#define WGL_ALPHA_SHIFT_ARB 0x201C
#define WGL_ALPHA_SHIFT_EXT 0x201C
#define WGL_ACCUM_BITS_ARB 0x201D
#define WGL_ACCUM_BITS_EXT 0x201D
#define WGL_ACCUM_RED_BITS_ARB 0x201E
#define WGL_ACCUM_RED_BITS_EXT 0x201E
#define WGL_ACCUM_GREEN_BITS_ARB 0x201F
#define WGL_ACCUM_GREEN_BITS_EXT 0x201F
#define WGL_ACCUM_BLUE_BITS_ARB 0x2020
#define WGL_ACCUM_BLUE_BITS_EXT 0x2020
#define WGL_ACCUM_ALPHA_BITS_ARB 0x2021
#define WGL_ACCUM_ALPHA_BITS_EXT 0x2021
#define WGL_DEPTH_BITS_ARB 0x2022
#define WGL_DEPTH_BITS_EXT 0x2022
#define WGL_STENCIL_BITS_ARB 0x2023
#define WGL_STENCIL_BITS_EXT 0x2023
#define WGL_AUX_BUFFERS_ARB 0x2024
#define WGL_AUX_BUFFERS_EXT 0x2024
#define WGL_NO_ACCELERATION_ARB 0x2025
#define WGL_NO_ACCELERATION_EXT 0x2025
#define WGL_GENERIC_ACCELERATION_ARB 0x2026
#define WGL_GENERIC_ACCELERATION_EXT 0x2026
#define WGL_FULL_ACCELERATION_ARB 0x2027
#define WGL_FULL_ACCELERATION_EXT 0x2027
#define WGL_SWAP_EXCHANGE_ARB 0x2028
#define WGL_SWAP_EXCHANGE_EXT 0x2028
#define WGL_SWAP_COPY_ARB 0x2029
#define WGL_SWAP_COPY_EXT 0x2029
#define WGL_SWAP_UNDEFINED_ARB 0x202A
#define WGL_SWAP_UNDEFINED_EXT 0x202A
#define WGL_TYPE_RGBA_ARB 0x202B
#define WGL_TYPE_RGBA_EXT 0x202B
#define WGL_TYPE_COLORINDEX_ARB 0x202C
#define WGL_TYPE_COLORINDEX_EXT 0x202C
#define WGL_DRAW_TO_PBUFFER_ARB 0x202D
#define WGL_DRAW_TO_PBUFFER_EXT 0x202D
#define WGL_MAX_PBUFFER_PIXELS_ARB 0x202E
#define WGL_MAX_PBUFFER_PIXELS_EXT 0x202E
#define WGL_MAX_PBUFFER_WIDTH_ARB 0x202F
#define WGL_MAX_PBUFFER_WIDTH_EXT 0x202F
#define WGL_MAX_PBUFFER_HEIGHT_ARB 0x2030
#define WGL_MAX_PBUFFER_HEIGHT_EXT 0x2030
#define WGL_OPTIMAL_PBUFFER_WIDTH_EXT 0x2031
#define WGL_OPTIMAL_PBUFFER_HEIGHT_EXT 0x2032
#define WGL_PBUFFER_LARGEST_ARB 0x2033
#define WGL_PBUFFER_LARGEST_EXT 0x2033
#define WGL_PBUFFER_WIDTH_ARB 0x2034
#define WGL_PBUFFER_WIDTH_EXT 0x2034
#define WGL_PBUFFER_HEIGHT_ARB 0x2035
#define WGL_PBUFFER_HEIGHT_EXT 0x2035
#define WGL_PBUFFER_LOST_ARB 0x2036
#define WGL_TRANSPARENT_RED_VALUE_ARB 0x2037
#define WGL_TRANSPARENT_GREEN_VALUE_ARB 0x2038
#define WGL_TRANSPARENT_BLUE_VALUE_ARB 0x2039
#define WGL_TRANSPARENT_ALPHA_VALUE_ARB 0x203A
#define WGL_TRANSPARENT_INDEX_VALUE_ARB 0x203B
#define WGL_DEPTH_FLOAT_EXT 0x2040
#define WGL_SAMPLE_BUFFERS_ARB 0x2041
#define WGL_SAMPLE_BUFFERS_EXT 0x2041
#define WGL_COVERAGE_SAMPLES_NV 0x2042
#define WGL_SAMPLES_ARB 0x2042
#define WGL_SAMPLES_EXT 0x2042
#define ERROR_INVALID_PIXEL_TYPE_ARB 0x2043
#define ERROR_INVALID_PIXEL_TYPE_EXT 0x2043
#define WGL_GENLOCK_SOURCE_MULTIVIEW_I3D 0x2044
#define WGL_GENLOCK_SOURCE_EXTERNAL_SYNC_I3D 0x2045
#define WGL_GENLOCK_SOURCE_EXTERNAL_FIELD_I3D 0x2046
#define WGL_GENLOCK_SOURCE_EXTERNAL_TTL_I3D 0x2047
#define WGL_GENLOCK_SOURCE_DIGITAL_SYNC_I3D 0x2048
#define WGL_GENLOCK_SOURCE_DIGITAL_FIELD_I3D 0x2049
#define WGL_GENLOCK_SOURCE_EDGE_FALLING_I3D 0x204A
#define WGL_GENLOCK_SOURCE_EDGE_RISING_I3D 0x204B
#define WGL_GENLOCK_SOURCE_EDGE_BOTH_I3D 0x204C
#define WGL_GAMMA_TABLE_SIZE_I3D 0x204E
#define WGL_GAMMA_EXCLUDE_DESKTOP_I3D 0x204F
#define WGL_DIGITAL_VIDEO_CURSOR_ALPHA_FRAMEBUFFER_I3D 0x2050
#define WGL_DIGITAL_VIDEO_CURSOR_ALPHA_VALUE_I3D 0x2051
#define WGL_DIGITAL_VIDEO_CURSOR_INCLUDED_I3D 0x2052
#define WGL_DIGITAL_VIDEO_GAMMA_CORRECTED_I3D 0x2053
#define ERROR_INCOMPATIBLE_DEVICE_CONTEXTS_ARB 0x2054
#define WGL_STEREO_EMITTER_ENABLE_3DL 0x2055
#define WGL_STEREO_EMITTER_DISABLE_3DL 0x2056
#define WGL_STEREO_POLARITY_NORMAL_3DL 0x2057
#define WGL_STEREO_POLARITY_INVERT_3DL 0x2058
#define WGL_SAMPLE_BUFFERS_3DFX 0x2060
#define WGL_SAMPLES_3DFX 0x2061
#define WGL_BIND_TO_TEXTURE_RGB_ARB 0x2070
#define WGL_BIND_TO_TEXTURE_RGBA_ARB 0x2071
#define WGL_TEXTURE_FORMAT_ARB 0x2072
#define WGL_TEXTURE_TARGET_ARB 0x2073
#define WGL_MIPMAP_TEXTURE_ARB 0x2074
#define WGL_TEXTURE_RGB_ARB 0x2075
#define WGL_TEXTURE_RGBA_ARB 0x2076
#define WGL_NO_TEXTURE_ARB 0x2077
#define WGL_TEXTURE_CUBE_MAP_ARB 0x2078
#define WGL_TEXTURE_1D_ARB 0x2079
#define WGL_TEXTURE_2D_ARB 0x207A
#define WGL_MIPMAP_LEVEL_ARB 0x207B
#define WGL_CUBE_MAP_FACE_ARB 0x207C
#define WGL_TEXTURE_CUBE_MAP_POSITIVE_X_ARB 0x207D
#define WGL_TEXTURE_CUBE_MAP_NEGATIVE_X_ARB 0x207E
#define WGL_TEXTURE_CUBE_MAP_POSITIVE_Y_ARB 0x207F
#define WGL_TEXTURE_CUBE_MAP_NEGATIVE_Y_ARB 0x2080
#define WGL_TEXTURE_CUBE_MAP_POSITIVE_Z_ARB 0x2081
#define WGL_TEXTURE_CUBE_MAP_NEGATIVE_Z_ARB 0x2082
#define WGL_FRONT_LEFT_ARB 0x2083
#define WGL_FRONT_RIGHT_ARB 0x2084
#define WGL_BACK_LEFT_ARB 0x2085
#define WGL_BACK_RIGHT_ARB 0x2086
#define WGL_AUX0_ARB 0x2087
#define WGL_AUX1_ARB 0x2088
#define WGL_AUX2_ARB 0x2089
#define WGL_AUX3_ARB 0x208A
#define WGL_AUX4_ARB 0x208B
#define WGL_AUX5_ARB 0x208C
#define WGL_AUX6_ARB 0x208D
#define WGL_AUX7_ARB 0x208E
#define WGL_AUX8_ARB 0x208F
#define WGL_AUX9_ARB 0x2090
#define WGL_CONTEXT_MAJOR_VERSION_ARB 0x2091
#define WGL_CONTEXT_MINOR_VERSION_ARB 0x2092
#define WGL_CONTEXT_LAYER_PLANE_ARB 0x2093
#define WGL_CONTEXT_FLAGS_ARB 0x2094
#define ERROR_INVALID_VERSION_ARB 0x2095
#define ERROR_INVALID_PROFILE_ARB 0x2096
#define WGL_CONTEXT_RELEASE_BEHAVIOR_ARB 0x2097
#define WGL_CONTEXT_RELEASE_BEHAVIOR_FLUSH_ARB 0x2098
#define WGL_BIND_TO_TEXTURE_RECTANGLE_RGB_NV 0x20A0
#define WGL_BIND_TO_TEXTURE_RECTANGLE_RGBA_NV 0x20A1
#define WGL_TEXTURE_RECTANGLE_NV 0x20A2
#define WGL_BIND_TO_TEXTURE_DEPTH_NV 0x20A3
#define WGL_BIND_TO_TEXTURE_RECTANGLE_DEPTH_NV 0x20A4
#define WGL_DEPTH_TEXTURE_FORMAT_NV 0x20A5
#define WGL_TEXTURE_DEPTH_COMPONENT_NV 0x20A6
#define WGL_DEPTH_COMPONENT_NV 0x20A7
#define WGL_TYPE_RGBA_UNSIGNED_FLOAT_EXT 0x20A8
#define WGL_FRAMEBUFFER_SRGB_CAPABLE_ARB 0x20A9
#define WGL_FRAMEBUFFER_SRGB_CAPABLE_EXT 0x20A9
#define WGL_CONTEXT_MULTIGPU_ATTRIB_NV 0x20AA
#define WGL_CONTEXT_MULTIGPU_ATTRIB_SINGLE_NV 0x20AB
#define WGL_CONTEXT_MULTIGPU_ATTRIB_AFR_NV 0x20AC
#define WGL_CONTEXT_MULTIGPU_ATTRIB_MULTICAST_NV 0x20AD
#define WGL_CONTEXT_MULTIGPU_ATTRIB_MULTI_DISPLAY_MULTICAST_NV 0x20AE
#define WGL_FLOAT_COMPONENTS_NV 0x20B0
#define WGL_BIND_TO_TEXTURE_RECTANGLE_FLOAT_R_NV 0x20B1
#define WGL_BIND_TO_TEXTURE_RECTANGLE_FLOAT_RG_NV 0x20B2
#define WGL_BIND_TO_TEXTURE_RECTANGLE_FLOAT_RGB_NV 0x20B3
#define WGL_BIND_TO_TEXTURE_RECTANGLE_FLOAT_RGBA_NV 0x20B4
#define WGL_TEXTURE_FLOAT_R_NV 0x20B5
#define WGL_TEXTURE_FLOAT_RG_NV 0x20B6
#define WGL_TEXTURE_FLOAT_RGB_NV 0x20B7
#define WGL_TEXTURE_FLOAT_RGBA_NV 0x20B8
#define WGL_COLOR_SAMPLES_NV 0x20B9
#define WGL_BIND_TO_VIDEO_RGB_NV 0x20C0
#define WGL_BIND_TO_VIDEO_RGBA_NV 0x20C1
#define WGL_BIND_TO_VIDEO_RGB_AND_DEPTH_NV 0x20C2
#define WGL_VIDEO_OUT_COLOR_NV 0x20C3
#define WGL_VIDEO_OUT_ALPHA_NV 0x20C4
#define WGL_VIDEO_OUT_DEPTH_NV 0x20C5
#define WGL_VIDEO_OUT_COLOR_AND_ALPHA_NV 0x20C6
#define WGL_VIDEO_OUT_COLOR_AND_DEPTH_NV 0x20C7
#define WGL_VIDEO_OUT_FRAME 0x20C8
#define WGL_VIDEO_OUT_FIELD_1 0x20C9
#define WGL_VIDEO_OUT_FIELD_2 0x20CA
#define WGL_VIDEO_OUT_STACKED_FIELDS_1_2 0x20CB
#define WGL_VIDEO_OUT_STACKED_FIELDS_2_1 0x20CC
#define WGL_UNIQUE_ID_NV 0x20CE
#define WGL_NUM_VIDEO_CAPTURE_SLOTS_NV 0x20CF
#define ERROR_INCOMPATIBLE_AFFINITY_MASKS_NV 0x20D0
#define ERROR_MISSING_AFFINITY_MASK_NV 0x20D1
#define WGL_NUM_VIDEO_SLOTS_NV 0x20F0
#define WGL_TYPE_RGBA_FLOAT_ARB 0x21A0
#define WGL_TYPE_RGBA_FLOAT_ATI 0x21A0
#define WGL_GPU_FASTEST_TARGET_GPUS_AMD 0x21A2
#define WGL_GPU_RAM_AMD 0x21A3
#define WGL_GPU_CLOCK_AMD 0x21A4
#define WGL_GPU_NUM_PIPES_AMD 0x21A5
#define WGL_TEXTURE_RECTANGLE_ATI 0x21A5 /* Duplicates unrelated WGL_GPU_NUM_PIPES_AMD */
#define WGL_GPU_NUM_SIMD_AMD 0x21A6
#define WGL_GPU_NUM_RB_AMD 0x21A7
#define WGL_GPU_NUM_SPI_AMD 0x21A8
#define WGL_COLORSPACE_EXT 0x309D
#define WGL_COLORSPACE_SRGB_EXT 0x3089
#define WGL_COLORSPACE_LINEAR_EXT 0x308A
#define WGL_CONTEXT_OPENGL_NO_ERROR_ARB 0x31B3
#define WGL_LOSE_CONTEXT_ON_RESET_ARB 0x8252
#define WGL_CONTEXT_RESET_NOTIFICATION_STRATEGY_ARB 0x8256
#define WGL_NO_RESET_NOTIFICATION_ARB 0x8261
#define WGL_CONTEXT_PROFILE_MASK_ARB 0x9126

/* ---- Types ----------------------------------------------------------------
   Emitted in topological dependency order.  Consecutive types sharing the
   same platform guard are coalesced into a single #ifdef/#endif block. */
DECLARE_HANDLE(HPBUFFERARB);

DECLARE_HANDLE(HPBUFFEREXT);

DECLARE_HANDLE(HVIDEOOUTPUTDEVICENV);

DECLARE_HANDLE(HPVIDEODEV);

DECLARE_HANDLE(HPGPUNV);

DECLARE_HANDLE(HGPUNV);

DECLARE_HANDLE(HVIDEOINPUTDEVICENV);

struct _GPU_DEVICE {
    DWORD  cb;
    CHAR   DeviceName[32];
    CHAR   DeviceString[128];
    DWORD  Flags;
    RECT   rcVirtualScreen;
};

typedef struct _GPU_DEVICE GPU_DEVICE;

typedef struct _GPU_DEVICE *PGPU_DEVICE;


/* ---- PFN typedefs -------------------------------------------------------- */
typedef int (APIENTRYP PFNWGLCHOOSEPIXELFORMATPROC)(HDC hDc, const PIXELFORMATDESCRIPTOR * pPfd);
typedef int (APIENTRYP PFNWGLDESCRIBEPIXELFORMATPROC)(HDC hdc, int ipfd, UINT cjpfd, PIXELFORMATDESCRIPTOR * ppfd);
typedef UINT (APIENTRYP PFNWGLGETENHMETAFILEPIXELFORMATPROC)(HENHMETAFILE hemf, UINT cbBuffer, PIXELFORMATDESCRIPTOR * ppfd);
typedef int (APIENTRYP PFNWGLGETPIXELFORMATPROC)(HDC hdc);
typedef BOOL (APIENTRYP PFNWGLSETPIXELFORMATPROC)(HDC hdc, int ipfd, const PIXELFORMATDESCRIPTOR * ppfd);
typedef BOOL (APIENTRYP PFNWGLSWAPBUFFERSPROC)(HDC hdc);
typedef BOOL (APIENTRYP PFNWGLCOPYCONTEXTPROC)(HGLRC hglrcSrc, HGLRC hglrcDst, UINT mask);
typedef HGLRC (APIENTRYP PFNWGLCREATECONTEXTPROC)(HDC hDc);
typedef HGLRC (APIENTRYP PFNWGLCREATELAYERCONTEXTPROC)(HDC hDc, int level);
typedef BOOL (APIENTRYP PFNWGLDELETECONTEXTPROC)(HGLRC oldContext);
typedef BOOL (APIENTRYP PFNWGLDESCRIBELAYERPLANEPROC)(HDC hDc, int pixelFormat, int layerPlane, UINT nBytes, LAYERPLANEDESCRIPTOR * plpd);
typedef HGLRC (APIENTRYP PFNWGLGETCURRENTCONTEXTPROC)(void);
typedef HDC (APIENTRYP PFNWGLGETCURRENTDCPROC)(void);
typedef int (APIENTRYP PFNWGLGETLAYERPALETTEENTRIESPROC)(HDC hdc, int iLayerPlane, int iStart, int cEntries, COLORREF * pcr);
typedef PROC (APIENTRYP PFNWGLGETPROCADDRESSPROC)(LPCSTR lpszProc);
typedef BOOL (APIENTRYP PFNWGLMAKECURRENTPROC)(HDC hDc, HGLRC newContext);
typedef BOOL (APIENTRYP PFNWGLREALIZELAYERPALETTEPROC)(HDC hdc, int iLayerPlane, BOOL bRealize);
typedef int (APIENTRYP PFNWGLSETLAYERPALETTEENTRIESPROC)(HDC hdc, int iLayerPlane, int iStart, int cEntries, const COLORREF * pcr);
typedef BOOL (APIENTRYP PFNWGLSHARELISTSPROC)(HGLRC hrcSrvShare, HGLRC hrcSrvSource);
typedef BOOL (APIENTRYP PFNWGLSWAPLAYERBUFFERSPROC)(HDC hdc, UINT fuFlags);
typedef BOOL (APIENTRYP PFNWGLUSEFONTBITMAPSPROC)(HDC hDC, DWORD first, DWORD count, DWORD listBase);
typedef BOOL (APIENTRYP PFNWGLUSEFONTBITMAPSAPROC)(HDC hDC, DWORD first, DWORD count, DWORD listBase);
typedef BOOL (APIENTRYP PFNWGLUSEFONTBITMAPSWPROC)(HDC hDC, DWORD first, DWORD count, DWORD listBase);
typedef BOOL (APIENTRYP PFNWGLUSEFONTOUTLINESPROC)(HDC hDC, DWORD first, DWORD count, DWORD listBase, FLOAT deviation, FLOAT extrusion, int format, LPGLYPHMETRICSFLOAT lpgmf);
typedef BOOL (APIENTRYP PFNWGLUSEFONTOUTLINESAPROC)(HDC hDC, DWORD first, DWORD count, DWORD listBase, FLOAT deviation, FLOAT extrusion, int format, LPGLYPHMETRICSFLOAT lpgmf);
typedef BOOL (APIENTRYP PFNWGLUSEFONTOUTLINESWPROC)(HDC hDC, DWORD first, DWORD count, DWORD listBase, FLOAT deviation, FLOAT extrusion, int format, LPGLYPHMETRICSFLOAT lpgmf);
typedef BOOL (APIENTRYP PFNWGLSETSTEREOEMITTERSTATE3DLPROC)(HDC hDC, UINT uState);
typedef VOID (APIENTRYP PFNWGLBLITCONTEXTFRAMEBUFFERAMDPROC)(HGLRC dstCtx, GLint srcX0, GLint srcY0, GLint srcX1, GLint srcY1, GLint dstX0, GLint dstY0, GLint dstX1, GLint dstY1, GLbitfield mask, GLenum filter);
typedef HGLRC (APIENTRYP PFNWGLCREATEASSOCIATEDCONTEXTAMDPROC)(UINT id);
typedef HGLRC (APIENTRYP PFNWGLCREATEASSOCIATEDCONTEXTATTRIBSAMDPROC)(UINT id, HGLRC hShareContext, const int * attribList);
typedef BOOL (APIENTRYP PFNWGLDELETEASSOCIATEDCONTEXTAMDPROC)(HGLRC hglrc);
typedef UINT (APIENTRYP PFNWGLGETCONTEXTGPUIDAMDPROC)(HGLRC hglrc);
typedef HGLRC (APIENTRYP PFNWGLGETCURRENTASSOCIATEDCONTEXTAMDPROC)(void);
typedef UINT (APIENTRYP PFNWGLGETGPUIDSAMDPROC)(UINT maxCount, UINT * ids);
typedef INT (APIENTRYP PFNWGLGETGPUINFOAMDPROC)(UINT id, INT property, GLenum dataType, UINT size, void * data);
typedef BOOL (APIENTRYP PFNWGLMAKEASSOCIATEDCONTEXTCURRENTAMDPROC)(HGLRC hglrc);
typedef HANDLE (APIENTRYP PFNWGLCREATEBUFFERREGIONARBPROC)(HDC hDC, int iLayerPlane, UINT uType);
typedef VOID (APIENTRYP PFNWGLDELETEBUFFERREGIONARBPROC)(HANDLE hRegion);
typedef BOOL (APIENTRYP PFNWGLRESTOREBUFFERREGIONARBPROC)(HANDLE hRegion, int x, int y, int width, int height, int xSrc, int ySrc);
typedef BOOL (APIENTRYP PFNWGLSAVEBUFFERREGIONARBPROC)(HANDLE hRegion, int x, int y, int width, int height);
typedef HGLRC (APIENTRYP PFNWGLCREATECONTEXTATTRIBSARBPROC)(HDC hDC, HGLRC hShareContext, const int * attribList);
typedef const char * (APIENTRYP PFNWGLGETEXTENSIONSSTRINGARBPROC)(HDC hdc);
typedef HDC (APIENTRYP PFNWGLGETCURRENTREADDCARBPROC)(void);
typedef BOOL (APIENTRYP PFNWGLMAKECONTEXTCURRENTARBPROC)(HDC hDrawDC, HDC hReadDC, HGLRC hglrc);
typedef HPBUFFERARB (APIENTRYP PFNWGLCREATEPBUFFERARBPROC)(HDC hDC, int iPixelFormat, int iWidth, int iHeight, const int * piAttribList);
typedef BOOL (APIENTRYP PFNWGLDESTROYPBUFFERARBPROC)(HPBUFFERARB hPbuffer);
typedef HDC (APIENTRYP PFNWGLGETPBUFFERDCARBPROC)(HPBUFFERARB hPbuffer);
typedef BOOL (APIENTRYP PFNWGLQUERYPBUFFERARBPROC)(HPBUFFERARB hPbuffer, int iAttribute, int * piValue);
typedef int (APIENTRYP PFNWGLRELEASEPBUFFERDCARBPROC)(HPBUFFERARB hPbuffer, HDC hDC);
typedef BOOL (APIENTRYP PFNWGLCHOOSEPIXELFORMATARBPROC)(HDC hdc, const int * piAttribIList, const FLOAT * pfAttribFList, UINT nMaxFormats, int * piFormats, UINT * nNumFormats);
typedef BOOL (APIENTRYP PFNWGLGETPIXELFORMATATTRIBFVARBPROC)(HDC hdc, int iPixelFormat, int iLayerPlane, UINT nAttributes, const int * piAttributes, FLOAT * pfValues);
typedef BOOL (APIENTRYP PFNWGLGETPIXELFORMATATTRIBIVARBPROC)(HDC hdc, int iPixelFormat, int iLayerPlane, UINT nAttributes, const int * piAttributes, int * piValues);
typedef BOOL (APIENTRYP PFNWGLBINDTEXIMAGEARBPROC)(HPBUFFERARB hPbuffer, int iBuffer);
typedef BOOL (APIENTRYP PFNWGLRELEASETEXIMAGEARBPROC)(HPBUFFERARB hPbuffer, int iBuffer);
typedef BOOL (APIENTRYP PFNWGLSETPBUFFERATTRIBARBPROC)(HPBUFFERARB hPbuffer, const int * piAttribList);
typedef GLboolean (APIENTRYP PFNWGLBINDDISPLAYCOLORTABLEEXTPROC)(GLushort id);
typedef GLboolean (APIENTRYP PFNWGLCREATEDISPLAYCOLORTABLEEXTPROC)(GLushort id);
typedef VOID (APIENTRYP PFNWGLDESTROYDISPLAYCOLORTABLEEXTPROC)(GLushort id);
typedef GLboolean (APIENTRYP PFNWGLLOADDISPLAYCOLORTABLEEXTPROC)(const GLushort * table, GLuint length);
typedef const char * (APIENTRYP PFNWGLGETEXTENSIONSSTRINGEXTPROC)(void);
typedef HDC (APIENTRYP PFNWGLGETCURRENTREADDCEXTPROC)(void);
typedef BOOL (APIENTRYP PFNWGLMAKECONTEXTCURRENTEXTPROC)(HDC hDrawDC, HDC hReadDC, HGLRC hglrc);
typedef HPBUFFEREXT (APIENTRYP PFNWGLCREATEPBUFFEREXTPROC)(HDC hDC, int iPixelFormat, int iWidth, int iHeight, const int * piAttribList);
typedef BOOL (APIENTRYP PFNWGLDESTROYPBUFFEREXTPROC)(HPBUFFEREXT hPbuffer);
typedef HDC (APIENTRYP PFNWGLGETPBUFFERDCEXTPROC)(HPBUFFEREXT hPbuffer);
typedef BOOL (APIENTRYP PFNWGLQUERYPBUFFEREXTPROC)(HPBUFFEREXT hPbuffer, int iAttribute, int * piValue);
typedef int (APIENTRYP PFNWGLRELEASEPBUFFERDCEXTPROC)(HPBUFFEREXT hPbuffer, HDC hDC);
typedef BOOL (APIENTRYP PFNWGLCHOOSEPIXELFORMATEXTPROC)(HDC hdc, const int * piAttribIList, const FLOAT * pfAttribFList, UINT nMaxFormats, int * piFormats, UINT * nNumFormats);
typedef BOOL (APIENTRYP PFNWGLGETPIXELFORMATATTRIBFVEXTPROC)(HDC hdc, int iPixelFormat, int iLayerPlane, UINT nAttributes, int * piAttributes, FLOAT * pfValues);
typedef BOOL (APIENTRYP PFNWGLGETPIXELFORMATATTRIBIVEXTPROC)(HDC hdc, int iPixelFormat, int iLayerPlane, UINT nAttributes, int * piAttributes, int * piValues);
typedef int (APIENTRYP PFNWGLGETSWAPINTERVALEXTPROC)(void);
typedef BOOL (APIENTRYP PFNWGLSWAPINTERVALEXTPROC)(int interval);
typedef BOOL (APIENTRYP PFNWGLGETDIGITALVIDEOPARAMETERSI3DPROC)(HDC hDC, int iAttribute, int * piValue);
typedef BOOL (APIENTRYP PFNWGLSETDIGITALVIDEOPARAMETERSI3DPROC)(HDC hDC, int iAttribute, const int * piValue);
typedef BOOL (APIENTRYP PFNWGLGETGAMMATABLEI3DPROC)(HDC hDC, int iEntries, USHORT * puRed, USHORT * puGreen, USHORT * puBlue);
typedef BOOL (APIENTRYP PFNWGLGETGAMMATABLEPARAMETERSI3DPROC)(HDC hDC, int iAttribute, int * piValue);
typedef BOOL (APIENTRYP PFNWGLSETGAMMATABLEI3DPROC)(HDC hDC, int iEntries, const USHORT * puRed, const USHORT * puGreen, const USHORT * puBlue);
typedef BOOL (APIENTRYP PFNWGLSETGAMMATABLEPARAMETERSI3DPROC)(HDC hDC, int iAttribute, const int * piValue);
typedef BOOL (APIENTRYP PFNWGLDISABLEGENLOCKI3DPROC)(HDC hDC);
typedef BOOL (APIENTRYP PFNWGLENABLEGENLOCKI3DPROC)(HDC hDC);
typedef BOOL (APIENTRYP PFNWGLGENLOCKSAMPLERATEI3DPROC)(HDC hDC, UINT uRate);
typedef BOOL (APIENTRYP PFNWGLGENLOCKSOURCEDELAYI3DPROC)(HDC hDC, UINT uDelay);
typedef BOOL (APIENTRYP PFNWGLGENLOCKSOURCEEDGEI3DPROC)(HDC hDC, UINT uEdge);
typedef BOOL (APIENTRYP PFNWGLGENLOCKSOURCEI3DPROC)(HDC hDC, UINT uSource);
typedef BOOL (APIENTRYP PFNWGLGETGENLOCKSAMPLERATEI3DPROC)(HDC hDC, UINT * uRate);
typedef BOOL (APIENTRYP PFNWGLGETGENLOCKSOURCEDELAYI3DPROC)(HDC hDC, UINT * uDelay);
typedef BOOL (APIENTRYP PFNWGLGETGENLOCKSOURCEEDGEI3DPROC)(HDC hDC, UINT * uEdge);
typedef BOOL (APIENTRYP PFNWGLGETGENLOCKSOURCEI3DPROC)(HDC hDC, UINT * uSource);
typedef BOOL (APIENTRYP PFNWGLISENABLEDGENLOCKI3DPROC)(HDC hDC, BOOL * pFlag);
typedef BOOL (APIENTRYP PFNWGLQUERYGENLOCKMAXSOURCEDELAYI3DPROC)(HDC hDC, UINT * uMaxLineDelay, UINT * uMaxPixelDelay);
typedef BOOL (APIENTRYP PFNWGLASSOCIATEIMAGEBUFFEREVENTSI3DPROC)(HDC hDC, const HANDLE * pEvent, const LPVOID * pAddress, const DWORD * pSize, UINT count);
typedef LPVOID (APIENTRYP PFNWGLCREATEIMAGEBUFFERI3DPROC)(HDC hDC, DWORD dwSize, UINT uFlags);
typedef BOOL (APIENTRYP PFNWGLDESTROYIMAGEBUFFERI3DPROC)(HDC hDC, LPVOID pAddress);
typedef BOOL (APIENTRYP PFNWGLRELEASEIMAGEBUFFEREVENTSI3DPROC)(HDC hDC, const LPVOID * pAddress, UINT count);
typedef BOOL (APIENTRYP PFNWGLDISABLEFRAMELOCKI3DPROC)(void);
typedef BOOL (APIENTRYP PFNWGLENABLEFRAMELOCKI3DPROC)(void);
typedef BOOL (APIENTRYP PFNWGLISENABLEDFRAMELOCKI3DPROC)(BOOL * pFlag);
typedef BOOL (APIENTRYP PFNWGLQUERYFRAMELOCKMASTERI3DPROC)(BOOL * pFlag);
typedef BOOL (APIENTRYP PFNWGLBEGINFRAMETRACKINGI3DPROC)(void);
typedef BOOL (APIENTRYP PFNWGLENDFRAMETRACKINGI3DPROC)(void);
typedef BOOL (APIENTRYP PFNWGLGETFRAMEUSAGEI3DPROC)(float * pUsage);
typedef BOOL (APIENTRYP PFNWGLQUERYFRAMETRACKINGI3DPROC)(DWORD * pFrameCount, DWORD * pMissedFrames, float * pLastMissedUsage);
typedef BOOL (APIENTRYP PFNWGLCOPYIMAGESUBDATANVPROC)(HGLRC hSrcRC, GLuint srcName, GLenum srcTarget, GLint srcLevel, GLint srcX, GLint srcY, GLint srcZ, HGLRC hDstRC, GLuint dstName, GLenum dstTarget, GLint dstLevel, GLint dstX, GLint dstY, GLint dstZ, GLsizei width, GLsizei height, GLsizei depth);
typedef BOOL (APIENTRYP PFNWGLDELAYBEFORESWAPNVPROC)(HDC hDC, GLfloat seconds);
typedef BOOL (APIENTRYP PFNWGLDXCLOSEDEVICENVPROC)(HANDLE hDevice);
typedef BOOL (APIENTRYP PFNWGLDXLOCKOBJECTSNVPROC)(HANDLE hDevice, GLint count, HANDLE * hObjects);
typedef BOOL (APIENTRYP PFNWGLDXOBJECTACCESSNVPROC)(HANDLE hObject, GLenum access);
typedef HANDLE (APIENTRYP PFNWGLDXOPENDEVICENVPROC)(void * dxDevice);
typedef HANDLE (APIENTRYP PFNWGLDXREGISTEROBJECTNVPROC)(HANDLE hDevice, void * dxObject, GLuint name, GLenum type, GLenum access);
typedef BOOL (APIENTRYP PFNWGLDXSETRESOURCESHAREHANDLENVPROC)(void * dxObject, HANDLE shareHandle);
typedef BOOL (APIENTRYP PFNWGLDXUNLOCKOBJECTSNVPROC)(HANDLE hDevice, GLint count, HANDLE * hObjects);
typedef BOOL (APIENTRYP PFNWGLDXUNREGISTEROBJECTNVPROC)(HANDLE hDevice, HANDLE hObject);
typedef HDC (APIENTRYP PFNWGLCREATEAFFINITYDCNVPROC)(const HGPUNV * phGpuList);
typedef BOOL (APIENTRYP PFNWGLDELETEDCNVPROC)(HDC hdc);
typedef BOOL (APIENTRYP PFNWGLENUMGPUDEVICESNVPROC)(HGPUNV hGpu, UINT iDeviceIndex, PGPU_DEVICE lpGpuDevice);
typedef BOOL (APIENTRYP PFNWGLENUMGPUSFROMAFFINITYDCNVPROC)(HDC hAffinityDC, UINT iGpuIndex, HGPUNV * hGpu);
typedef BOOL (APIENTRYP PFNWGLENUMGPUSNVPROC)(UINT iGpuIndex, HGPUNV * phGpu);
typedef BOOL (APIENTRYP PFNWGLBINDVIDEODEVICENVPROC)(HDC hDc, unsigned int uVideoSlot, HVIDEOOUTPUTDEVICENV hVideoDevice, const int * piAttribList);
typedef int (APIENTRYP PFNWGLENUMERATEVIDEODEVICESNVPROC)(HDC hDc, HVIDEOOUTPUTDEVICENV * phDeviceList);
typedef BOOL (APIENTRYP PFNWGLQUERYCURRENTCONTEXTNVPROC)(int iAttribute, int * piValue);
typedef BOOL (APIENTRYP PFNWGLBINDSWAPBARRIERNVPROC)(GLuint group, GLuint barrier);
typedef BOOL (APIENTRYP PFNWGLJOINSWAPGROUPNVPROC)(HDC hDC, GLuint group);
typedef BOOL (APIENTRYP PFNWGLQUERYFRAMECOUNTNVPROC)(HDC hDC, GLuint * count);
typedef BOOL (APIENTRYP PFNWGLQUERYMAXSWAPGROUPSNVPROC)(HDC hDC, GLuint * maxGroups, GLuint * maxBarriers);
typedef BOOL (APIENTRYP PFNWGLQUERYSWAPGROUPNVPROC)(HDC hDC, GLuint * group, GLuint * barrier);
typedef BOOL (APIENTRYP PFNWGLRESETFRAMECOUNTNVPROC)(HDC hDC);
typedef BOOL (APIENTRYP PFNWGLBINDVIDEOCAPTUREDEVICENVPROC)(UINT uVideoSlot, HVIDEOINPUTDEVICENV hDevice);
typedef UINT (APIENTRYP PFNWGLENUMERATEVIDEOCAPTUREDEVICESNVPROC)(HDC hDc, HVIDEOINPUTDEVICENV * phDeviceList);
typedef BOOL (APIENTRYP PFNWGLLOCKVIDEOCAPTUREDEVICENVPROC)(HDC hDc, HVIDEOINPUTDEVICENV hDevice);
typedef BOOL (APIENTRYP PFNWGLQUERYVIDEOCAPTUREDEVICENVPROC)(HDC hDc, HVIDEOINPUTDEVICENV hDevice, int iAttribute, int * piValue);
typedef BOOL (APIENTRYP PFNWGLRELEASEVIDEOCAPTUREDEVICENVPROC)(HDC hDc, HVIDEOINPUTDEVICENV hDevice);
typedef BOOL (APIENTRYP PFNWGLBINDVIDEOIMAGENVPROC)(HPVIDEODEV hVideoDevice, HPBUFFERARB hPbuffer, int iVideoBuffer);
typedef BOOL (APIENTRYP PFNWGLGETVIDEODEVICENVPROC)(HDC hDC, int numDevices, HPVIDEODEV * hVideoDevice);
typedef BOOL (APIENTRYP PFNWGLGETVIDEOINFONVPROC)(HPVIDEODEV hpVideoDevice, unsigned long * pulCounterOutputPbuffer, unsigned long * pulCounterOutputVideo);
typedef BOOL (APIENTRYP PFNWGLRELEASEVIDEODEVICENVPROC)(HPVIDEODEV hVideoDevice);
typedef BOOL (APIENTRYP PFNWGLRELEASEVIDEOIMAGENVPROC)(HPBUFFERARB hPbuffer, int iVideoBuffer);
typedef BOOL (APIENTRYP PFNWGLSENDPBUFFERTOVIDEONVPROC)(HPBUFFERARB hPbuffer, int iBufferType, unsigned long * pulCounterPbuffer, BOOL bBlock);
typedef void * (APIENTRYP PFNWGLALLOCATEMEMORYNVPROC)(GLsizei size, GLfloat readfreq, GLfloat writefreq, GLfloat priority);
typedef void (APIENTRYP PFNWGLFREEMEMORYNVPROC)(void * pointer);
typedef BOOL (APIENTRYP PFNWGLGETMSCRATEOMLPROC)(HDC hdc, INT32 * numerator, INT32 * denominator);
typedef BOOL (APIENTRYP PFNWGLGETSYNCVALUESOMLPROC)(HDC hdc, INT64 * ust, INT64 * msc, INT64 * sbc);
typedef INT64 (APIENTRYP PFNWGLSWAPBUFFERSMSCOMLPROC)(HDC hdc, INT64 target_msc, INT64 divisor, INT64 remainder);
typedef INT64 (APIENTRYP PFNWGLSWAPLAYERBUFFERSMSCOMLPROC)(HDC hdc, INT fuPlanes, INT64 target_msc, INT64 divisor, INT64 remainder);
typedef BOOL (APIENTRYP PFNWGLWAITFORMSCOMLPROC)(HDC hdc, INT64 target_msc, INT64 divisor, INT64 remainder, INT64 * ust, INT64 * msc, INT64 * sbc);
typedef BOOL (APIENTRYP PFNWGLWAITFORSBCOMLPROC)(HDC hdc, INT64 target_sbc, INT64 * ust, INT64 * msc, INT64 * sbc);


/* ---- Context struct ------------------------------------------------------
   Three anonymous unions give both indexed (array) and named (struct member)
   access to the same memory, at zero runtime cost.

   featArray / extArray: unsigned char flags, one per feature / extension.
   pfnArray: function pointer slots, one per command.

   Anonymous structs inside the unions are a C11 / GCC extension; they are
   universally supported on our target compilers. */
typedef struct GloamWGLContext {
    union {
        unsigned char featArray[1];
        struct {
        /*    0 */ unsigned char VERSION_1_0;
        };
    };

    union {
        unsigned char extArray[57];
        struct {
        /*    0 */ unsigned char _3DFX_multisample;
        /*    1 */ unsigned char _3DL_stereo_control;
        /*    2 */ unsigned char AMD_gpu_association;
        /*    3 */ unsigned char ARB_buffer_region;
        /*    4 */ unsigned char ARB_context_flush_control;
        /*    5 */ unsigned char ARB_create_context;
        /*    6 */ unsigned char ARB_create_context_no_error;
        /*    7 */ unsigned char ARB_create_context_profile;
        /*    8 */ unsigned char ARB_create_context_robustness;
        /*    9 */ unsigned char ARB_extensions_string;
        /*   10 */ unsigned char ARB_framebuffer_sRGB;
        /*   11 */ unsigned char ARB_make_current_read;
        /*   12 */ unsigned char ARB_multisample;
        /*   13 */ unsigned char ARB_pbuffer;
        /*   14 */ unsigned char ARB_pixel_format;
        /*   15 */ unsigned char ARB_pixel_format_float;
        /*   16 */ unsigned char ARB_render_texture;
        /*   17 */ unsigned char ARB_robustness_application_isolation;
        /*   18 */ unsigned char ARB_robustness_share_group_isolation;
        /*   19 */ unsigned char ATI_pixel_format_float;
        /*   20 */ unsigned char ATI_render_texture_rectangle;
        /*   21 */ unsigned char EXT_colorspace;
        /*   22 */ unsigned char EXT_create_context_es2_profile;
        /*   23 */ unsigned char EXT_create_context_es_profile;
        /*   24 */ unsigned char EXT_depth_float;
        /*   25 */ unsigned char EXT_display_color_table;
        /*   26 */ unsigned char EXT_extensions_string;
        /*   27 */ unsigned char EXT_framebuffer_sRGB;
        /*   28 */ unsigned char EXT_make_current_read;
        /*   29 */ unsigned char EXT_multisample;
        /*   30 */ unsigned char EXT_pbuffer;
        /*   31 */ unsigned char EXT_pixel_format;
        /*   32 */ unsigned char EXT_pixel_format_packed_float;
        /*   33 */ unsigned char EXT_swap_control;
        /*   34 */ unsigned char EXT_swap_control_tear;
        /*   35 */ unsigned char I3D_digital_video_control;
        /*   36 */ unsigned char I3D_gamma;
        /*   37 */ unsigned char I3D_genlock;
        /*   38 */ unsigned char I3D_image_buffer;
        /*   39 */ unsigned char I3D_swap_frame_lock;
        /*   40 */ unsigned char I3D_swap_frame_usage;
        /*   41 */ unsigned char NV_DX_interop;
        /*   42 */ unsigned char NV_DX_interop2;
        /*   43 */ unsigned char NV_copy_image;
        /*   44 */ unsigned char NV_delay_before_swap;
        /*   45 */ unsigned char NV_float_buffer;
        /*   46 */ unsigned char NV_gpu_affinity;
        /*   47 */ unsigned char NV_multigpu_context;
        /*   48 */ unsigned char NV_multisample_coverage;
        /*   49 */ unsigned char NV_present_video;
        /*   50 */ unsigned char NV_render_depth_texture;
        /*   51 */ unsigned char NV_render_texture_rectangle;
        /*   52 */ unsigned char NV_swap_group;
        /*   53 */ unsigned char NV_vertex_array_range;
        /*   54 */ unsigned char NV_video_capture;
        /*   55 */ unsigned char NV_video_output;
        /*   56 */ unsigned char OML_sync_control;
        };
    };

    union {
        void *pfnArray[145];
        struct {
        /*    0 */ PFNWGLCHOOSEPIXELFORMATPROC ChoosePixelFormat;
        /*    1 */ PFNWGLDESCRIBEPIXELFORMATPROC DescribePixelFormat;
        /*    2 */ PFNWGLGETENHMETAFILEPIXELFORMATPROC GetEnhMetaFilePixelFormat;
        /*    3 */ PFNWGLGETPIXELFORMATPROC GetPixelFormat;
        /*    4 */ PFNWGLSETPIXELFORMATPROC SetPixelFormat;
        /*    5 */ PFNWGLSWAPBUFFERSPROC SwapBuffers;
        /*    6 */ PFNWGLCOPYCONTEXTPROC CopyContext;
        /*    7 */ PFNWGLCREATECONTEXTPROC CreateContext;
        /*    8 */ PFNWGLCREATELAYERCONTEXTPROC CreateLayerContext;
        /*    9 */ PFNWGLDELETECONTEXTPROC DeleteContext;
        /*   10 */ PFNWGLDESCRIBELAYERPLANEPROC DescribeLayerPlane;
        /*   11 */ PFNWGLGETCURRENTCONTEXTPROC GetCurrentContext;
        /*   12 */ PFNWGLGETCURRENTDCPROC GetCurrentDC;
        /*   13 */ PFNWGLGETLAYERPALETTEENTRIESPROC GetLayerPaletteEntries;
        /*   14 */ PFNWGLGETPROCADDRESSPROC GetProcAddress;
        /*   15 */ PFNWGLMAKECURRENTPROC MakeCurrent;
        /*   16 */ PFNWGLREALIZELAYERPALETTEPROC RealizeLayerPalette;
        /*   17 */ PFNWGLSETLAYERPALETTEENTRIESPROC SetLayerPaletteEntries;
        /*   18 */ PFNWGLSHARELISTSPROC ShareLists;
        /*   19 */ PFNWGLSWAPLAYERBUFFERSPROC SwapLayerBuffers;
        /*   20 */ PFNWGLUSEFONTBITMAPSPROC UseFontBitmaps;
        /*   21 */ PFNWGLUSEFONTBITMAPSAPROC UseFontBitmapsA;
        /*   22 */ PFNWGLUSEFONTBITMAPSWPROC UseFontBitmapsW;
        /*   23 */ PFNWGLUSEFONTOUTLINESPROC UseFontOutlines;
        /*   24 */ PFNWGLUSEFONTOUTLINESAPROC UseFontOutlinesA;
        /*   25 */ PFNWGLUSEFONTOUTLINESWPROC UseFontOutlinesW;
        /*   26 */ PFNWGLSETSTEREOEMITTERSTATE3DLPROC SetStereoEmitterState3DL;
        /*   27 */ PFNWGLBLITCONTEXTFRAMEBUFFERAMDPROC BlitContextFramebufferAMD;
        /*   28 */ PFNWGLCREATEASSOCIATEDCONTEXTAMDPROC CreateAssociatedContextAMD;
        /*   29 */ PFNWGLCREATEASSOCIATEDCONTEXTATTRIBSAMDPROC CreateAssociatedContextAttribsAMD;
        /*   30 */ PFNWGLDELETEASSOCIATEDCONTEXTAMDPROC DeleteAssociatedContextAMD;
        /*   31 */ PFNWGLGETCONTEXTGPUIDAMDPROC GetContextGPUIDAMD;
        /*   32 */ PFNWGLGETCURRENTASSOCIATEDCONTEXTAMDPROC GetCurrentAssociatedContextAMD;
        /*   33 */ PFNWGLGETGPUIDSAMDPROC GetGPUIDsAMD;
        /*   34 */ PFNWGLGETGPUINFOAMDPROC GetGPUInfoAMD;
        /*   35 */ PFNWGLMAKEASSOCIATEDCONTEXTCURRENTAMDPROC MakeAssociatedContextCurrentAMD;
        /*   36 */ PFNWGLCREATEBUFFERREGIONARBPROC CreateBufferRegionARB;
        /*   37 */ PFNWGLDELETEBUFFERREGIONARBPROC DeleteBufferRegionARB;
        /*   38 */ PFNWGLRESTOREBUFFERREGIONARBPROC RestoreBufferRegionARB;
        /*   39 */ PFNWGLSAVEBUFFERREGIONARBPROC SaveBufferRegionARB;
        /*   40 */ PFNWGLCREATECONTEXTATTRIBSARBPROC CreateContextAttribsARB;
        /*   41 */ PFNWGLGETEXTENSIONSSTRINGARBPROC GetExtensionsStringARB;
        /*   42 */ PFNWGLGETCURRENTREADDCARBPROC GetCurrentReadDCARB;
        /*   43 */ PFNWGLMAKECONTEXTCURRENTARBPROC MakeContextCurrentARB;
        /*   44 */ PFNWGLCREATEPBUFFERARBPROC CreatePbufferARB;
        /*   45 */ PFNWGLDESTROYPBUFFERARBPROC DestroyPbufferARB;
        /*   46 */ PFNWGLGETPBUFFERDCARBPROC GetPbufferDCARB;
        /*   47 */ PFNWGLQUERYPBUFFERARBPROC QueryPbufferARB;
        /*   48 */ PFNWGLRELEASEPBUFFERDCARBPROC ReleasePbufferDCARB;
        /*   49 */ PFNWGLCHOOSEPIXELFORMATARBPROC ChoosePixelFormatARB;
        /*   50 */ PFNWGLGETPIXELFORMATATTRIBFVARBPROC GetPixelFormatAttribfvARB;
        /*   51 */ PFNWGLGETPIXELFORMATATTRIBIVARBPROC GetPixelFormatAttribivARB;
        /*   52 */ PFNWGLBINDTEXIMAGEARBPROC BindTexImageARB;
        /*   53 */ PFNWGLRELEASETEXIMAGEARBPROC ReleaseTexImageARB;
        /*   54 */ PFNWGLSETPBUFFERATTRIBARBPROC SetPbufferAttribARB;
        /*   55 */ PFNWGLBINDDISPLAYCOLORTABLEEXTPROC BindDisplayColorTableEXT;
        /*   56 */ PFNWGLCREATEDISPLAYCOLORTABLEEXTPROC CreateDisplayColorTableEXT;
        /*   57 */ PFNWGLDESTROYDISPLAYCOLORTABLEEXTPROC DestroyDisplayColorTableEXT;
        /*   58 */ PFNWGLLOADDISPLAYCOLORTABLEEXTPROC LoadDisplayColorTableEXT;
        /*   59 */ PFNWGLGETEXTENSIONSSTRINGEXTPROC GetExtensionsStringEXT;
        /*   60 */ PFNWGLGETCURRENTREADDCEXTPROC GetCurrentReadDCEXT;
        /*   61 */ PFNWGLMAKECONTEXTCURRENTEXTPROC MakeContextCurrentEXT;
        /*   62 */ PFNWGLCREATEPBUFFEREXTPROC CreatePbufferEXT;
        /*   63 */ PFNWGLDESTROYPBUFFEREXTPROC DestroyPbufferEXT;
        /*   64 */ PFNWGLGETPBUFFERDCEXTPROC GetPbufferDCEXT;
        /*   65 */ PFNWGLQUERYPBUFFEREXTPROC QueryPbufferEXT;
        /*   66 */ PFNWGLRELEASEPBUFFERDCEXTPROC ReleasePbufferDCEXT;
        /*   67 */ PFNWGLCHOOSEPIXELFORMATEXTPROC ChoosePixelFormatEXT;
        /*   68 */ PFNWGLGETPIXELFORMATATTRIBFVEXTPROC GetPixelFormatAttribfvEXT;
        /*   69 */ PFNWGLGETPIXELFORMATATTRIBIVEXTPROC GetPixelFormatAttribivEXT;
        /*   70 */ PFNWGLGETSWAPINTERVALEXTPROC GetSwapIntervalEXT;
        /*   71 */ PFNWGLSWAPINTERVALEXTPROC SwapIntervalEXT;
        /*   72 */ PFNWGLGETDIGITALVIDEOPARAMETERSI3DPROC GetDigitalVideoParametersI3D;
        /*   73 */ PFNWGLSETDIGITALVIDEOPARAMETERSI3DPROC SetDigitalVideoParametersI3D;
        /*   74 */ PFNWGLGETGAMMATABLEI3DPROC GetGammaTableI3D;
        /*   75 */ PFNWGLGETGAMMATABLEPARAMETERSI3DPROC GetGammaTableParametersI3D;
        /*   76 */ PFNWGLSETGAMMATABLEI3DPROC SetGammaTableI3D;
        /*   77 */ PFNWGLSETGAMMATABLEPARAMETERSI3DPROC SetGammaTableParametersI3D;
        /*   78 */ PFNWGLDISABLEGENLOCKI3DPROC DisableGenlockI3D;
        /*   79 */ PFNWGLENABLEGENLOCKI3DPROC EnableGenlockI3D;
        /*   80 */ PFNWGLGENLOCKSAMPLERATEI3DPROC GenlockSampleRateI3D;
        /*   81 */ PFNWGLGENLOCKSOURCEDELAYI3DPROC GenlockSourceDelayI3D;
        /*   82 */ PFNWGLGENLOCKSOURCEEDGEI3DPROC GenlockSourceEdgeI3D;
        /*   83 */ PFNWGLGENLOCKSOURCEI3DPROC GenlockSourceI3D;
        /*   84 */ PFNWGLGETGENLOCKSAMPLERATEI3DPROC GetGenlockSampleRateI3D;
        /*   85 */ PFNWGLGETGENLOCKSOURCEDELAYI3DPROC GetGenlockSourceDelayI3D;
        /*   86 */ PFNWGLGETGENLOCKSOURCEEDGEI3DPROC GetGenlockSourceEdgeI3D;
        /*   87 */ PFNWGLGETGENLOCKSOURCEI3DPROC GetGenlockSourceI3D;
        /*   88 */ PFNWGLISENABLEDGENLOCKI3DPROC IsEnabledGenlockI3D;
        /*   89 */ PFNWGLQUERYGENLOCKMAXSOURCEDELAYI3DPROC QueryGenlockMaxSourceDelayI3D;
        /*   90 */ PFNWGLASSOCIATEIMAGEBUFFEREVENTSI3DPROC AssociateImageBufferEventsI3D;
        /*   91 */ PFNWGLCREATEIMAGEBUFFERI3DPROC CreateImageBufferI3D;
        /*   92 */ PFNWGLDESTROYIMAGEBUFFERI3DPROC DestroyImageBufferI3D;
        /*   93 */ PFNWGLRELEASEIMAGEBUFFEREVENTSI3DPROC ReleaseImageBufferEventsI3D;
        /*   94 */ PFNWGLDISABLEFRAMELOCKI3DPROC DisableFrameLockI3D;
        /*   95 */ PFNWGLENABLEFRAMELOCKI3DPROC EnableFrameLockI3D;
        /*   96 */ PFNWGLISENABLEDFRAMELOCKI3DPROC IsEnabledFrameLockI3D;
        /*   97 */ PFNWGLQUERYFRAMELOCKMASTERI3DPROC QueryFrameLockMasterI3D;
        /*   98 */ PFNWGLBEGINFRAMETRACKINGI3DPROC BeginFrameTrackingI3D;
        /*   99 */ PFNWGLENDFRAMETRACKINGI3DPROC EndFrameTrackingI3D;
        /*  100 */ PFNWGLGETFRAMEUSAGEI3DPROC GetFrameUsageI3D;
        /*  101 */ PFNWGLQUERYFRAMETRACKINGI3DPROC QueryFrameTrackingI3D;
        /*  102 */ PFNWGLCOPYIMAGESUBDATANVPROC CopyImageSubDataNV;
        /*  103 */ PFNWGLDELAYBEFORESWAPNVPROC DelayBeforeSwapNV;
        /*  104 */ PFNWGLDXCLOSEDEVICENVPROC DXCloseDeviceNV;
        /*  105 */ PFNWGLDXLOCKOBJECTSNVPROC DXLockObjectsNV;
        /*  106 */ PFNWGLDXOBJECTACCESSNVPROC DXObjectAccessNV;
        /*  107 */ PFNWGLDXOPENDEVICENVPROC DXOpenDeviceNV;
        /*  108 */ PFNWGLDXREGISTEROBJECTNVPROC DXRegisterObjectNV;
        /*  109 */ PFNWGLDXSETRESOURCESHAREHANDLENVPROC DXSetResourceShareHandleNV;
        /*  110 */ PFNWGLDXUNLOCKOBJECTSNVPROC DXUnlockObjectsNV;
        /*  111 */ PFNWGLDXUNREGISTEROBJECTNVPROC DXUnregisterObjectNV;
        /*  112 */ PFNWGLCREATEAFFINITYDCNVPROC CreateAffinityDCNV;
        /*  113 */ PFNWGLDELETEDCNVPROC DeleteDCNV;
        /*  114 */ PFNWGLENUMGPUDEVICESNVPROC EnumGpuDevicesNV;
        /*  115 */ PFNWGLENUMGPUSFROMAFFINITYDCNVPROC EnumGpusFromAffinityDCNV;
        /*  116 */ PFNWGLENUMGPUSNVPROC EnumGpusNV;
        /*  117 */ PFNWGLBINDVIDEODEVICENVPROC BindVideoDeviceNV;
        /*  118 */ PFNWGLENUMERATEVIDEODEVICESNVPROC EnumerateVideoDevicesNV;
        /*  119 */ PFNWGLQUERYCURRENTCONTEXTNVPROC QueryCurrentContextNV;
        /*  120 */ PFNWGLBINDSWAPBARRIERNVPROC BindSwapBarrierNV;
        /*  121 */ PFNWGLJOINSWAPGROUPNVPROC JoinSwapGroupNV;
        /*  122 */ PFNWGLQUERYFRAMECOUNTNVPROC QueryFrameCountNV;
        /*  123 */ PFNWGLQUERYMAXSWAPGROUPSNVPROC QueryMaxSwapGroupsNV;
        /*  124 */ PFNWGLQUERYSWAPGROUPNVPROC QuerySwapGroupNV;
        /*  125 */ PFNWGLRESETFRAMECOUNTNVPROC ResetFrameCountNV;
        /*  126 */ PFNWGLBINDVIDEOCAPTUREDEVICENVPROC BindVideoCaptureDeviceNV;
        /*  127 */ PFNWGLENUMERATEVIDEOCAPTUREDEVICESNVPROC EnumerateVideoCaptureDevicesNV;
        /*  128 */ PFNWGLLOCKVIDEOCAPTUREDEVICENVPROC LockVideoCaptureDeviceNV;
        /*  129 */ PFNWGLQUERYVIDEOCAPTUREDEVICENVPROC QueryVideoCaptureDeviceNV;
        /*  130 */ PFNWGLRELEASEVIDEOCAPTUREDEVICENVPROC ReleaseVideoCaptureDeviceNV;
        /*  131 */ PFNWGLBINDVIDEOIMAGENVPROC BindVideoImageNV;
        /*  132 */ PFNWGLGETVIDEODEVICENVPROC GetVideoDeviceNV;
        /*  133 */ PFNWGLGETVIDEOINFONVPROC GetVideoInfoNV;
        /*  134 */ PFNWGLRELEASEVIDEODEVICENVPROC ReleaseVideoDeviceNV;
        /*  135 */ PFNWGLRELEASEVIDEOIMAGENVPROC ReleaseVideoImageNV;
        /*  136 */ PFNWGLSENDPBUFFERTOVIDEONVPROC SendPbufferToVideoNV;
        /*  137 */ PFNWGLALLOCATEMEMORYNVPROC AllocateMemoryNV;
        /*  138 */ PFNWGLFREEMEMORYNVPROC FreeMemoryNV;
        /*  139 */ PFNWGLGETMSCRATEOMLPROC GetMscRateOML;
        /*  140 */ PFNWGLGETSYNCVALUESOMLPROC GetSyncValuesOML;
        /*  141 */ PFNWGLSWAPBUFFERSMSCOMLPROC SwapBuffersMscOML;
        /*  142 */ PFNWGLSWAPLAYERBUFFERSMSCOMLPROC SwapLayerBuffersMscOML;
        /*  143 */ PFNWGLWAITFORMSCOMLPROC WaitForMscOML;
        /*  144 */ PFNWGLWAITFORSBCOMLPROC WaitForSbcOML;
        };
    };
    /* Built-in loader library handle.  Set by gloamLoaderLoad*Context when it
       opens the platform library.  Pre-populate before calling that function
       to supply your own handle (dlopen is then skipped); zero it before
       calling gloamLoaderUnload*Context to prevent it closing a handle you
       still own.  Present on all context types so user code can use a single
       field name regardless of API. */
    void *gloam_loader_handle;


} GloamWGLContext;

/* Global context instance — a value, not a pointer, so the compiler knows
   its address is fixed and does not re-load it on every access. */
extern GloamWGLContext gloam_wgl_context;

/* ---- Feature presence macros --------------------------------------------
   Test whether a versioned feature was detected at load time. */
#define GLOAM_WGL_VERSION_1_0 (gloam_wgl_context.VERSION_1_0)

/* ---- Extension presence macros ------------------------------------------ */
#define GLOAM_WGL_3DFX_multisample (gloam_wgl_context._3DFX_multisample)
#define GLOAM_WGL_3DL_stereo_control (gloam_wgl_context._3DL_stereo_control)
#define GLOAM_WGL_AMD_gpu_association (gloam_wgl_context.AMD_gpu_association)
#define GLOAM_WGL_ARB_buffer_region (gloam_wgl_context.ARB_buffer_region)
#define GLOAM_WGL_ARB_context_flush_control (gloam_wgl_context.ARB_context_flush_control)
#define GLOAM_WGL_ARB_create_context (gloam_wgl_context.ARB_create_context)
#define GLOAM_WGL_ARB_create_context_no_error (gloam_wgl_context.ARB_create_context_no_error)
#define GLOAM_WGL_ARB_create_context_profile (gloam_wgl_context.ARB_create_context_profile)
#define GLOAM_WGL_ARB_create_context_robustness (gloam_wgl_context.ARB_create_context_robustness)
#define GLOAM_WGL_ARB_extensions_string (gloam_wgl_context.ARB_extensions_string)
#define GLOAM_WGL_ARB_framebuffer_sRGB (gloam_wgl_context.ARB_framebuffer_sRGB)
#define GLOAM_WGL_ARB_make_current_read (gloam_wgl_context.ARB_make_current_read)
#define GLOAM_WGL_ARB_multisample (gloam_wgl_context.ARB_multisample)
#define GLOAM_WGL_ARB_pbuffer (gloam_wgl_context.ARB_pbuffer)
#define GLOAM_WGL_ARB_pixel_format (gloam_wgl_context.ARB_pixel_format)
#define GLOAM_WGL_ARB_pixel_format_float (gloam_wgl_context.ARB_pixel_format_float)
#define GLOAM_WGL_ARB_render_texture (gloam_wgl_context.ARB_render_texture)
#define GLOAM_WGL_ARB_robustness_application_isolation (gloam_wgl_context.ARB_robustness_application_isolation)
#define GLOAM_WGL_ARB_robustness_share_group_isolation (gloam_wgl_context.ARB_robustness_share_group_isolation)
#define GLOAM_WGL_ATI_pixel_format_float (gloam_wgl_context.ATI_pixel_format_float)
#define GLOAM_WGL_ATI_render_texture_rectangle (gloam_wgl_context.ATI_render_texture_rectangle)
#define GLOAM_WGL_EXT_colorspace (gloam_wgl_context.EXT_colorspace)
#define GLOAM_WGL_EXT_create_context_es2_profile (gloam_wgl_context.EXT_create_context_es2_profile)
#define GLOAM_WGL_EXT_create_context_es_profile (gloam_wgl_context.EXT_create_context_es_profile)
#define GLOAM_WGL_EXT_depth_float (gloam_wgl_context.EXT_depth_float)
#define GLOAM_WGL_EXT_display_color_table (gloam_wgl_context.EXT_display_color_table)
#define GLOAM_WGL_EXT_extensions_string (gloam_wgl_context.EXT_extensions_string)
#define GLOAM_WGL_EXT_framebuffer_sRGB (gloam_wgl_context.EXT_framebuffer_sRGB)
#define GLOAM_WGL_EXT_make_current_read (gloam_wgl_context.EXT_make_current_read)
#define GLOAM_WGL_EXT_multisample (gloam_wgl_context.EXT_multisample)
#define GLOAM_WGL_EXT_pbuffer (gloam_wgl_context.EXT_pbuffer)
#define GLOAM_WGL_EXT_pixel_format (gloam_wgl_context.EXT_pixel_format)
#define GLOAM_WGL_EXT_pixel_format_packed_float (gloam_wgl_context.EXT_pixel_format_packed_float)
#define GLOAM_WGL_EXT_swap_control (gloam_wgl_context.EXT_swap_control)
#define GLOAM_WGL_EXT_swap_control_tear (gloam_wgl_context.EXT_swap_control_tear)
#define GLOAM_WGL_I3D_digital_video_control (gloam_wgl_context.I3D_digital_video_control)
#define GLOAM_WGL_I3D_gamma (gloam_wgl_context.I3D_gamma)
#define GLOAM_WGL_I3D_genlock (gloam_wgl_context.I3D_genlock)
#define GLOAM_WGL_I3D_image_buffer (gloam_wgl_context.I3D_image_buffer)
#define GLOAM_WGL_I3D_swap_frame_lock (gloam_wgl_context.I3D_swap_frame_lock)
#define GLOAM_WGL_I3D_swap_frame_usage (gloam_wgl_context.I3D_swap_frame_usage)
#define GLOAM_WGL_NV_DX_interop (gloam_wgl_context.NV_DX_interop)
#define GLOAM_WGL_NV_DX_interop2 (gloam_wgl_context.NV_DX_interop2)
#define GLOAM_WGL_NV_copy_image (gloam_wgl_context.NV_copy_image)
#define GLOAM_WGL_NV_delay_before_swap (gloam_wgl_context.NV_delay_before_swap)
#define GLOAM_WGL_NV_float_buffer (gloam_wgl_context.NV_float_buffer)
#define GLOAM_WGL_NV_gpu_affinity (gloam_wgl_context.NV_gpu_affinity)
#define GLOAM_WGL_NV_multigpu_context (gloam_wgl_context.NV_multigpu_context)
#define GLOAM_WGL_NV_multisample_coverage (gloam_wgl_context.NV_multisample_coverage)
#define GLOAM_WGL_NV_present_video (gloam_wgl_context.NV_present_video)
#define GLOAM_WGL_NV_render_depth_texture (gloam_wgl_context.NV_render_depth_texture)
#define GLOAM_WGL_NV_render_texture_rectangle (gloam_wgl_context.NV_render_texture_rectangle)
#define GLOAM_WGL_NV_swap_group (gloam_wgl_context.NV_swap_group)
#define GLOAM_WGL_NV_vertex_array_range (gloam_wgl_context.NV_vertex_array_range)
#define GLOAM_WGL_NV_video_capture (gloam_wgl_context.NV_video_capture)
#define GLOAM_WGL_NV_video_output (gloam_wgl_context.NV_video_output)
#define GLOAM_WGL_OML_sync_control (gloam_wgl_context.OML_sync_control)


/* ---- Dispatch macros and IntelliSense prototypes -------------------------
   Under __INTELLISENSE__ we expose real function declarations so IDEs can
   provide parameter info and type checking.  In normal compilation the macros
   dispatch directly through the global context struct. */
#ifdef __INTELLISENSE__
int ChoosePixelFormat(HDC hDc, const PIXELFORMATDESCRIPTOR * pPfd);
int DescribePixelFormat(HDC hdc, int ipfd, UINT cjpfd, PIXELFORMATDESCRIPTOR * ppfd);
UINT GetEnhMetaFilePixelFormat(HENHMETAFILE hemf, UINT cbBuffer, PIXELFORMATDESCRIPTOR * ppfd);
int GetPixelFormat(HDC hdc);
BOOL SetPixelFormat(HDC hdc, int ipfd, const PIXELFORMATDESCRIPTOR * ppfd);
BOOL SwapBuffers(HDC hdc);
BOOL wglCopyContext(HGLRC hglrcSrc, HGLRC hglrcDst, UINT mask);
HGLRC wglCreateContext(HDC hDc);
HGLRC wglCreateLayerContext(HDC hDc, int level);
BOOL wglDeleteContext(HGLRC oldContext);
BOOL wglDescribeLayerPlane(HDC hDc, int pixelFormat, int layerPlane, UINT nBytes, LAYERPLANEDESCRIPTOR * plpd);
HGLRC wglGetCurrentContext(void);
HDC wglGetCurrentDC(void);
int wglGetLayerPaletteEntries(HDC hdc, int iLayerPlane, int iStart, int cEntries, COLORREF * pcr);
PROC wglGetProcAddress(LPCSTR lpszProc);
BOOL wglMakeCurrent(HDC hDc, HGLRC newContext);
BOOL wglRealizeLayerPalette(HDC hdc, int iLayerPlane, BOOL bRealize);
int wglSetLayerPaletteEntries(HDC hdc, int iLayerPlane, int iStart, int cEntries, const COLORREF * pcr);
BOOL wglShareLists(HGLRC hrcSrvShare, HGLRC hrcSrvSource);
BOOL wglSwapLayerBuffers(HDC hdc, UINT fuFlags);
BOOL wglUseFontBitmaps(HDC hDC, DWORD first, DWORD count, DWORD listBase);
BOOL wglUseFontBitmapsA(HDC hDC, DWORD first, DWORD count, DWORD listBase);
BOOL wglUseFontBitmapsW(HDC hDC, DWORD first, DWORD count, DWORD listBase);
BOOL wglUseFontOutlines(HDC hDC, DWORD first, DWORD count, DWORD listBase, FLOAT deviation, FLOAT extrusion, int format, LPGLYPHMETRICSFLOAT lpgmf);
BOOL wglUseFontOutlinesA(HDC hDC, DWORD first, DWORD count, DWORD listBase, FLOAT deviation, FLOAT extrusion, int format, LPGLYPHMETRICSFLOAT lpgmf);
BOOL wglUseFontOutlinesW(HDC hDC, DWORD first, DWORD count, DWORD listBase, FLOAT deviation, FLOAT extrusion, int format, LPGLYPHMETRICSFLOAT lpgmf);
BOOL wglSetStereoEmitterState3DL(HDC hDC, UINT uState);
VOID wglBlitContextFramebufferAMD(HGLRC dstCtx, GLint srcX0, GLint srcY0, GLint srcX1, GLint srcY1, GLint dstX0, GLint dstY0, GLint dstX1, GLint dstY1, GLbitfield mask, GLenum filter);
HGLRC wglCreateAssociatedContextAMD(UINT id);
HGLRC wglCreateAssociatedContextAttribsAMD(UINT id, HGLRC hShareContext, const int * attribList);
BOOL wglDeleteAssociatedContextAMD(HGLRC hglrc);
UINT wglGetContextGPUIDAMD(HGLRC hglrc);
HGLRC wglGetCurrentAssociatedContextAMD(void);
UINT wglGetGPUIDsAMD(UINT maxCount, UINT * ids);
INT wglGetGPUInfoAMD(UINT id, INT property, GLenum dataType, UINT size, void * data);
BOOL wglMakeAssociatedContextCurrentAMD(HGLRC hglrc);
HANDLE wglCreateBufferRegionARB(HDC hDC, int iLayerPlane, UINT uType);
VOID wglDeleteBufferRegionARB(HANDLE hRegion);
BOOL wglRestoreBufferRegionARB(HANDLE hRegion, int x, int y, int width, int height, int xSrc, int ySrc);
BOOL wglSaveBufferRegionARB(HANDLE hRegion, int x, int y, int width, int height);
HGLRC wglCreateContextAttribsARB(HDC hDC, HGLRC hShareContext, const int * attribList);
const char * wglGetExtensionsStringARB(HDC hdc);
HDC wglGetCurrentReadDCARB(void);
BOOL wglMakeContextCurrentARB(HDC hDrawDC, HDC hReadDC, HGLRC hglrc);
HPBUFFERARB wglCreatePbufferARB(HDC hDC, int iPixelFormat, int iWidth, int iHeight, const int * piAttribList);
BOOL wglDestroyPbufferARB(HPBUFFERARB hPbuffer);
HDC wglGetPbufferDCARB(HPBUFFERARB hPbuffer);
BOOL wglQueryPbufferARB(HPBUFFERARB hPbuffer, int iAttribute, int * piValue);
int wglReleasePbufferDCARB(HPBUFFERARB hPbuffer, HDC hDC);
BOOL wglChoosePixelFormatARB(HDC hdc, const int * piAttribIList, const FLOAT * pfAttribFList, UINT nMaxFormats, int * piFormats, UINT * nNumFormats);
BOOL wglGetPixelFormatAttribfvARB(HDC hdc, int iPixelFormat, int iLayerPlane, UINT nAttributes, const int * piAttributes, FLOAT * pfValues);
BOOL wglGetPixelFormatAttribivARB(HDC hdc, int iPixelFormat, int iLayerPlane, UINT nAttributes, const int * piAttributes, int * piValues);
BOOL wglBindTexImageARB(HPBUFFERARB hPbuffer, int iBuffer);
BOOL wglReleaseTexImageARB(HPBUFFERARB hPbuffer, int iBuffer);
BOOL wglSetPbufferAttribARB(HPBUFFERARB hPbuffer, const int * piAttribList);
GLboolean wglBindDisplayColorTableEXT(GLushort id);
GLboolean wglCreateDisplayColorTableEXT(GLushort id);
VOID wglDestroyDisplayColorTableEXT(GLushort id);
GLboolean wglLoadDisplayColorTableEXT(const GLushort * table, GLuint length);
const char * wglGetExtensionsStringEXT(void);
HDC wglGetCurrentReadDCEXT(void);
BOOL wglMakeContextCurrentEXT(HDC hDrawDC, HDC hReadDC, HGLRC hglrc);
HPBUFFEREXT wglCreatePbufferEXT(HDC hDC, int iPixelFormat, int iWidth, int iHeight, const int * piAttribList);
BOOL wglDestroyPbufferEXT(HPBUFFEREXT hPbuffer);
HDC wglGetPbufferDCEXT(HPBUFFEREXT hPbuffer);
BOOL wglQueryPbufferEXT(HPBUFFEREXT hPbuffer, int iAttribute, int * piValue);
int wglReleasePbufferDCEXT(HPBUFFEREXT hPbuffer, HDC hDC);
BOOL wglChoosePixelFormatEXT(HDC hdc, const int * piAttribIList, const FLOAT * pfAttribFList, UINT nMaxFormats, int * piFormats, UINT * nNumFormats);
BOOL wglGetPixelFormatAttribfvEXT(HDC hdc, int iPixelFormat, int iLayerPlane, UINT nAttributes, int * piAttributes, FLOAT * pfValues);
BOOL wglGetPixelFormatAttribivEXT(HDC hdc, int iPixelFormat, int iLayerPlane, UINT nAttributes, int * piAttributes, int * piValues);
int wglGetSwapIntervalEXT(void);
BOOL wglSwapIntervalEXT(int interval);
BOOL wglGetDigitalVideoParametersI3D(HDC hDC, int iAttribute, int * piValue);
BOOL wglSetDigitalVideoParametersI3D(HDC hDC, int iAttribute, const int * piValue);
BOOL wglGetGammaTableI3D(HDC hDC, int iEntries, USHORT * puRed, USHORT * puGreen, USHORT * puBlue);
BOOL wglGetGammaTableParametersI3D(HDC hDC, int iAttribute, int * piValue);
BOOL wglSetGammaTableI3D(HDC hDC, int iEntries, const USHORT * puRed, const USHORT * puGreen, const USHORT * puBlue);
BOOL wglSetGammaTableParametersI3D(HDC hDC, int iAttribute, const int * piValue);
BOOL wglDisableGenlockI3D(HDC hDC);
BOOL wglEnableGenlockI3D(HDC hDC);
BOOL wglGenlockSampleRateI3D(HDC hDC, UINT uRate);
BOOL wglGenlockSourceDelayI3D(HDC hDC, UINT uDelay);
BOOL wglGenlockSourceEdgeI3D(HDC hDC, UINT uEdge);
BOOL wglGenlockSourceI3D(HDC hDC, UINT uSource);
BOOL wglGetGenlockSampleRateI3D(HDC hDC, UINT * uRate);
BOOL wglGetGenlockSourceDelayI3D(HDC hDC, UINT * uDelay);
BOOL wglGetGenlockSourceEdgeI3D(HDC hDC, UINT * uEdge);
BOOL wglGetGenlockSourceI3D(HDC hDC, UINT * uSource);
BOOL wglIsEnabledGenlockI3D(HDC hDC, BOOL * pFlag);
BOOL wglQueryGenlockMaxSourceDelayI3D(HDC hDC, UINT * uMaxLineDelay, UINT * uMaxPixelDelay);
BOOL wglAssociateImageBufferEventsI3D(HDC hDC, const HANDLE * pEvent, const LPVOID * pAddress, const DWORD * pSize, UINT count);
LPVOID wglCreateImageBufferI3D(HDC hDC, DWORD dwSize, UINT uFlags);
BOOL wglDestroyImageBufferI3D(HDC hDC, LPVOID pAddress);
BOOL wglReleaseImageBufferEventsI3D(HDC hDC, const LPVOID * pAddress, UINT count);
BOOL wglDisableFrameLockI3D(void);
BOOL wglEnableFrameLockI3D(void);
BOOL wglIsEnabledFrameLockI3D(BOOL * pFlag);
BOOL wglQueryFrameLockMasterI3D(BOOL * pFlag);
BOOL wglBeginFrameTrackingI3D(void);
BOOL wglEndFrameTrackingI3D(void);
BOOL wglGetFrameUsageI3D(float * pUsage);
BOOL wglQueryFrameTrackingI3D(DWORD * pFrameCount, DWORD * pMissedFrames, float * pLastMissedUsage);
BOOL wglCopyImageSubDataNV(HGLRC hSrcRC, GLuint srcName, GLenum srcTarget, GLint srcLevel, GLint srcX, GLint srcY, GLint srcZ, HGLRC hDstRC, GLuint dstName, GLenum dstTarget, GLint dstLevel, GLint dstX, GLint dstY, GLint dstZ, GLsizei width, GLsizei height, GLsizei depth);
BOOL wglDelayBeforeSwapNV(HDC hDC, GLfloat seconds);
BOOL wglDXCloseDeviceNV(HANDLE hDevice);
BOOL wglDXLockObjectsNV(HANDLE hDevice, GLint count, HANDLE * hObjects);
BOOL wglDXObjectAccessNV(HANDLE hObject, GLenum access);
HANDLE wglDXOpenDeviceNV(void * dxDevice);
HANDLE wglDXRegisterObjectNV(HANDLE hDevice, void * dxObject, GLuint name, GLenum type, GLenum access);
BOOL wglDXSetResourceShareHandleNV(void * dxObject, HANDLE shareHandle);
BOOL wglDXUnlockObjectsNV(HANDLE hDevice, GLint count, HANDLE * hObjects);
BOOL wglDXUnregisterObjectNV(HANDLE hDevice, HANDLE hObject);
HDC wglCreateAffinityDCNV(const HGPUNV * phGpuList);
BOOL wglDeleteDCNV(HDC hdc);
BOOL wglEnumGpuDevicesNV(HGPUNV hGpu, UINT iDeviceIndex, PGPU_DEVICE lpGpuDevice);
BOOL wglEnumGpusFromAffinityDCNV(HDC hAffinityDC, UINT iGpuIndex, HGPUNV * hGpu);
BOOL wglEnumGpusNV(UINT iGpuIndex, HGPUNV * phGpu);
BOOL wglBindVideoDeviceNV(HDC hDc, unsigned int uVideoSlot, HVIDEOOUTPUTDEVICENV hVideoDevice, const int * piAttribList);
int wglEnumerateVideoDevicesNV(HDC hDc, HVIDEOOUTPUTDEVICENV * phDeviceList);
BOOL wglQueryCurrentContextNV(int iAttribute, int * piValue);
BOOL wglBindSwapBarrierNV(GLuint group, GLuint barrier);
BOOL wglJoinSwapGroupNV(HDC hDC, GLuint group);
BOOL wglQueryFrameCountNV(HDC hDC, GLuint * count);
BOOL wglQueryMaxSwapGroupsNV(HDC hDC, GLuint * maxGroups, GLuint * maxBarriers);
BOOL wglQuerySwapGroupNV(HDC hDC, GLuint * group, GLuint * barrier);
BOOL wglResetFrameCountNV(HDC hDC);
BOOL wglBindVideoCaptureDeviceNV(UINT uVideoSlot, HVIDEOINPUTDEVICENV hDevice);
UINT wglEnumerateVideoCaptureDevicesNV(HDC hDc, HVIDEOINPUTDEVICENV * phDeviceList);
BOOL wglLockVideoCaptureDeviceNV(HDC hDc, HVIDEOINPUTDEVICENV hDevice);
BOOL wglQueryVideoCaptureDeviceNV(HDC hDc, HVIDEOINPUTDEVICENV hDevice, int iAttribute, int * piValue);
BOOL wglReleaseVideoCaptureDeviceNV(HDC hDc, HVIDEOINPUTDEVICENV hDevice);
BOOL wglBindVideoImageNV(HPVIDEODEV hVideoDevice, HPBUFFERARB hPbuffer, int iVideoBuffer);
BOOL wglGetVideoDeviceNV(HDC hDC, int numDevices, HPVIDEODEV * hVideoDevice);
BOOL wglGetVideoInfoNV(HPVIDEODEV hpVideoDevice, unsigned long * pulCounterOutputPbuffer, unsigned long * pulCounterOutputVideo);
BOOL wglReleaseVideoDeviceNV(HPVIDEODEV hVideoDevice);
BOOL wglReleaseVideoImageNV(HPBUFFERARB hPbuffer, int iVideoBuffer);
BOOL wglSendPbufferToVideoNV(HPBUFFERARB hPbuffer, int iBufferType, unsigned long * pulCounterPbuffer, BOOL bBlock);
void * wglAllocateMemoryNV(GLsizei size, GLfloat readfreq, GLfloat writefreq, GLfloat priority);
void wglFreeMemoryNV(void * pointer);
BOOL wglGetMscRateOML(HDC hdc, INT32 * numerator, INT32 * denominator);
BOOL wglGetSyncValuesOML(HDC hdc, INT64 * ust, INT64 * msc, INT64 * sbc);
INT64 wglSwapBuffersMscOML(HDC hdc, INT64 target_msc, INT64 divisor, INT64 remainder);
INT64 wglSwapLayerBuffersMscOML(HDC hdc, INT fuPlanes, INT64 target_msc, INT64 divisor, INT64 remainder);
BOOL wglWaitForMscOML(HDC hdc, INT64 target_msc, INT64 divisor, INT64 remainder, INT64 * ust, INT64 * msc, INT64 * sbc);
BOOL wglWaitForSbcOML(HDC hdc, INT64 target_sbc, INT64 * ust, INT64 * msc, INT64 * sbc);
#else
#define ChoosePixelFormat (gloam_wgl_context.ChoosePixelFormat)
#define DescribePixelFormat (gloam_wgl_context.DescribePixelFormat)
#define GetEnhMetaFilePixelFormat (gloam_wgl_context.GetEnhMetaFilePixelFormat)
#define GetPixelFormat (gloam_wgl_context.GetPixelFormat)
#define SetPixelFormat (gloam_wgl_context.SetPixelFormat)
#define SwapBuffers (gloam_wgl_context.SwapBuffers)
#define wglCopyContext (gloam_wgl_context.CopyContext)
#define wglCreateContext (gloam_wgl_context.CreateContext)
#define wglCreateLayerContext (gloam_wgl_context.CreateLayerContext)
#define wglDeleteContext (gloam_wgl_context.DeleteContext)
#define wglDescribeLayerPlane (gloam_wgl_context.DescribeLayerPlane)
#define wglGetCurrentContext (gloam_wgl_context.GetCurrentContext)
#define wglGetCurrentDC (gloam_wgl_context.GetCurrentDC)
#define wglGetLayerPaletteEntries (gloam_wgl_context.GetLayerPaletteEntries)
#define wglGetProcAddress (gloam_wgl_context.GetProcAddress)
#define wglMakeCurrent (gloam_wgl_context.MakeCurrent)
#define wglRealizeLayerPalette (gloam_wgl_context.RealizeLayerPalette)
#define wglSetLayerPaletteEntries (gloam_wgl_context.SetLayerPaletteEntries)
#define wglShareLists (gloam_wgl_context.ShareLists)
#define wglSwapLayerBuffers (gloam_wgl_context.SwapLayerBuffers)
#define wglUseFontBitmaps (gloam_wgl_context.UseFontBitmaps)
#define wglUseFontBitmapsA (gloam_wgl_context.UseFontBitmapsA)
#define wglUseFontBitmapsW (gloam_wgl_context.UseFontBitmapsW)
#define wglUseFontOutlines (gloam_wgl_context.UseFontOutlines)
#define wglUseFontOutlinesA (gloam_wgl_context.UseFontOutlinesA)
#define wglUseFontOutlinesW (gloam_wgl_context.UseFontOutlinesW)
#define wglSetStereoEmitterState3DL (gloam_wgl_context.SetStereoEmitterState3DL)
#define wglBlitContextFramebufferAMD (gloam_wgl_context.BlitContextFramebufferAMD)
#define wglCreateAssociatedContextAMD (gloam_wgl_context.CreateAssociatedContextAMD)
#define wglCreateAssociatedContextAttribsAMD (gloam_wgl_context.CreateAssociatedContextAttribsAMD)
#define wglDeleteAssociatedContextAMD (gloam_wgl_context.DeleteAssociatedContextAMD)
#define wglGetContextGPUIDAMD (gloam_wgl_context.GetContextGPUIDAMD)
#define wglGetCurrentAssociatedContextAMD (gloam_wgl_context.GetCurrentAssociatedContextAMD)
#define wglGetGPUIDsAMD (gloam_wgl_context.GetGPUIDsAMD)
#define wglGetGPUInfoAMD (gloam_wgl_context.GetGPUInfoAMD)
#define wglMakeAssociatedContextCurrentAMD (gloam_wgl_context.MakeAssociatedContextCurrentAMD)
#define wglCreateBufferRegionARB (gloam_wgl_context.CreateBufferRegionARB)
#define wglDeleteBufferRegionARB (gloam_wgl_context.DeleteBufferRegionARB)
#define wglRestoreBufferRegionARB (gloam_wgl_context.RestoreBufferRegionARB)
#define wglSaveBufferRegionARB (gloam_wgl_context.SaveBufferRegionARB)
#define wglCreateContextAttribsARB (gloam_wgl_context.CreateContextAttribsARB)
#define wglGetExtensionsStringARB (gloam_wgl_context.GetExtensionsStringARB)
#define wglGetCurrentReadDCARB (gloam_wgl_context.GetCurrentReadDCARB)
#define wglMakeContextCurrentARB (gloam_wgl_context.MakeContextCurrentARB)
#define wglCreatePbufferARB (gloam_wgl_context.CreatePbufferARB)
#define wglDestroyPbufferARB (gloam_wgl_context.DestroyPbufferARB)
#define wglGetPbufferDCARB (gloam_wgl_context.GetPbufferDCARB)
#define wglQueryPbufferARB (gloam_wgl_context.QueryPbufferARB)
#define wglReleasePbufferDCARB (gloam_wgl_context.ReleasePbufferDCARB)
#define wglChoosePixelFormatARB (gloam_wgl_context.ChoosePixelFormatARB)
#define wglGetPixelFormatAttribfvARB (gloam_wgl_context.GetPixelFormatAttribfvARB)
#define wglGetPixelFormatAttribivARB (gloam_wgl_context.GetPixelFormatAttribivARB)
#define wglBindTexImageARB (gloam_wgl_context.BindTexImageARB)
#define wglReleaseTexImageARB (gloam_wgl_context.ReleaseTexImageARB)
#define wglSetPbufferAttribARB (gloam_wgl_context.SetPbufferAttribARB)
#define wglBindDisplayColorTableEXT (gloam_wgl_context.BindDisplayColorTableEXT)
#define wglCreateDisplayColorTableEXT (gloam_wgl_context.CreateDisplayColorTableEXT)
#define wglDestroyDisplayColorTableEXT (gloam_wgl_context.DestroyDisplayColorTableEXT)
#define wglLoadDisplayColorTableEXT (gloam_wgl_context.LoadDisplayColorTableEXT)
#define wglGetExtensionsStringEXT (gloam_wgl_context.GetExtensionsStringEXT)
#define wglGetCurrentReadDCEXT (gloam_wgl_context.GetCurrentReadDCEXT)
#define wglMakeContextCurrentEXT (gloam_wgl_context.MakeContextCurrentEXT)
#define wglCreatePbufferEXT (gloam_wgl_context.CreatePbufferEXT)
#define wglDestroyPbufferEXT (gloam_wgl_context.DestroyPbufferEXT)
#define wglGetPbufferDCEXT (gloam_wgl_context.GetPbufferDCEXT)
#define wglQueryPbufferEXT (gloam_wgl_context.QueryPbufferEXT)
#define wglReleasePbufferDCEXT (gloam_wgl_context.ReleasePbufferDCEXT)
#define wglChoosePixelFormatEXT (gloam_wgl_context.ChoosePixelFormatEXT)
#define wglGetPixelFormatAttribfvEXT (gloam_wgl_context.GetPixelFormatAttribfvEXT)
#define wglGetPixelFormatAttribivEXT (gloam_wgl_context.GetPixelFormatAttribivEXT)
#define wglGetSwapIntervalEXT (gloam_wgl_context.GetSwapIntervalEXT)
#define wglSwapIntervalEXT (gloam_wgl_context.SwapIntervalEXT)
#define wglGetDigitalVideoParametersI3D (gloam_wgl_context.GetDigitalVideoParametersI3D)
#define wglSetDigitalVideoParametersI3D (gloam_wgl_context.SetDigitalVideoParametersI3D)
#define wglGetGammaTableI3D (gloam_wgl_context.GetGammaTableI3D)
#define wglGetGammaTableParametersI3D (gloam_wgl_context.GetGammaTableParametersI3D)
#define wglSetGammaTableI3D (gloam_wgl_context.SetGammaTableI3D)
#define wglSetGammaTableParametersI3D (gloam_wgl_context.SetGammaTableParametersI3D)
#define wglDisableGenlockI3D (gloam_wgl_context.DisableGenlockI3D)
#define wglEnableGenlockI3D (gloam_wgl_context.EnableGenlockI3D)
#define wglGenlockSampleRateI3D (gloam_wgl_context.GenlockSampleRateI3D)
#define wglGenlockSourceDelayI3D (gloam_wgl_context.GenlockSourceDelayI3D)
#define wglGenlockSourceEdgeI3D (gloam_wgl_context.GenlockSourceEdgeI3D)
#define wglGenlockSourceI3D (gloam_wgl_context.GenlockSourceI3D)
#define wglGetGenlockSampleRateI3D (gloam_wgl_context.GetGenlockSampleRateI3D)
#define wglGetGenlockSourceDelayI3D (gloam_wgl_context.GetGenlockSourceDelayI3D)
#define wglGetGenlockSourceEdgeI3D (gloam_wgl_context.GetGenlockSourceEdgeI3D)
#define wglGetGenlockSourceI3D (gloam_wgl_context.GetGenlockSourceI3D)
#define wglIsEnabledGenlockI3D (gloam_wgl_context.IsEnabledGenlockI3D)
#define wglQueryGenlockMaxSourceDelayI3D (gloam_wgl_context.QueryGenlockMaxSourceDelayI3D)
#define wglAssociateImageBufferEventsI3D (gloam_wgl_context.AssociateImageBufferEventsI3D)
#define wglCreateImageBufferI3D (gloam_wgl_context.CreateImageBufferI3D)
#define wglDestroyImageBufferI3D (gloam_wgl_context.DestroyImageBufferI3D)
#define wglReleaseImageBufferEventsI3D (gloam_wgl_context.ReleaseImageBufferEventsI3D)
#define wglDisableFrameLockI3D (gloam_wgl_context.DisableFrameLockI3D)
#define wglEnableFrameLockI3D (gloam_wgl_context.EnableFrameLockI3D)
#define wglIsEnabledFrameLockI3D (gloam_wgl_context.IsEnabledFrameLockI3D)
#define wglQueryFrameLockMasterI3D (gloam_wgl_context.QueryFrameLockMasterI3D)
#define wglBeginFrameTrackingI3D (gloam_wgl_context.BeginFrameTrackingI3D)
#define wglEndFrameTrackingI3D (gloam_wgl_context.EndFrameTrackingI3D)
#define wglGetFrameUsageI3D (gloam_wgl_context.GetFrameUsageI3D)
#define wglQueryFrameTrackingI3D (gloam_wgl_context.QueryFrameTrackingI3D)
#define wglCopyImageSubDataNV (gloam_wgl_context.CopyImageSubDataNV)
#define wglDelayBeforeSwapNV (gloam_wgl_context.DelayBeforeSwapNV)
#define wglDXCloseDeviceNV (gloam_wgl_context.DXCloseDeviceNV)
#define wglDXLockObjectsNV (gloam_wgl_context.DXLockObjectsNV)
#define wglDXObjectAccessNV (gloam_wgl_context.DXObjectAccessNV)
#define wglDXOpenDeviceNV (gloam_wgl_context.DXOpenDeviceNV)
#define wglDXRegisterObjectNV (gloam_wgl_context.DXRegisterObjectNV)
#define wglDXSetResourceShareHandleNV (gloam_wgl_context.DXSetResourceShareHandleNV)
#define wglDXUnlockObjectsNV (gloam_wgl_context.DXUnlockObjectsNV)
#define wglDXUnregisterObjectNV (gloam_wgl_context.DXUnregisterObjectNV)
#define wglCreateAffinityDCNV (gloam_wgl_context.CreateAffinityDCNV)
#define wglDeleteDCNV (gloam_wgl_context.DeleteDCNV)
#define wglEnumGpuDevicesNV (gloam_wgl_context.EnumGpuDevicesNV)
#define wglEnumGpusFromAffinityDCNV (gloam_wgl_context.EnumGpusFromAffinityDCNV)
#define wglEnumGpusNV (gloam_wgl_context.EnumGpusNV)
#define wglBindVideoDeviceNV (gloam_wgl_context.BindVideoDeviceNV)
#define wglEnumerateVideoDevicesNV (gloam_wgl_context.EnumerateVideoDevicesNV)
#define wglQueryCurrentContextNV (gloam_wgl_context.QueryCurrentContextNV)
#define wglBindSwapBarrierNV (gloam_wgl_context.BindSwapBarrierNV)
#define wglJoinSwapGroupNV (gloam_wgl_context.JoinSwapGroupNV)
#define wglQueryFrameCountNV (gloam_wgl_context.QueryFrameCountNV)
#define wglQueryMaxSwapGroupsNV (gloam_wgl_context.QueryMaxSwapGroupsNV)
#define wglQuerySwapGroupNV (gloam_wgl_context.QuerySwapGroupNV)
#define wglResetFrameCountNV (gloam_wgl_context.ResetFrameCountNV)
#define wglBindVideoCaptureDeviceNV (gloam_wgl_context.BindVideoCaptureDeviceNV)
#define wglEnumerateVideoCaptureDevicesNV (gloam_wgl_context.EnumerateVideoCaptureDevicesNV)
#define wglLockVideoCaptureDeviceNV (gloam_wgl_context.LockVideoCaptureDeviceNV)
#define wglQueryVideoCaptureDeviceNV (gloam_wgl_context.QueryVideoCaptureDeviceNV)
#define wglReleaseVideoCaptureDeviceNV (gloam_wgl_context.ReleaseVideoCaptureDeviceNV)
#define wglBindVideoImageNV (gloam_wgl_context.BindVideoImageNV)
#define wglGetVideoDeviceNV (gloam_wgl_context.GetVideoDeviceNV)
#define wglGetVideoInfoNV (gloam_wgl_context.GetVideoInfoNV)
#define wglReleaseVideoDeviceNV (gloam_wgl_context.ReleaseVideoDeviceNV)
#define wglReleaseVideoImageNV (gloam_wgl_context.ReleaseVideoImageNV)
#define wglSendPbufferToVideoNV (gloam_wgl_context.SendPbufferToVideoNV)
#define wglAllocateMemoryNV (gloam_wgl_context.AllocateMemoryNV)
#define wglFreeMemoryNV (gloam_wgl_context.FreeMemoryNV)
#define wglGetMscRateOML (gloam_wgl_context.GetMscRateOML)
#define wglGetSyncValuesOML (gloam_wgl_context.GetSyncValuesOML)
#define wglSwapBuffersMscOML (gloam_wgl_context.SwapBuffersMscOML)
#define wglSwapLayerBuffersMscOML (gloam_wgl_context.SwapLayerBuffersMscOML)
#define wglWaitForMscOML (gloam_wgl_context.WaitForMscOML)
#define wglWaitForSbcOML (gloam_wgl_context.WaitForSbcOML)
#endif /* __INTELLISENSE__ */

/* ---- API declarations ---------------------------------------------------- */

#ifndef GLOAM_DEFINED_CALLBACK_TYPES_
#define GLOAM_DEFINED_CALLBACK_TYPES_
/* Opaque function pointer type — the common return type for all load
   callbacks.  Callers cast to the specific PFN type they need. */
typedef void (*GloamAPIProc)(void);

/* Load function pointer type (GL / EGL / GLX / WGL). */
typedef GloamAPIProc (*GloamLoadFunc)(const char *name);
#endif
int gloamLoadWGLContext(GloamWGLContext *context, HDC hdc, GloamLoadFunc getProcAddr);
int gloamLoadWGL(HDC hdc, GloamLoadFunc getProcAddr);
/* Built-in loader: opens the platform library if needed and calls Load for you.
   Each Load function may be called multiple times (additive, same contract as
   the underlying gloamLoad* functions).  Pre-populate context->gloam_loader_handle
   to supply your own library handle; zero it before Unload to retain ownership. */
int  gloamLoaderLoadWGLContext(GloamWGLContext *context, HDC hdc);
int  gloamLoaderLoadWGL(HDC hdc);
void gloamLoaderUnloadWGLContext(GloamWGLContext *context);
void gloamLoaderUnloadWGL(void);
void gloamLoaderResetWGLContext(GloamWGLContext *context);
void gloamLoaderResetWGL(void);

#ifdef __cplusplus
}
#endif

#endif /* _WIN32 */

#endif /* GLOAM_WGL_H */