/*
 * Generated by gloam 0.1.7. DO NOT EDIT.
 *
 *   gloam --predecessors --promoted --api=gl:core,gles2,vulkan,egl,glx,wgl --out-path D:\dev\darwinia\contrib\gloam --merge c --alias --loader
 *
 * Extensions: all (66 total)
 *
 * Copyright (c) 2026 Steven Noonan
 * SPDX-License-Identifier: MIT
 *
 * Portions derived from Khronos Group XML API Registry specifications.
 * Copyright (c) 2013-2026 The Khronos Group Inc.
 * SPDX-License-Identifier: Apache-2.0
 */

#ifdef __linux

#include <gloam/glx.h>

#include <stdlib.h>  /* calloc, free    */
#include <stddef.h>
#include <stdio.h>   /* sscanf          */
#include <string.h>  /* strlen, strncmp */
#ifdef _WIN32
#  ifndef WIN32_LEAN_AND_MEAN
#    define WIN32_LEAN_AND_MEAN
#  endif
#  include <windows.h>  /* LoadLibrary, GetProcAddress */
#else
#  include <dlfcn.h> /* dlopen, dlsym, dlclose */
#endif

#if defined(__x86_64__) || defined(__i386__) || defined(_M_IX86) || defined(_M_X64)
#  define XXH_VECTOR XXH_SSE2
#  include <immintrin.h>
#elif defined(__aarch64__) || defined(__arm__) || defined(_M_ARM) || defined(_M_ARM64)
#  define XXH_VECTOR XXH_NEON
#  include <arm_neon.h>
#endif
#ifndef GLOAM_EXTERNAL_XXHASH
#  define XXH_INLINE_ALL
#  define XXH_NO_STREAM
#endif
#include "xxhash.h"

#ifndef GLOAM_IMPL_UTIL_C_
#define GLOAM_IMPL_UTIL_C_

/* MSVC vs GCC/Clang sscanf */
#ifdef _MSC_VER
#  define GLOAM_IMPL_UTIL_SSCANF sscanf_s
#else
#  define GLOAM_IMPL_UTIL_SSCANF sscanf
#endif

/* GLOAM_NO_INLINE — suppress inlining on functions that should stay out of
   the hot path (sort, hash, etc.) to avoid code bloat at call sites. */
#ifdef _MSC_VER
#  define GLOAM_NO_INLINE __declspec(noinline)
#else
#  define GLOAM_NO_INLINE __attribute__((noinline))
#endif

#define GLOAM_ARRAYSIZE(x) (sizeof(x) / sizeof((x)[0]))
#define GLOAM_UNUSED(x)    ((void)(x))

/* Opaque function pointer type — the common return type for all load
   callbacks.  Callers cast to the specific PFN type they need. */
typedef void (*GloamAPIProc)(void);

/* Load function pointer type: plain proc-addr callback (GL / EGL / GLX / WGL). */
typedef GloamAPIProc (*GloamLoadFunc)(const char *name);

/* Contiguous run of pfnArray slots belonging to one feature or extension.
   Used by the range-based PFN loading loop. */
typedef struct {
    uint16_t extension; /* index into featArray or extArray */
    uint16_t start;     /* first pfnArray index in this run  */
    uint16_t count;     /* number of consecutive slots       */
} GloamPfnRange_t;

/* Bijective alias pair: if canonical slot is null but secondary is loaded
   (or vice versa), the loaded pointer is propagated to both slots. */
typedef struct {
    uint16_t first;  /* canonical (shortest name) pfnArray index */
    uint16_t second; /* alias pfnArray index                     */
} GloamAliasPair_t;

#endif /* GLOAM_IMPL_UTIL_C_ */

#ifndef GLOAM_IMPL_HASHSEARCH_C_
#define GLOAM_IMPL_HASHSEARCH_C_

/* gloam_sort_hashes — in-place Shellsort on a uint64_t array.
 *
 * Ciura (2001) gap sequence.  Gaps larger than n are skipped at runtime so
 * small arrays (< 10 extensions) take only a couple of passes.  No heap
 * allocation; code size is ~80 bytes on x86-64.
 */
GLOAM_NO_INLINE static void gloam_sort_hashes(uint64_t *a, size_t n) {
    static const size_t kGaps[] = { 701, 301, 132, 57, 23, 10, 4, 1 };
    size_t gi = 0;
    if (!a || n < 2) return;
    /* Skip gaps that are larger than the array. */
    while (gi < GLOAM_ARRAYSIZE(kGaps) && kGaps[gi] >= n) ++gi;
    for (; gi < GLOAM_ARRAYSIZE(kGaps); ++gi) {
        size_t gap = kGaps[gi], i;
        for (i = gap; i < n; ++i) {
            uint64_t v = a[i];
            size_t j = i;
            while (j >= gap && a[j - gap] > v) {
                a[j] = a[j - gap];
                j -= gap;
            }
            a[j] = v;
        }
    }
}

/* gloam_hash_search — binary search for `target` in a sorted uint64_t array.
 * Returns 1 if found, 0 otherwise.
 */
GLOAM_NO_INLINE static int gloam_hash_search(const uint64_t *arr, uint32_t size, uint64_t target) {
    int32_t lo = 0, hi = (int32_t)size - 1;
    while (lo <= hi) {
        int32_t mid = lo + (hi - lo) / 2;
        if (arr[mid] == target) return 1;
        if (arr[mid] < target)  lo = mid + 1;
        else                    hi = mid - 1;
    }
    return 0;
}

/* gloam_hash_string — hash a NUL-terminated string with XXH3-64.
 * The same algorithm is used at generator time to pre-bake kExtHashes[],
 * guaranteeing that driver-reported names and the embedded table match.
 */
GLOAM_NO_INLINE static uint64_t gloam_hash_string(const char *str, size_t length) {
    return XXH3_64bits(str, length);
}
#endif /* GLOAM_IMPL_HASHSEARCH_C_ */

/* ---- Global context (zero-initialised at program startup) ---------------- */
#ifdef __cplusplus
GloamGLXContext gloam_glx_context = {};
#else
GloamGLXContext gloam_glx_context = { 0 };
#endif

/* ---- Function name table -------------------------------------------------
   Indexed by command.index.  Used for bootstrapping and by the PFN-range
   loader to call getProcAddr(name) for each slot. */
static const char * const kFnNames_GLX[] = {
    /*    0 */ "glXChooseVisual",
    /*    1 */ "glXCreateContext",
    /*    2 */ "glXDestroyContext",
    /*    3 */ "glXMakeCurrent",
    /*    4 */ "glXCopyContext",
    /*    5 */ "glXSwapBuffers",
    /*    6 */ "glXCreateGLXPixmap",
    /*    7 */ "glXDestroyGLXPixmap",
    /*    8 */ "glXQueryExtension",
    /*    9 */ "glXQueryVersion",
    /*   10 */ "glXIsDirect",
    /*   11 */ "glXGetConfig",
    /*   12 */ "glXGetCurrentContext",
    /*   13 */ "glXGetCurrentDrawable",
    /*   14 */ "glXWaitGL",
    /*   15 */ "glXWaitX",
    /*   16 */ "glXUseXFont",
    /*   17 */ "glXQueryExtensionsString",
    /*   18 */ "glXQueryServerString",
    /*   19 */ "glXGetClientString",
    /*   20 */ "glXGetCurrentDisplay",
    /*   21 */ "glXGetFBConfigs",
    /*   22 */ "glXChooseFBConfig",
    /*   23 */ "glXGetFBConfigAttrib",
    /*   24 */ "glXGetVisualFromFBConfig",
    /*   25 */ "glXCreateWindow",
    /*   26 */ "glXDestroyWindow",
    /*   27 */ "glXCreatePixmap",
    /*   28 */ "glXDestroyPixmap",
    /*   29 */ "glXCreatePbuffer",
    /*   30 */ "glXDestroyPbuffer",
    /*   31 */ "glXQueryDrawable",
    /*   32 */ "glXCreateNewContext",
    /*   33 */ "glXMakeContextCurrent",
    /*   34 */ "glXGetCurrentReadDrawable",
    /*   35 */ "glXQueryContext",
    /*   36 */ "glXSelectEvent",
    /*   37 */ "glXGetSelectedEvent",
    /*   38 */ "glXGetProcAddress",
    /*   39 */ "glXGetGPUIDsAMD",
    /*   40 */ "glXGetGPUInfoAMD",
    /*   41 */ "glXGetContextGPUIDAMD",
    /*   42 */ "glXCreateAssociatedContextAMD",
    /*   43 */ "glXCreateAssociatedContextAttribsAMD",
    /*   44 */ "glXDeleteAssociatedContextAMD",
    /*   45 */ "glXMakeAssociatedContextCurrentAMD",
    /*   46 */ "glXGetCurrentAssociatedContextAMD",
    /*   47 */ "glXBlitContextFramebufferAMD",
    /*   48 */ "glXCreateContextAttribsARB",
    /*   49 */ "glXGetProcAddressARB",
    /*   50 */ "glXGetCurrentDisplayEXT",
    /*   51 */ "glXQueryContextInfoEXT",
    /*   52 */ "glXGetContextIDEXT",
    /*   53 */ "glXImportContextEXT",
    /*   54 */ "glXFreeContextEXT",
    /*   55 */ "glXSwapIntervalEXT",
    /*   56 */ "glXBindTexImageEXT",
    /*   57 */ "glXReleaseTexImageEXT",
    /*   58 */ "glXGetAGPOffsetMESA",
    /*   59 */ "glXCopySubBufferMESA",
    /*   60 */ "glXCreateGLXPixmapMESA",
    /*   61 */ "glXQueryCurrentRendererIntegerMESA",
    /*   62 */ "glXQueryCurrentRendererStringMESA",
    /*   63 */ "glXQueryRendererIntegerMESA",
    /*   64 */ "glXQueryRendererStringMESA",
    /*   65 */ "glXReleaseBuffersMESA",
    /*   66 */ "glXSet3DfxModeMESA",
    /*   67 */ "glXGetSwapIntervalMESA",
    /*   68 */ "glXSwapIntervalMESA",
    /*   69 */ "glXCopyBufferSubDataNV",
    /*   70 */ "glXNamedCopyBufferSubDataNV",
    /*   71 */ "glXCopyImageSubDataNV",
    /*   72 */ "glXDelayBeforeSwapNV",
    /*   73 */ "glXEnumerateVideoDevicesNV",
    /*   74 */ "glXBindVideoDeviceNV",
    /*   75 */ "glXJoinSwapGroupNV",
    /*   76 */ "glXBindSwapBarrierNV",
    /*   77 */ "glXQuerySwapGroupNV",
    /*   78 */ "glXQueryMaxSwapGroupsNV",
    /*   79 */ "glXQueryFrameCountNV",
    /*   80 */ "glXResetFrameCountNV",
    /*   81 */ "glXBindVideoCaptureDeviceNV",
    /*   82 */ "glXEnumerateVideoCaptureDevicesNV",
    /*   83 */ "glXLockVideoCaptureDeviceNV",
    /*   84 */ "glXQueryVideoCaptureDeviceNV",
    /*   85 */ "glXReleaseVideoCaptureDeviceNV",
    /*   86 */ "glXGetVideoDeviceNV",
    /*   87 */ "glXReleaseVideoDeviceNV",
    /*   88 */ "glXBindVideoImageNV",
    /*   89 */ "glXReleaseVideoImageNV",
    /*   90 */ "glXSendPbufferToVideoNV",
    /*   91 */ "glXGetVideoInfoNV",
    /*   92 */ "glXGetSyncValuesOML",
    /*   93 */ "glXGetMscRateOML",
    /*   94 */ "glXSwapBuffersMscOML",
    /*   95 */ "glXWaitForMscOML",
    /*   96 */ "glXWaitForSbcOML",
    /*   97 */ "glXCushionSGI",
    /*   98 */ "glXMakeCurrentReadSGI",
    /*   99 */ "glXGetCurrentReadDrawableSGI",
    /*  100 */ "glXSwapIntervalSGI",
    /*  101 */ "glXGetVideoSyncSGI",
    /*  102 */ "glXWaitVideoSyncSGI",
    /*  103 */ "glXGetFBConfigAttribSGIX",
    /*  104 */ "glXChooseFBConfigSGIX",
    /*  105 */ "glXCreateGLXPixmapWithConfigSGIX",
    /*  106 */ "glXCreateContextWithConfigSGIX",
    /*  107 */ "glXGetVisualFromFBConfigSGIX",
    /*  108 */ "glXGetFBConfigFromVisualSGIX",
    /*  109 */ "glXQueryHyperpipeNetworkSGIX",
    /*  110 */ "glXHyperpipeConfigSGIX",
    /*  111 */ "glXQueryHyperpipeConfigSGIX",
    /*  112 */ "glXDestroyHyperpipeConfigSGIX",
    /*  113 */ "glXBindHyperpipeSGIX",
    /*  114 */ "glXQueryHyperpipeBestAttribSGIX",
    /*  115 */ "glXHyperpipeAttribSGIX",
    /*  116 */ "glXQueryHyperpipeAttribSGIX",
    /*  117 */ "glXCreateGLXPbufferSGIX",
    /*  118 */ "glXDestroyGLXPbufferSGIX",
    /*  119 */ "glXQueryGLXPbufferSGIX",
    /*  120 */ "glXSelectEventSGIX",
    /*  121 */ "glXGetSelectedEventSGIX",
    /*  122 */ "glXBindSwapBarrierSGIX",
    /*  123 */ "glXQueryMaxSwapBarriersSGIX",
    /*  124 */ "glXJoinSwapGroupSGIX",
    /*  125 */ "glXBindChannelToWindowSGIX",
    /*  126 */ "glXChannelRectSGIX",
    /*  127 */ "glXQueryChannelRectSGIX",
    /*  128 */ "glXQueryChannelDeltasSGIX",
    /*  129 */ "glXChannelRectSyncSGIX",
    /*  130 */ "glXGetTransparentIndexSUN"
};


/* ---- Extension hash table ------------------------------------------------
   One XXH3-64 hash per extension, in extArray index order.
   Pre-baked at generator time with the same algorithm used at load time. */
static const uint64_t kExtHashes_GLX[] = {
    /*    0 */ 0xc090be22f50edf0fULL, /* GLX_3DFX_multisample */
    /*    1 */ 0x072d0fa7672bf59aULL, /* GLX_AMD_gpu_association */
    /*    2 */ 0x048a82b333a65f74ULL, /* GLX_ARB_context_flush_control */
    /*    3 */ 0x3f4d9cd2b079e931ULL, /* GLX_ARB_create_context */
    /*    4 */ 0xbd7c0e0c70fd916bULL, /* GLX_ARB_create_context_no_error */
    /*    5 */ 0x8690d94d5a4ce24dULL, /* GLX_ARB_create_context_profile */
    /*    6 */ 0x047a6e2eedd3d3d3ULL, /* GLX_ARB_create_context_robustness */
    /*    7 */ 0xa07f3edb8ce15ce0ULL, /* GLX_ARB_fbconfig_float */
    /*    8 */ 0xd5e2cc7383f82f45ULL, /* GLX_ARB_framebuffer_sRGB */
    /*    9 */ 0x6fad53b639e2a390ULL, /* GLX_ARB_get_proc_address */
    /*   10 */ 0x7dd3a391032250e3ULL, /* GLX_ARB_multisample */
    /*   11 */ 0xdba9a6195cec812fULL, /* GLX_ARB_robustness_application_isolation */
    /*   12 */ 0x081dfaeea13e2411ULL, /* GLX_ARB_robustness_share_group_isolation */
    /*   13 */ 0x2e804f63a6dcd082ULL, /* GLX_ARB_vertex_buffer_object */
    /*   14 */ 0xe7306595f98ee4e1ULL, /* GLX_EXT_buffer_age */
    /*   15 */ 0x1b481fa7315ee5b6ULL, /* GLX_EXT_context_priority */
    /*   16 */ 0xaec606cc661980b4ULL, /* GLX_EXT_create_context_es2_profile */
    /*   17 */ 0xf1d970eb90dd86a0ULL, /* GLX_EXT_create_context_es_profile */
    /*   18 */ 0x346e291f40286e34ULL, /* GLX_EXT_fbconfig_packed_float */
    /*   19 */ 0xd153ec8aa16793b3ULL, /* GLX_EXT_framebuffer_sRGB */
    /*   20 */ 0x83387f3dfb09e41fULL, /* GLX_EXT_get_drawable_type */
    /*   21 */ 0x03bcfc5a3cae3c31ULL, /* GLX_EXT_import_context */
    /*   22 */ 0x6f6d381e8ae478f2ULL, /* GLX_EXT_libglvnd */
    /*   23 */ 0x12a9351ba20ce5a3ULL, /* GLX_EXT_no_config_context */
    /*   24 */ 0x7cef1b9da97fd70eULL, /* GLX_EXT_stereo_tree */
    /*   25 */ 0xb279c1493993d32dULL, /* GLX_EXT_swap_control */
    /*   26 */ 0x81782a45ccd71ff8ULL, /* GLX_EXT_swap_control_tear */
    /*   27 */ 0xcd4daa50b9e2718aULL, /* GLX_EXT_texture_from_pixmap */
    /*   28 */ 0xb747ecf03b25c5b0ULL, /* GLX_EXT_visual_info */
    /*   29 */ 0x6c1fc772574daedcULL, /* GLX_EXT_visual_rating */
    /*   30 */ 0x90a93448eb7baa50ULL, /* GLX_INTEL_swap_event */
    /*   31 */ 0xce0282d625639b9bULL, /* GLX_MESA_agp_offset */
    /*   32 */ 0x910ff30a1deb6b79ULL, /* GLX_MESA_copy_sub_buffer */
    /*   33 */ 0xdab23c1e71961e55ULL, /* GLX_MESA_pixmap_colormap */
    /*   34 */ 0x29596e504e9a6a25ULL, /* GLX_MESA_query_renderer */
    /*   35 */ 0x0e4e87fbd85b8f81ULL, /* GLX_MESA_release_buffers */
    /*   36 */ 0x29561836651d917aULL, /* GLX_MESA_set_3dfx_mode */
    /*   37 */ 0xd32cf4de2880d29fULL, /* GLX_MESA_swap_control */
    /*   38 */ 0xc6df36e9a84a750eULL, /* GLX_NV_copy_buffer */
    /*   39 */ 0x939dc7e8d56cb021ULL, /* GLX_NV_copy_image */
    /*   40 */ 0xdae9b56ed6046e29ULL, /* GLX_NV_delay_before_swap */
    /*   41 */ 0x4e3ccfe50be2411dULL, /* GLX_NV_float_buffer */
    /*   42 */ 0xc52be3ef322db374ULL, /* GLX_NV_multigpu_context */
    /*   43 */ 0x6073c41473e50bfaULL, /* GLX_NV_multisample_coverage */
    /*   44 */ 0x871aa145ea386a73ULL, /* GLX_NV_present_video */
    /*   45 */ 0xdb0def6df3a16d6cULL, /* GLX_NV_robustness_video_memory_purge */
    /*   46 */ 0x2f414e4fcd131e32ULL, /* GLX_NV_swap_group */
    /*   47 */ 0xefa7c60274d87055ULL, /* GLX_NV_video_capture */
    /*   48 */ 0x963ec6ee3eb6b7fcULL, /* GLX_NV_video_out */
    /*   49 */ 0x139db0a508493724ULL, /* GLX_OML_swap_method */
    /*   50 */ 0xffaa3afdd9aa1090ULL, /* GLX_OML_sync_control */
    /*   51 */ 0xe386bd135a6e5f2cULL, /* GLX_SGIS_blended_overlay */
    /*   52 */ 0x900c6b39bcf9e3aeULL, /* GLX_SGIS_multisample */
    /*   53 */ 0x5c16b82b4300c08cULL, /* GLX_SGIS_shared_multisample */
    /*   54 */ 0x6dadb65d0ec947c2ULL, /* GLX_SGIX_fbconfig */
    /*   55 */ 0x341bcc9d120c6f49ULL, /* GLX_SGIX_hyperpipe */
    /*   56 */ 0x09ddc4c71d7734d0ULL, /* GLX_SGIX_pbuffer */
    /*   57 */ 0xaf8c148fdb3c3939ULL, /* GLX_SGIX_swap_barrier */
    /*   58 */ 0x4cab82df7b1591eeULL, /* GLX_SGIX_swap_group */
    /*   59 */ 0xadbdc7e24c604283ULL, /* GLX_SGIX_video_resize */
    /*   60 */ 0x07a1d27a401cc274ULL, /* GLX_SGIX_visual_select_group */
    /*   61 */ 0xb54066e1e7b44f60ULL, /* GLX_SGI_cushion */
    /*   62 */ 0xb01c250c6b9a122aULL, /* GLX_SGI_make_current_read */
    /*   63 */ 0xad9c9c9f23007dd1ULL, /* GLX_SGI_swap_control */
    /*   64 */ 0x0d617d9b2139534bULL, /* GLX_SGI_video_sync */
    /*   65 */ 0xa1de47dd92ad3d02ULL  /* GLX_SUN_get_transparent_index */
};

/* ---- Feature PFN range table ---------------------------------------------
   Each entry maps one feature (by featArray index) to a contiguous run of
   pfnArray slots.  The loader iterates this table and bulk-loads the run
   when featArray[entry.extension] is set. */
static const GloamPfnRange_t kFeatPfnRanges_GLX[] = {
    {    0,    0,   17 }, /* GLX_VERSION_1_0 */
    {    1,   17,    3 }, /* GLX_VERSION_1_1 */
    {    2,   20,    1 }, /* GLX_VERSION_1_2 */
    {    3,   21,   17 }, /* GLX_VERSION_1_3 */
    {    4,   38,    1 }, /* GLX_VERSION_1_4 */
};

/* ---- PFN range helper (GL / EGL / GLX / WGL) ----------------------------
   Walks a contiguous run of pfnArray slots and calls the plain load callback
   (name only) for each one. */
static void gloam_load_pfn_range_glx(GloamGLXContext *context, GloamLoadFunc getProcAddr,
                                  uint16_t start, uint16_t count) {
    uint16_t i;
    for (i = start; i < (uint16_t)(start + count); ++i)
        context->pfnArray[i] = (void *)getProcAddr(kFnNames_GLX[i]);
}


/* ==========================================================================
   Per-API sections
   ========================================================================== */

/* --------------------------------------------------------------------------
   API: glx
   -------------------------------------------------------------------------- */

/* Extension index subset for glx: extArray indices this API supports. */
static const uint16_t kExtIdx_glx[] = {
       0, /* GLX_3DFX_multisample */
       1, /* GLX_AMD_gpu_association */
       2, /* GLX_ARB_context_flush_control */
       3, /* GLX_ARB_create_context */
       4, /* GLX_ARB_create_context_no_error */
       5, /* GLX_ARB_create_context_profile */
       6, /* GLX_ARB_create_context_robustness */
       7, /* GLX_ARB_fbconfig_float */
       8, /* GLX_ARB_framebuffer_sRGB */
       9, /* GLX_ARB_get_proc_address */
      10, /* GLX_ARB_multisample */
      11, /* GLX_ARB_robustness_application_isolation */
      12, /* GLX_ARB_robustness_share_group_isolation */
      13, /* GLX_ARB_vertex_buffer_object */
      14, /* GLX_EXT_buffer_age */
      15, /* GLX_EXT_context_priority */
      16, /* GLX_EXT_create_context_es2_profile */
      17, /* GLX_EXT_create_context_es_profile */
      18, /* GLX_EXT_fbconfig_packed_float */
      19, /* GLX_EXT_framebuffer_sRGB */
      20, /* GLX_EXT_get_drawable_type */
      21, /* GLX_EXT_import_context */
      22, /* GLX_EXT_libglvnd */
      23, /* GLX_EXT_no_config_context */
      24, /* GLX_EXT_stereo_tree */
      25, /* GLX_EXT_swap_control */
      26, /* GLX_EXT_swap_control_tear */
      27, /* GLX_EXT_texture_from_pixmap */
      28, /* GLX_EXT_visual_info */
      29, /* GLX_EXT_visual_rating */
      30, /* GLX_INTEL_swap_event */
      31, /* GLX_MESA_agp_offset */
      32, /* GLX_MESA_copy_sub_buffer */
      33, /* GLX_MESA_pixmap_colormap */
      34, /* GLX_MESA_query_renderer */
      35, /* GLX_MESA_release_buffers */
      36, /* GLX_MESA_set_3dfx_mode */
      37, /* GLX_MESA_swap_control */
      38, /* GLX_NV_copy_buffer */
      39, /* GLX_NV_copy_image */
      40, /* GLX_NV_delay_before_swap */
      41, /* GLX_NV_float_buffer */
      42, /* GLX_NV_multigpu_context */
      43, /* GLX_NV_multisample_coverage */
      44, /* GLX_NV_present_video */
      45, /* GLX_NV_robustness_video_memory_purge */
      46, /* GLX_NV_swap_group */
      47, /* GLX_NV_video_capture */
      48, /* GLX_NV_video_out */
      49, /* GLX_OML_swap_method */
      50, /* GLX_OML_sync_control */
      51, /* GLX_SGIS_blended_overlay */
      52, /* GLX_SGIS_multisample */
      53, /* GLX_SGIS_shared_multisample */
      54, /* GLX_SGIX_fbconfig */
      55, /* GLX_SGIX_hyperpipe */
      56, /* GLX_SGIX_pbuffer */
      57, /* GLX_SGIX_swap_barrier */
      58, /* GLX_SGIX_swap_group */
      59, /* GLX_SGIX_video_resize */
      60, /* GLX_SGIX_visual_select_group */
      61, /* GLX_SGI_cushion */
      62, /* GLX_SGI_make_current_read */
      63, /* GLX_SGI_swap_control */
      64, /* GLX_SGI_video_sync */
      65, /* GLX_SUN_get_transparent_index */
};

/* Extension PFN range table for glx. */
static const GloamPfnRange_t kExtPfnRanges_glx[] = {
    {    1,   39,    9 }, /* GLX_AMD_gpu_association */
    {    3,   48,    1 }, /* GLX_ARB_create_context */
    {    9,   49,    1 }, /* GLX_ARB_get_proc_address */
    {   21,   50,    5 }, /* GLX_EXT_import_context */
    {   25,   55,    1 }, /* GLX_EXT_swap_control */
    {   27,   56,    2 }, /* GLX_EXT_texture_from_pixmap */
    {   31,   58,    1 }, /* GLX_MESA_agp_offset */
    {   32,   59,    1 }, /* GLX_MESA_copy_sub_buffer */
    {   33,   60,    1 }, /* GLX_MESA_pixmap_colormap */
    {   34,   61,    4 }, /* GLX_MESA_query_renderer */
    {   35,   65,    1 }, /* GLX_MESA_release_buffers */
    {   36,   66,    1 }, /* GLX_MESA_set_3dfx_mode */
    {   37,   67,    2 }, /* GLX_MESA_swap_control */
    {   38,   69,    2 }, /* GLX_NV_copy_buffer */
    {   39,   71,    1 }, /* GLX_NV_copy_image */
    {   40,   72,    1 }, /* GLX_NV_delay_before_swap */
    {   44,   73,    2 }, /* GLX_NV_present_video */
    {   46,   75,    6 }, /* GLX_NV_swap_group */
    {   47,   81,    5 }, /* GLX_NV_video_capture */
    {   48,   86,    6 }, /* GLX_NV_video_out */
    {   50,   92,    5 }, /* GLX_OML_sync_control */
    {   61,   97,    1 }, /* GLX_SGI_cushion */
    {   62,   98,    2 }, /* GLX_SGI_make_current_read */
    {   63,  100,    1 }, /* GLX_SGI_swap_control */
    {   64,  101,    2 }, /* GLX_SGI_video_sync */
    {   54,  103,    6 }, /* GLX_SGIX_fbconfig */
    {   55,  109,    8 }, /* GLX_SGIX_hyperpipe */
    {   56,  117,    5 }, /* GLX_SGIX_pbuffer */
    {   57,  122,    2 }, /* GLX_SGIX_swap_barrier */
    {   58,  124,    1 }, /* GLX_SGIX_swap_group */
    {   59,  125,    5 }, /* GLX_SGIX_video_resize */
    {   65,  130,    1 }, /* GLX_SUN_get_transparent_index */
};

/* GLX: glXQueryExtensionsString(display, screen) — space-separated. */
static int gloam_glx_get_extensions_glx(GloamGLXContext *context, Display *display, int screen,
                                                              uint64_t **out_exts,
                                                              uint32_t *out_num_exts) {
    const char *ext_str, *cur, *next;
    uint64_t *exts = NULL;
    uint32_t num_exts = 0, j;
    if (!context->QueryExtensionsString) return 0;
    ext_str = (const char *)context->QueryExtensionsString(display, screen);
    if (!ext_str) return 0;
    for (j = 0; j < 2; ++j) {
        num_exts = 0;
        cur  = ext_str;
        next = cur + strcspn(cur, " ");
        while (1) {
            size_t len;
            cur += strspn(cur, " ");
            if (!cur[0]) break;
            len = (size_t)(next - cur);
            if (exts) exts[num_exts] = gloam_hash_string(cur, len);
            ++num_exts;
            cur  = next + strspn(next, " ");
            next = cur  + strcspn(cur,  " ");
        }
        if (!exts) {
            exts = (uint64_t *)calloc(num_exts, sizeof(uint64_t));
            if (!exts) return 0;
        }
    }
    gloam_sort_hashes(exts, num_exts);
    *out_exts     = exts;
    *out_num_exts = num_exts;
    return 1;
}

/* Search pre-baked kExtHashes_GLX against the sorted driver hash list and set
 * extArray flags for every matching extension. */
static int gloam_glx_find_extensions_glx(GloamGLXContext *context, Display *display, int screen) {
    uint64_t *exts = NULL;
    uint32_t  num_exts = 0, i;

    if (!gloam_glx_get_extensions_glx(context, display, screen, &exts, &num_exts))
        return 0;

    for (i = 0; i < GLOAM_ARRAYSIZE(kExtIdx_glx); ++i) {
        const uint16_t extIdx = kExtIdx_glx[i];
        context->extArray[extIdx] = gloam_hash_search(exts, num_exts, kExtHashes_GLX[extIdx]);
    }

    free(exts);
    return 1;
}

/* Query the GLX version via glXQueryVersion and set featArray entries for GLX.
 * Also returns the packed version (major << 8 | minor) for loader use. */
static int gloam_glx_find_core_glx(GloamGLXContext *context, Display **display, int *screen) {
    int major = 0, minor = 0;
    unsigned short version_value;
    if(*display == NULL) {
        *display = XOpenDisplay(0);
        if (*display == NULL) {
            return 0;
        }
        *screen = XScreenNumberOfScreen(XDefaultScreenOfDisplay(*display));
    }
    context->QueryVersion(*display, &major, &minor);
    version_value = (major << 8U) | minor;
    context->VERSION_1_0 = version_value >= 0x0100;
    context->VERSION_1_1 = version_value >= 0x0101;
    context->VERSION_1_2 = version_value >= 0x0102;
    context->VERSION_1_3 = version_value >= 0x0103;
    context->VERSION_1_4 = version_value >= 0x0104;
    return version_value;
}
int gloamLoadGLXContext(GloamGLXContext *context, Display *display, int screen, GloamLoadFunc getProcAddr) {
    int version;
    uint32_t i;
    memset(context, 0, sizeof(*context));

    context->QueryVersion = (PFNGLXQUERYVERSIONPROC)getProcAddr("glXQueryVersion");

    version = gloam_glx_find_core_glx(context, &display, &screen);
    if (!version) return 0;

    /* Load all PFNs upfront. */
    for (i = 0; i < GLOAM_ARRAYSIZE(kFnNames_GLX); ++i)
        context->pfnArray[i] = (void *)getProcAddr(kFnNames_GLX[i]);

    /* Mark features based on PFN availability. */
    for (i = 0; i < GLOAM_ARRAYSIZE(kFeatPfnRanges_GLX); ++i) {
        const GloamPfnRange_t *r = &kFeatPfnRanges_GLX[i];
        uint16_t j; int ok = 1;
        for (j = r->start; j < (uint16_t)(r->start + r->count); ++j)
            ok &= (context->pfnArray[j] != NULL);
        if (ok) context->featArray[r->extension] = 1;
    }

    if (!gloam_glx_find_extensions_glx(context, display, screen)) return 0;

    for (i = 0; i < GLOAM_ARRAYSIZE(kExtPfnRanges_glx); ++i) {
        const GloamPfnRange_t *r = &kExtPfnRanges_glx[i];
        if (context->extArray[r->extension])
            gloam_load_pfn_range_glx(context, getProcAddr, r->start, r->count);
    }

    return 1;
}

int gloamLoadGLX(Display *display, int screen, GloamLoadFunc getProcAddr) {
    return gloamLoadGLXContext(&gloam_glx_context, display, screen, getProcAddr);
}

/* ==========================================================================
   Built-in loader (--loader)
   ========================================================================== */
#ifndef GLOAM_LOADER_LIBRARY_C_
#define GLOAM_LOADER_LIBRARY_C_

#if defined(_WIN32) || defined(__CYGWIN__)

static void *gloam_dlopen(const char *name) {
    return (void *)LoadLibraryA(name);
}
static void gloam_dlclose(void *handle) {
    FreeLibrary((HMODULE)handle);
}
static void *gloam_dlsym(void *handle, const char *name) {
    return (void *)GetProcAddress((HMODULE)handle, name);
}

#else /* POSIX */

static void *gloam_dlopen(const char *name) {
    return dlopen(name, RTLD_LAZY | RTLD_LOCAL);
}
static void gloam_dlclose(void *handle) {
    dlclose(handle);
}
static void *gloam_dlsym(void *handle, const char *name) {
    return dlsym(handle, name);
}

#endif /* _WIN32 */

/* Try each name in turn; return the first handle that opens successfully. */
static void *gloam_open_library(const char * const *names, int count) {
    int i;
    for (i = 0; i < count; ++i) {
        void *h = gloam_dlopen(names[i]);
        if (h) return h;
    }
    return NULL;
}

#endif /* GLOAM_LOADER_LIBRARY_C_ */

/* ---- GLX built-in loader ------------------------------------------------ */

static const char * const gloam_glx_lib_names[] = {
#if defined(__CYGWIN__)
    "libGL-1.so",
#endif
    "libGL.so.1", "libGL.so",
};

/* glXGetProcAddressARB returns __GLXextFuncPtr = void(*)(void); store with the
   correct function-pointer type so the call goes through the right ABI. */
struct gloam_glx_load_userptr {
    void *handle;
    GloamAPIProc (*get_proc_address)(const char *);
};
static struct gloam_glx_load_userptr gloam_glx_load_state;

static GloamAPIProc gloam_glx_get_proc(const char *name) {
    struct gloam_glx_load_userptr *u = &gloam_glx_load_state;
    GloamAPIProc result = NULL;
    if (u->get_proc_address) result = u->get_proc_address(name);
    if (!result)              result = (GloamAPIProc)gloam_dlsym(u->handle, name);
    return result;
}

int gloamLoaderLoadGLXContext(GloamGLXContext *context, Display *display, int screen) {
    int did_open = 0, version;
    if (!context->gloam_loader_handle) {
        context->gloam_loader_handle = gloam_open_library(
            gloam_glx_lib_names, GLOAM_ARRAYSIZE(gloam_glx_lib_names));
        did_open = 1;
    }
    if (!context->gloam_loader_handle) return 0;

    gloam_glx_load_state.handle = context->gloam_loader_handle;
    gloam_glx_load_state.get_proc_address =
        (GloamAPIProc (*)(const char *))
            gloam_dlsym(context->gloam_loader_handle, "glXGetProcAddressARB");
    if (!gloam_glx_load_state.get_proc_address) {
        if (did_open) { gloam_dlclose(context->gloam_loader_handle); context->gloam_loader_handle = NULL; }
        return 0;
    }

    version = gloamLoadGLXContext(context, display, screen, gloam_glx_get_proc);
    gloam_glx_load_state.handle = NULL;
    if (!version && did_open) { gloam_dlclose(context->gloam_loader_handle); context->gloam_loader_handle = NULL; }
    return version;
}

int gloamLoaderLoadGLX(Display *display, int screen) {
    return gloamLoaderLoadGLXContext(&gloam_glx_context, display, screen);
}

void gloamLoaderUnloadGLXContext(GloamGLXContext *context) {
    if (context->gloam_loader_handle) {
        gloam_dlclose(context->gloam_loader_handle);
        context->gloam_loader_handle = NULL;
    }
    gloamLoaderResetGLXContext(context);
}

void gloamLoaderUnloadGLX(void) {
    gloamLoaderUnloadGLXContext(&gloam_glx_context);
}

void gloamLoaderResetGLXContext(GloamGLXContext *context) {
    memset(context, 0, sizeof(*context));
}

void gloamLoaderResetGLX(void) {
    gloamLoaderResetGLXContext(&gloam_glx_context);
}
#endif /* __linux */
