/*
 * Generated by gloam 0.2.3+ad22900. DO NOT EDIT.
 *
 *   gloam --extensions=all,-GL_EXT_direct_state_access,-GL_EXT_separate_shader_objects,-GL_EXT_vertex_shader,-GL_SUNX_constant_data,-GL_SUN_convolution_border_modes,-GL_SUN_global_alpha,-GL_SUN_mesh_array,-GL_SUN_slice_accum,-GL_SUN_triangle_list,-GL_SUN_vertex,-GL_SGIX_async,-GL_SGIX_async_histogram,-GL_SGIX_async_pixel,-GL_SGIX_blend_alpha_minmax,-GL_SGIX_calligraphic_fragment,-GL_SGIX_clipmap,-GL_SGIX_convolution_accuracy,-GL_SGIX_depth_pass_instrument,-GL_SGIX_depth_texture,-GL_SGIX_flush_raster,-GL_SGIX_fog_offset,-GL_SGIX_fragment_lighting,-GL_SGIX_framezoom,-GL_SGIX_igloo_interface,-GL_SGIX_instruments,-GL_SGIX_interlace,-GL_SGIX_ir_instrument1,-GL_SGIX_list_priority,-GL_SGIX_pixel_texture,-GL_SGIX_pixel_tiles,-GL_SGIX_polynomial_ffd,-GL_SGIX_reference_plane,-GL_SGIX_resample,-GL_SGIX_scalebias_hint,-GL_SGIX_shadow,-GL_SGIX_shadow_ambient,-GL_SGIX_sprite,-GL_SGIX_subsample,-GL_SGIX_tag_sample_buffer,-GL_SGIX_texture_add_env,-GL_SGIX_texture_coordinate_clamp,-GL_SGIX_texture_lod_bias,-GL_SGIX_texture_multi_buffer,-GL_SGIX_texture_scale_bias,-GL_SGIX_vertex_preclip,-GL_SGIX_ycrcb,-GL_SGIX_ycrcb_subsample,-GL_SGIX_ycrcba,-GL_NV_half_float,-GL_OES_byte_coordinates,-GL_ANGLE_robust_client_memory,-GL_ANGLE_shader_pixel_local_storage, --predecessors --promoted --api=gl:core,gles2,vulkan,egl,glx,wgl --baseline=gl:core=3.3,gles2=3.0 --out-path /Users/steven/Development/darwinia/contrib/gloam --merge c --alias --loader
 *
 * Extensions: all, 52 excluded explicitly (57 included)
 *   excluded explicitly: GL_ANGLE_robust_client_memory, GL_ANGLE_shader_pixel_local_storage, GL_EXT_direct_state_access, GL_EXT_separate_shader_objects, GL_EXT_vertex_shader, GL_NV_half_float, GL_OES_byte_coordinates, GL_SGIX_async, GL_SGIX_async_histogram, GL_SGIX_async_pixel, GL_SGIX_blend_alpha_minmax, GL_SGIX_calligraphic_fragment, GL_SGIX_clipmap, GL_SGIX_convolution_accuracy, GL_SGIX_depth_pass_instrument, GL_SGIX_depth_texture, GL_SGIX_flush_raster, GL_SGIX_fog_offset, GL_SGIX_fragment_lighting, GL_SGIX_framezoom, GL_SGIX_igloo_interface, GL_SGIX_instruments, GL_SGIX_interlace, GL_SGIX_ir_instrument1, GL_SGIX_list_priority, GL_SGIX_pixel_texture, GL_SGIX_pixel_tiles, GL_SGIX_polynomial_ffd, GL_SGIX_reference_plane, GL_SGIX_resample, GL_SGIX_scalebias_hint, GL_SGIX_shadow, GL_SGIX_shadow_ambient, GL_SGIX_sprite, GL_SGIX_subsample, GL_SGIX_tag_sample_buffer, GL_SGIX_texture_add_env, GL_SGIX_texture_coordinate_clamp, GL_SGIX_texture_lod_bias, GL_SGIX_texture_multi_buffer, GL_SGIX_texture_scale_bias, GL_SGIX_vertex_preclip, GL_SGIX_ycrcb, GL_SGIX_ycrcb_subsample, GL_SGIX_ycrcba, GL_SUNX_constant_data, GL_SUN_convolution_border_modes, GL_SUN_global_alpha, GL_SUN_mesh_array, GL_SUN_slice_accum, GL_SUN_triangle_list, GL_SUN_vertex
 *
 * Copyright (c) 2026 Steven Noonan
 * SPDX-License-Identifier: MIT
 *
 * Portions derived from Khronos Group XML API Registry specifications.
 * Copyright (c) 2013-2026 The Khronos Group Inc.
 * SPDX-License-Identifier: Apache-2.0
 */

#ifdef _WIN32
#include <gloam/gl.h>

#include <gloam/wgl.h>

#include <stdlib.h>  /* calloc, free    */
#include <stddef.h>
#include <stdio.h>   /* sscanf          */
#include <string.h>  /* strlen, strncmp */
#ifdef _WIN32
#  ifndef WIN32_LEAN_AND_MEAN
#    define WIN32_LEAN_AND_MEAN
#  endif
#  include <windows.h>  /* LoadLibrary, GetProcAddress */
#else
#  include <dlfcn.h> /* dlopen, dlsym, dlclose */
#endif

#if defined(__x86_64__) || defined(__i386__) || defined(_M_IX86) || defined(_M_X64)
#  define XXH_VECTOR XXH_SSE2
#  include <immintrin.h>
#elif defined(__aarch64__) || defined(__arm__) || defined(_M_ARM) || defined(_M_ARM64)
#  define XXH_VECTOR XXH_NEON
#  include <arm_neon.h>
#endif
#ifndef GLOAM_EXTERNAL_XXHASH
#  define XXH_INLINE_ALL
#  define XXH_NO_STREAM
#endif
#include "xxhash.h"

#ifndef GLOAM_IMPL_UTIL_C_
#define GLOAM_IMPL_UTIL_C_

/* MSVC vs GCC/Clang sscanf */
#ifdef _MSC_VER
#  define GLOAM_IMPL_UTIL_SSCANF sscanf_s
#else
#  define GLOAM_IMPL_UTIL_SSCANF sscanf
#endif

/* GLOAM_NO_INLINE — suppress inlining on functions that should stay out of
   the hot path (sort, hash, etc.) to avoid code bloat at call sites. */
#ifdef _MSC_VER
#  define GLOAM_NO_INLINE __declspec(noinline)
#else
#  define GLOAM_NO_INLINE __attribute__((noinline))
#endif

#define GLOAM_ARRAYSIZE(x) (sizeof(x) / sizeof((x)[0]))
#define GLOAM_UNUSED(x)    ((void)(x))

/* Contiguous run of pfnArray slots belonging to one feature or extension.
   Used by the range-based PFN loading loop. */
typedef struct {
    uint16_t extension; /* index into featArray or extArray */
    uint16_t start;     /* first pfnArray index in this run  */
    uint16_t count;     /* number of consecutive slots       */
} GloamPfnRange_t;

/* Bijective alias pair: if canonical slot is null but secondary is loaded
   (or vice versa), the loaded pointer is propagated to both slots. */
typedef struct {
    uint16_t first;  /* canonical (shortest name) pfnArray index */
    uint16_t second; /* alias pfnArray index                     */
} GloamAliasPair_t;

#endif /* GLOAM_IMPL_UTIL_C_ */

#ifndef GLOAM_IMPL_HASHSEARCH_C_
#define GLOAM_IMPL_HASHSEARCH_C_

/* gloam_sort_hashes — in-place Shellsort on a uint64_t array.
 *
 * Ciura (2001) gap sequence.  Gaps larger than n are skipped at runtime so
 * small arrays (< 10 extensions) take only a couple of passes.  No heap
 * allocation; code size is ~80 bytes on x86-64.
 */
GLOAM_NO_INLINE static void gloam_sort_hashes(uint64_t *a, size_t n) {
    static const size_t kGaps[] = { 701, 301, 132, 57, 23, 10, 4, 1 };
    size_t gi = 0;
    if (!a || n < 2) return;
    /* Skip gaps that are larger than the array. */
    while (gi < GLOAM_ARRAYSIZE(kGaps) && kGaps[gi] >= n) ++gi;
    for (; gi < GLOAM_ARRAYSIZE(kGaps); ++gi) {
        size_t gap = kGaps[gi], i;
        for (i = gap; i < n; ++i) {
            uint64_t v = a[i];
            size_t j = i;
            while (j >= gap && a[j - gap] > v) {
                a[j] = a[j - gap];
                j -= gap;
            }
            a[j] = v;
        }
    }
}

/* gloam_hash_search — binary search for `target` in a sorted uint64_t array.
 * Returns 1 if found, 0 otherwise.
 */
GLOAM_NO_INLINE static int gloam_hash_search(const uint64_t *arr, uint32_t size, uint64_t target) {
    int32_t lo = 0, hi = (int32_t)size - 1;
    while (lo <= hi) {
        int32_t mid = lo + (hi - lo) / 2;
        if (arr[mid] == target) return 1;
        if (arr[mid] < target)  lo = mid + 1;
        else                    hi = mid - 1;
    }
    return 0;
}

/* gloam_hash_string — hash a NUL-terminated string with XXH3-64.
 * The same algorithm is used at generator time to pre-bake kExtHashes[],
 * guaranteeing that driver-reported names and the embedded table match.
 */
GLOAM_NO_INLINE static uint64_t gloam_hash_string(const char *str, size_t length) {
    return XXH3_64bits(str, length);
}
#endif /* GLOAM_IMPL_HASHSEARCH_C_ */

/* ---- Global context (zero-initialised at program startup) ---------------- */
#ifdef __cplusplus
GloamWGLContext gloam_wgl_context = {};
#else
GloamWGLContext gloam_wgl_context = { 0 };
#endif

/* ---- Function name table -------------------------------------------------
   Command names stored as a single NUL-terminated string blob with a parallel
   offset table for O(1) indexing.  This avoids one pointer (8 bytes on 64-bit)
   plus one relocation entry (~24 bytes in PIC builds) per command compared to
   the traditional const char * const [] approach. */
static const uint32_t kFnCount_WGL = 145;

static const char kFnNameData_WGL[] =
    /*     0 */ "ChoosePixelFormat\0"
    /*    18 */ "DescribePixelFormat\0"
    /*    38 */ "GetEnhMetaFilePixelFormat\0"
    /*    64 */ "GetPixelFormat\0"
    /*    79 */ "SetPixelFormat\0"
    /*    94 */ "SwapBuffers\0"
    /*   106 */ "wglCopyContext\0"
    /*   121 */ "wglCreateContext\0"
    /*   138 */ "wglCreateLayerContext\0"
    /*   160 */ "wglDeleteContext\0"
    /*   177 */ "wglDescribeLayerPlane\0"
    /*   199 */ "wglGetCurrentContext\0"
    /*   220 */ "wglGetCurrentDC\0"
    /*   236 */ "wglGetLayerPaletteEntries\0"
    /*   262 */ "wglGetProcAddress\0"
    /*   280 */ "wglMakeCurrent\0"
    /*   295 */ "wglRealizeLayerPalette\0"
    /*   318 */ "wglSetLayerPaletteEntries\0"
    /*   344 */ "wglShareLists\0"
    /*   358 */ "wglSwapLayerBuffers\0"
    /*   378 */ "wglUseFontBitmaps\0"
    /*   396 */ "wglUseFontBitmapsA\0"
    /*   415 */ "wglUseFontBitmapsW\0"
    /*   434 */ "wglUseFontOutlines\0"
    /*   453 */ "wglUseFontOutlinesA\0"
    /*   473 */ "wglUseFontOutlinesW\0"
    /*   493 */ "wglSetStereoEmitterState3DL\0"
    /*   521 */ "wglBlitContextFramebufferAMD\0"
    /*   550 */ "wglCreateAssociatedContextAMD\0"
    /*   580 */ "wglCreateAssociatedContextAttribsAMD\0"
    /*   617 */ "wglDeleteAssociatedContextAMD\0"
    /*   647 */ "wglGetContextGPUIDAMD\0"
    /*   669 */ "wglGetCurrentAssociatedContextAMD\0"
    /*   703 */ "wglGetGPUIDsAMD\0"
    /*   719 */ "wglGetGPUInfoAMD\0"
    /*   736 */ "wglMakeAssociatedContextCurrentAMD\0"
    /*   771 */ "wglCreateBufferRegionARB\0"
    /*   796 */ "wglDeleteBufferRegionARB\0"
    /*   821 */ "wglRestoreBufferRegionARB\0"
    /*   847 */ "wglSaveBufferRegionARB\0"
    /*   870 */ "wglCreateContextAttribsARB\0"
    /*   897 */ "wglGetExtensionsStringARB\0"
    /*   923 */ "wglGetCurrentReadDCARB\0"
    /*   946 */ "wglMakeContextCurrentARB\0"
    /*   971 */ "wglCreatePbufferARB\0"
    /*   991 */ "wglDestroyPbufferARB\0"
    /*  1012 */ "wglGetPbufferDCARB\0"
    /*  1031 */ "wglQueryPbufferARB\0"
    /*  1050 */ "wglReleasePbufferDCARB\0"
    /*  1073 */ "wglChoosePixelFormatARB\0"
    /*  1097 */ "wglGetPixelFormatAttribfvARB\0"
    /*  1126 */ "wglGetPixelFormatAttribivARB\0"
    /*  1155 */ "wglBindTexImageARB\0"
    /*  1174 */ "wglReleaseTexImageARB\0"
    /*  1196 */ "wglSetPbufferAttribARB\0"
    /*  1219 */ "wglBindDisplayColorTableEXT\0"
    /*  1247 */ "wglCreateDisplayColorTableEXT\0"
    /*  1277 */ "wglDestroyDisplayColorTableEXT\0"
    /*  1308 */ "wglLoadDisplayColorTableEXT\0"
    /*  1336 */ "wglGetExtensionsStringEXT\0"
    /*  1362 */ "wglGetCurrentReadDCEXT\0"
    /*  1385 */ "wglMakeContextCurrentEXT\0"
    /*  1410 */ "wglCreatePbufferEXT\0"
    /*  1430 */ "wglDestroyPbufferEXT\0"
    /*  1451 */ "wglGetPbufferDCEXT\0"
    /*  1470 */ "wglQueryPbufferEXT\0"
    /*  1489 */ "wglReleasePbufferDCEXT\0"
    /*  1512 */ "wglChoosePixelFormatEXT\0"
    /*  1536 */ "wglGetPixelFormatAttribfvEXT\0"
    /*  1565 */ "wglGetPixelFormatAttribivEXT\0"
    /*  1594 */ "wglGetSwapIntervalEXT\0"
    /*  1616 */ "wglSwapIntervalEXT\0"
    /*  1635 */ "wglGetDigitalVideoParametersI3D\0"
    /*  1667 */ "wglSetDigitalVideoParametersI3D\0"
    /*  1699 */ "wglGetGammaTableI3D\0"
    /*  1719 */ "wglGetGammaTableParametersI3D\0"
    /*  1749 */ "wglSetGammaTableI3D\0"
    /*  1769 */ "wglSetGammaTableParametersI3D\0"
    /*  1799 */ "wglDisableGenlockI3D\0"
    /*  1820 */ "wglEnableGenlockI3D\0"
    /*  1840 */ "wglGenlockSampleRateI3D\0"
    /*  1864 */ "wglGenlockSourceDelayI3D\0"
    /*  1889 */ "wglGenlockSourceEdgeI3D\0"
    /*  1913 */ "wglGenlockSourceI3D\0"
    /*  1933 */ "wglGetGenlockSampleRateI3D\0"
    /*  1960 */ "wglGetGenlockSourceDelayI3D\0"
    /*  1988 */ "wglGetGenlockSourceEdgeI3D\0"
    /*  2015 */ "wglGetGenlockSourceI3D\0"
    /*  2038 */ "wglIsEnabledGenlockI3D\0"
    /*  2061 */ "wglQueryGenlockMaxSourceDelayI3D\0"
    /*  2094 */ "wglAssociateImageBufferEventsI3D\0"
    /*  2127 */ "wglCreateImageBufferI3D\0"
    /*  2151 */ "wglDestroyImageBufferI3D\0"
    /*  2176 */ "wglReleaseImageBufferEventsI3D\0"
    /*  2207 */ "wglDisableFrameLockI3D\0"
    /*  2230 */ "wglEnableFrameLockI3D\0"
    /*  2252 */ "wglIsEnabledFrameLockI3D\0"
    /*  2277 */ "wglQueryFrameLockMasterI3D\0"
    /*  2304 */ "wglBeginFrameTrackingI3D\0"
    /*  2329 */ "wglEndFrameTrackingI3D\0"
    /*  2352 */ "wglGetFrameUsageI3D\0"
    /*  2372 */ "wglQueryFrameTrackingI3D\0"
    /*  2397 */ "wglCopyImageSubDataNV\0"
    /*  2419 */ "wglDelayBeforeSwapNV\0"
    /*  2440 */ "wglDXCloseDeviceNV\0"
    /*  2459 */ "wglDXLockObjectsNV\0"
    /*  2478 */ "wglDXObjectAccessNV\0"
    /*  2498 */ "wglDXOpenDeviceNV\0"
    /*  2516 */ "wglDXRegisterObjectNV\0"
    /*  2538 */ "wglDXSetResourceShareHandleNV\0"
    /*  2568 */ "wglDXUnlockObjectsNV\0"
    /*  2589 */ "wglDXUnregisterObjectNV\0"
    /*  2613 */ "wglCreateAffinityDCNV\0"
    /*  2635 */ "wglDeleteDCNV\0"
    /*  2649 */ "wglEnumGpuDevicesNV\0"
    /*  2669 */ "wglEnumGpusFromAffinityDCNV\0"
    /*  2697 */ "wglEnumGpusNV\0"
    /*  2711 */ "wglBindVideoDeviceNV\0"
    /*  2732 */ "wglEnumerateVideoDevicesNV\0"
    /*  2759 */ "wglQueryCurrentContextNV\0"
    /*  2784 */ "wglBindSwapBarrierNV\0"
    /*  2805 */ "wglJoinSwapGroupNV\0"
    /*  2824 */ "wglQueryFrameCountNV\0"
    /*  2845 */ "wglQueryMaxSwapGroupsNV\0"
    /*  2869 */ "wglQuerySwapGroupNV\0"
    /*  2889 */ "wglResetFrameCountNV\0"
    /*  2910 */ "wglBindVideoCaptureDeviceNV\0"
    /*  2938 */ "wglEnumerateVideoCaptureDevicesNV\0"
    /*  2972 */ "wglLockVideoCaptureDeviceNV\0"
    /*  3000 */ "wglQueryVideoCaptureDeviceNV\0"
    /*  3029 */ "wglReleaseVideoCaptureDeviceNV\0"
    /*  3060 */ "wglBindVideoImageNV\0"
    /*  3080 */ "wglGetVideoDeviceNV\0"
    /*  3100 */ "wglGetVideoInfoNV\0"
    /*  3118 */ "wglReleaseVideoDeviceNV\0"
    /*  3142 */ "wglReleaseVideoImageNV\0"
    /*  3165 */ "wglSendPbufferToVideoNV\0"
    /*  3189 */ "wglAllocateMemoryNV\0"
    /*  3209 */ "wglFreeMemoryNV\0"
    /*  3225 */ "wglGetMscRateOML\0"
    /*  3242 */ "wglGetSyncValuesOML\0"
    /*  3262 */ "wglSwapBuffersMscOML\0"
    /*  3283 */ "wglSwapLayerBuffersMscOML\0"
    /*  3309 */ "wglWaitForMscOML\0"
    /*  3326 */ "wglWaitForSbcOML\0"
;

static const uint16_t kFnNameOffsets_WGL[] = {
    /*    0 */     0, /* ChoosePixelFormat */
    /*    1 */    18, /* DescribePixelFormat */
    /*    2 */    38, /* GetEnhMetaFilePixelFormat */
    /*    3 */    64, /* GetPixelFormat */
    /*    4 */    79, /* SetPixelFormat */
    /*    5 */    94, /* SwapBuffers */
    /*    6 */   106, /* wglCopyContext */
    /*    7 */   121, /* wglCreateContext */
    /*    8 */   138, /* wglCreateLayerContext */
    /*    9 */   160, /* wglDeleteContext */
    /*   10 */   177, /* wglDescribeLayerPlane */
    /*   11 */   199, /* wglGetCurrentContext */
    /*   12 */   220, /* wglGetCurrentDC */
    /*   13 */   236, /* wglGetLayerPaletteEntries */
    /*   14 */   262, /* wglGetProcAddress */
    /*   15 */   280, /* wglMakeCurrent */
    /*   16 */   295, /* wglRealizeLayerPalette */
    /*   17 */   318, /* wglSetLayerPaletteEntries */
    /*   18 */   344, /* wglShareLists */
    /*   19 */   358, /* wglSwapLayerBuffers */
    /*   20 */   378, /* wglUseFontBitmaps */
    /*   21 */   396, /* wglUseFontBitmapsA */
    /*   22 */   415, /* wglUseFontBitmapsW */
    /*   23 */   434, /* wglUseFontOutlines */
    /*   24 */   453, /* wglUseFontOutlinesA */
    /*   25 */   473, /* wglUseFontOutlinesW */
    /*   26 */   493, /* wglSetStereoEmitterState3DL */
    /*   27 */   521, /* wglBlitContextFramebufferAMD */
    /*   28 */   550, /* wglCreateAssociatedContextAMD */
    /*   29 */   580, /* wglCreateAssociatedContextAttribsAMD */
    /*   30 */   617, /* wglDeleteAssociatedContextAMD */
    /*   31 */   647, /* wglGetContextGPUIDAMD */
    /*   32 */   669, /* wglGetCurrentAssociatedContextAMD */
    /*   33 */   703, /* wglGetGPUIDsAMD */
    /*   34 */   719, /* wglGetGPUInfoAMD */
    /*   35 */   736, /* wglMakeAssociatedContextCurrentAMD */
    /*   36 */   771, /* wglCreateBufferRegionARB */
    /*   37 */   796, /* wglDeleteBufferRegionARB */
    /*   38 */   821, /* wglRestoreBufferRegionARB */
    /*   39 */   847, /* wglSaveBufferRegionARB */
    /*   40 */   870, /* wglCreateContextAttribsARB */
    /*   41 */   897, /* wglGetExtensionsStringARB */
    /*   42 */   923, /* wglGetCurrentReadDCARB */
    /*   43 */   946, /* wglMakeContextCurrentARB */
    /*   44 */   971, /* wglCreatePbufferARB */
    /*   45 */   991, /* wglDestroyPbufferARB */
    /*   46 */  1012, /* wglGetPbufferDCARB */
    /*   47 */  1031, /* wglQueryPbufferARB */
    /*   48 */  1050, /* wglReleasePbufferDCARB */
    /*   49 */  1073, /* wglChoosePixelFormatARB */
    /*   50 */  1097, /* wglGetPixelFormatAttribfvARB */
    /*   51 */  1126, /* wglGetPixelFormatAttribivARB */
    /*   52 */  1155, /* wglBindTexImageARB */
    /*   53 */  1174, /* wglReleaseTexImageARB */
    /*   54 */  1196, /* wglSetPbufferAttribARB */
    /*   55 */  1219, /* wglBindDisplayColorTableEXT */
    /*   56 */  1247, /* wglCreateDisplayColorTableEXT */
    /*   57 */  1277, /* wglDestroyDisplayColorTableEXT */
    /*   58 */  1308, /* wglLoadDisplayColorTableEXT */
    /*   59 */  1336, /* wglGetExtensionsStringEXT */
    /*   60 */  1362, /* wglGetCurrentReadDCEXT */
    /*   61 */  1385, /* wglMakeContextCurrentEXT */
    /*   62 */  1410, /* wglCreatePbufferEXT */
    /*   63 */  1430, /* wglDestroyPbufferEXT */
    /*   64 */  1451, /* wglGetPbufferDCEXT */
    /*   65 */  1470, /* wglQueryPbufferEXT */
    /*   66 */  1489, /* wglReleasePbufferDCEXT */
    /*   67 */  1512, /* wglChoosePixelFormatEXT */
    /*   68 */  1536, /* wglGetPixelFormatAttribfvEXT */
    /*   69 */  1565, /* wglGetPixelFormatAttribivEXT */
    /*   70 */  1594, /* wglGetSwapIntervalEXT */
    /*   71 */  1616, /* wglSwapIntervalEXT */
    /*   72 */  1635, /* wglGetDigitalVideoParametersI3D */
    /*   73 */  1667, /* wglSetDigitalVideoParametersI3D */
    /*   74 */  1699, /* wglGetGammaTableI3D */
    /*   75 */  1719, /* wglGetGammaTableParametersI3D */
    /*   76 */  1749, /* wglSetGammaTableI3D */
    /*   77 */  1769, /* wglSetGammaTableParametersI3D */
    /*   78 */  1799, /* wglDisableGenlockI3D */
    /*   79 */  1820, /* wglEnableGenlockI3D */
    /*   80 */  1840, /* wglGenlockSampleRateI3D */
    /*   81 */  1864, /* wglGenlockSourceDelayI3D */
    /*   82 */  1889, /* wglGenlockSourceEdgeI3D */
    /*   83 */  1913, /* wglGenlockSourceI3D */
    /*   84 */  1933, /* wglGetGenlockSampleRateI3D */
    /*   85 */  1960, /* wglGetGenlockSourceDelayI3D */
    /*   86 */  1988, /* wglGetGenlockSourceEdgeI3D */
    /*   87 */  2015, /* wglGetGenlockSourceI3D */
    /*   88 */  2038, /* wglIsEnabledGenlockI3D */
    /*   89 */  2061, /* wglQueryGenlockMaxSourceDelayI3D */
    /*   90 */  2094, /* wglAssociateImageBufferEventsI3D */
    /*   91 */  2127, /* wglCreateImageBufferI3D */
    /*   92 */  2151, /* wglDestroyImageBufferI3D */
    /*   93 */  2176, /* wglReleaseImageBufferEventsI3D */
    /*   94 */  2207, /* wglDisableFrameLockI3D */
    /*   95 */  2230, /* wglEnableFrameLockI3D */
    /*   96 */  2252, /* wglIsEnabledFrameLockI3D */
    /*   97 */  2277, /* wglQueryFrameLockMasterI3D */
    /*   98 */  2304, /* wglBeginFrameTrackingI3D */
    /*   99 */  2329, /* wglEndFrameTrackingI3D */
    /*  100 */  2352, /* wglGetFrameUsageI3D */
    /*  101 */  2372, /* wglQueryFrameTrackingI3D */
    /*  102 */  2397, /* wglCopyImageSubDataNV */
    /*  103 */  2419, /* wglDelayBeforeSwapNV */
    /*  104 */  2440, /* wglDXCloseDeviceNV */
    /*  105 */  2459, /* wglDXLockObjectsNV */
    /*  106 */  2478, /* wglDXObjectAccessNV */
    /*  107 */  2498, /* wglDXOpenDeviceNV */
    /*  108 */  2516, /* wglDXRegisterObjectNV */
    /*  109 */  2538, /* wglDXSetResourceShareHandleNV */
    /*  110 */  2568, /* wglDXUnlockObjectsNV */
    /*  111 */  2589, /* wglDXUnregisterObjectNV */
    /*  112 */  2613, /* wglCreateAffinityDCNV */
    /*  113 */  2635, /* wglDeleteDCNV */
    /*  114 */  2649, /* wglEnumGpuDevicesNV */
    /*  115 */  2669, /* wglEnumGpusFromAffinityDCNV */
    /*  116 */  2697, /* wglEnumGpusNV */
    /*  117 */  2711, /* wglBindVideoDeviceNV */
    /*  118 */  2732, /* wglEnumerateVideoDevicesNV */
    /*  119 */  2759, /* wglQueryCurrentContextNV */
    /*  120 */  2784, /* wglBindSwapBarrierNV */
    /*  121 */  2805, /* wglJoinSwapGroupNV */
    /*  122 */  2824, /* wglQueryFrameCountNV */
    /*  123 */  2845, /* wglQueryMaxSwapGroupsNV */
    /*  124 */  2869, /* wglQuerySwapGroupNV */
    /*  125 */  2889, /* wglResetFrameCountNV */
    /*  126 */  2910, /* wglBindVideoCaptureDeviceNV */
    /*  127 */  2938, /* wglEnumerateVideoCaptureDevicesNV */
    /*  128 */  2972, /* wglLockVideoCaptureDeviceNV */
    /*  129 */  3000, /* wglQueryVideoCaptureDeviceNV */
    /*  130 */  3029, /* wglReleaseVideoCaptureDeviceNV */
    /*  131 */  3060, /* wglBindVideoImageNV */
    /*  132 */  3080, /* wglGetVideoDeviceNV */
    /*  133 */  3100, /* wglGetVideoInfoNV */
    /*  134 */  3118, /* wglReleaseVideoDeviceNV */
    /*  135 */  3142, /* wglReleaseVideoImageNV */
    /*  136 */  3165, /* wglSendPbufferToVideoNV */
    /*  137 */  3189, /* wglAllocateMemoryNV */
    /*  138 */  3209, /* wglFreeMemoryNV */
    /*  139 */  3225, /* wglGetMscRateOML */
    /*  140 */  3242, /* wglGetSyncValuesOML */
    /*  141 */  3262, /* wglSwapBuffersMscOML */
    /*  142 */  3283, /* wglSwapLayerBuffersMscOML */
    /*  143 */  3309, /* wglWaitForMscOML */
    /*  144 */  3326 /* wglWaitForSbcOML */
};


/* ---- Extension hash table ------------------------------------------------
   One XXH3-64 hash per extension, in extArray index order.
   Pre-baked at generator time with the same algorithm used at load time. */
static const uint64_t kExtHashes_WGL[] = {
    /*    0 */ 0x0bec45d23000040cULL, /* WGL_3DFX_multisample */
    /*    1 */ 0xa544e2233909cd6cULL, /* WGL_3DL_stereo_control */
    /*    2 */ 0x3444be63e457de0aULL, /* WGL_AMD_gpu_association */
    /*    3 */ 0x23735e3ef94191dfULL, /* WGL_ARB_buffer_region */
    /*    4 */ 0xcba9d91bf8152127ULL, /* WGL_ARB_context_flush_control */
    /*    5 */ 0x93b339a9e2cbe314ULL, /* WGL_ARB_create_context */
    /*    6 */ 0x4d3ff082cec434daULL, /* WGL_ARB_create_context_no_error */
    /*    7 */ 0x6879670f69d523e8ULL, /* WGL_ARB_create_context_profile */
    /*    8 */ 0x24a0369001a0d30dULL, /* WGL_ARB_create_context_robustness */
    /*    9 */ 0xd6afdfe5c6fa3614ULL, /* WGL_ARB_extensions_string */
    /*   10 */ 0x2b2322e59fb5083bULL, /* WGL_ARB_framebuffer_sRGB */
    /*   11 */ 0xffb3e932bb0ccdd5ULL, /* WGL_ARB_make_current_read */
    /*   12 */ 0xad82eec327c2f1d8ULL, /* WGL_ARB_multisample */
    /*   13 */ 0xf6b9458b542c30dcULL, /* WGL_ARB_pbuffer */
    /*   14 */ 0xe73be941e5f7916bULL, /* WGL_ARB_pixel_format */
    /*   15 */ 0x0bed92c76c78efffULL, /* WGL_ARB_pixel_format_float */
    /*   16 */ 0xf0753dc5c832f146ULL, /* WGL_ARB_render_texture */
    /*   17 */ 0x6c50f503bc89115eULL, /* WGL_ARB_robustness_application_isolation */
    /*   18 */ 0x944ee36787077ccfULL, /* WGL_ARB_robustness_share_group_isolation */
    /*   19 */ 0x40521e21b96727d5ULL, /* WGL_ATI_pixel_format_float */
    /*   20 */ 0x6a042befb2e60d17ULL, /* WGL_ATI_render_texture_rectangle */
    /*   21 */ 0x344eee0b6820af34ULL, /* WGL_EXT_colorspace */
    /*   22 */ 0xdea75ca5e2edbb10ULL, /* WGL_EXT_create_context_es2_profile */
    /*   23 */ 0x7e5f58022569e61eULL, /* WGL_EXT_create_context_es_profile */
    /*   24 */ 0x3404dab980e61ca2ULL, /* WGL_EXT_depth_float */
    /*   25 */ 0x2d0e6cfb46a0106fULL, /* WGL_EXT_display_color_table */
    /*   26 */ 0x675d378710334a65ULL, /* WGL_EXT_extensions_string */
    /*   27 */ 0x1f5a579fdea0f148ULL, /* WGL_EXT_framebuffer_sRGB */
    /*   28 */ 0x6d4cef39fc681fb3ULL, /* WGL_EXT_make_current_read */
    /*   29 */ 0x712af2217200a415ULL, /* WGL_EXT_multisample */
    /*   30 */ 0x51b3a5602fa896a1ULL, /* WGL_EXT_pbuffer */
    /*   31 */ 0xf09d08e1c43f564eULL, /* WGL_EXT_pixel_format */
    /*   32 */ 0x61cb3bc9968979c9ULL, /* WGL_EXT_pixel_format_packed_float */
    /*   33 */ 0x212a6bdfca219506ULL, /* WGL_EXT_swap_control */
    /*   34 */ 0x97c79eb8ab4c254aULL, /* WGL_EXT_swap_control_tear */
    /*   35 */ 0x93c433aa5564a48dULL, /* WGL_I3D_digital_video_control */
    /*   36 */ 0x50b4447ba45d250eULL, /* WGL_I3D_gamma */
    /*   37 */ 0x13f677cdbcea2701ULL, /* WGL_I3D_genlock */
    /*   38 */ 0x7030d8df95640f74ULL, /* WGL_I3D_image_buffer */
    /*   39 */ 0xf89e0e880fa2991dULL, /* WGL_I3D_swap_frame_lock */
    /*   40 */ 0xe483d21a182c9656ULL, /* WGL_I3D_swap_frame_usage */
    /*   41 */ 0xa54b9b658ac06b9aULL, /* WGL_NV_DX_interop */
    /*   42 */ 0x1187bf238685f6baULL, /* WGL_NV_DX_interop2 */
    /*   43 */ 0xafab55f5e37bcb25ULL, /* WGL_NV_copy_image */
    /*   44 */ 0x3e1dd8f8bde73422ULL, /* WGL_NV_delay_before_swap */
    /*   45 */ 0xdad29f54a41cb160ULL, /* WGL_NV_float_buffer */
    /*   46 */ 0x83ba23356bc5c9c7ULL, /* WGL_NV_gpu_affinity */
    /*   47 */ 0x045e190c435b4d35ULL, /* WGL_NV_multigpu_context */
    /*   48 */ 0x7d7c383b450b63afULL, /* WGL_NV_multisample_coverage */
    /*   49 */ 0x5f2a9df50cf1003aULL, /* WGL_NV_present_video */
    /*   50 */ 0x2ac871c1f2dbac4dULL, /* WGL_NV_render_depth_texture */
    /*   51 */ 0x275c113e57078fccULL, /* WGL_NV_render_texture_rectangle */
    /*   52 */ 0xd91b7247d42d3ba5ULL, /* WGL_NV_swap_group */
    /*   53 */ 0x293670a02363360bULL, /* WGL_NV_vertex_array_range */
    /*   54 */ 0x8cf54648141ca138ULL, /* WGL_NV_video_capture */
    /*   55 */ 0xeab153b5cac91b24ULL, /* WGL_NV_video_output */
    /*   56 */ 0x3c2462ed17d12185ULL  /* WGL_OML_sync_control */
};

/* ---- Feature PFN range table ---------------------------------------------
   Each entry maps one feature (by featArray index) to a contiguous run of
   pfnArray slots.  The loader iterates this table and bulk-loads the run
   when featArray[entry.extension] is set. */
static const GloamPfnRange_t kFeatPfnRanges_WGL[] = {
    {    0,    0,   26 }, /* WGL_VERSION_1_0 */
};

/* ---- PFN range helper (GL / EGL / GLX / WGL) ----------------------------
   Walks a contiguous run of pfnArray slots and calls the plain load callback
   (name only) for each one. */
static void gloam_load_pfn_range_wgl(GloamWGLContext *context, GloamLoadFunc getProcAddr,
                                  uint16_t start, uint16_t count) {
    uint16_t i;
    for (i = start; i < (uint16_t)(start + count); ++i) {
        const char *pfnName = &kFnNameData_WGL[kFnNameOffsets_WGL[i]];
        context->pfnArray[i] = (void *)getProcAddr(pfnName);
    }
}


/* ==========================================================================
   Per-API sections
   ========================================================================== */

/* --------------------------------------------------------------------------
   API: wgl
   -------------------------------------------------------------------------- */

/* Extension index subset for wgl: extArray indices this API supports. */
static const uint16_t kExtIdx_wgl[] = {
       0, /* WGL_3DFX_multisample */
       1, /* WGL_3DL_stereo_control */
       2, /* WGL_AMD_gpu_association */
       3, /* WGL_ARB_buffer_region */
       4, /* WGL_ARB_context_flush_control */
       5, /* WGL_ARB_create_context */
       6, /* WGL_ARB_create_context_no_error */
       7, /* WGL_ARB_create_context_profile */
       8, /* WGL_ARB_create_context_robustness */
       9, /* WGL_ARB_extensions_string */
      10, /* WGL_ARB_framebuffer_sRGB */
      11, /* WGL_ARB_make_current_read */
      12, /* WGL_ARB_multisample */
      13, /* WGL_ARB_pbuffer */
      14, /* WGL_ARB_pixel_format */
      15, /* WGL_ARB_pixel_format_float */
      16, /* WGL_ARB_render_texture */
      17, /* WGL_ARB_robustness_application_isolation */
      18, /* WGL_ARB_robustness_share_group_isolation */
      19, /* WGL_ATI_pixel_format_float */
      20, /* WGL_ATI_render_texture_rectangle */
      21, /* WGL_EXT_colorspace */
      22, /* WGL_EXT_create_context_es2_profile */
      23, /* WGL_EXT_create_context_es_profile */
      24, /* WGL_EXT_depth_float */
      25, /* WGL_EXT_display_color_table */
      26, /* WGL_EXT_extensions_string */
      27, /* WGL_EXT_framebuffer_sRGB */
      28, /* WGL_EXT_make_current_read */
      29, /* WGL_EXT_multisample */
      30, /* WGL_EXT_pbuffer */
      31, /* WGL_EXT_pixel_format */
      32, /* WGL_EXT_pixel_format_packed_float */
      33, /* WGL_EXT_swap_control */
      34, /* WGL_EXT_swap_control_tear */
      35, /* WGL_I3D_digital_video_control */
      36, /* WGL_I3D_gamma */
      37, /* WGL_I3D_genlock */
      38, /* WGL_I3D_image_buffer */
      39, /* WGL_I3D_swap_frame_lock */
      40, /* WGL_I3D_swap_frame_usage */
      41, /* WGL_NV_DX_interop */
      42, /* WGL_NV_DX_interop2 */
      43, /* WGL_NV_copy_image */
      44, /* WGL_NV_delay_before_swap */
      45, /* WGL_NV_float_buffer */
      46, /* WGL_NV_gpu_affinity */
      47, /* WGL_NV_multigpu_context */
      48, /* WGL_NV_multisample_coverage */
      49, /* WGL_NV_present_video */
      50, /* WGL_NV_render_depth_texture */
      51, /* WGL_NV_render_texture_rectangle */
      52, /* WGL_NV_swap_group */
      53, /* WGL_NV_vertex_array_range */
      54, /* WGL_NV_video_capture */
      55, /* WGL_NV_video_output */
      56, /* WGL_OML_sync_control */
};

/* Extension PFN range table for wgl. */
static const GloamPfnRange_t kExtPfnRanges_wgl[] = {
    {    1,   26,    1 }, /* WGL_3DL_stereo_control */
    {    2,   27,    9 }, /* WGL_AMD_gpu_association */
    {    3,   36,    4 }, /* WGL_ARB_buffer_region */
    {    5,   40,    1 }, /* WGL_ARB_create_context */
    {    9,   41,    1 }, /* WGL_ARB_extensions_string */
    {   11,   42,    2 }, /* WGL_ARB_make_current_read */
    {   13,   44,    5 }, /* WGL_ARB_pbuffer */
    {   14,   49,    3 }, /* WGL_ARB_pixel_format */
    {   16,   52,    3 }, /* WGL_ARB_render_texture */
    {   25,   55,    4 }, /* WGL_EXT_display_color_table */
    {   26,   59,    1 }, /* WGL_EXT_extensions_string */
    {   28,   60,    2 }, /* WGL_EXT_make_current_read */
    {   30,   62,    5 }, /* WGL_EXT_pbuffer */
    {   31,   67,    3 }, /* WGL_EXT_pixel_format */
    {   33,   70,    2 }, /* WGL_EXT_swap_control */
    {   35,   72,    2 }, /* WGL_I3D_digital_video_control */
    {   36,   74,    4 }, /* WGL_I3D_gamma */
    {   37,   78,   12 }, /* WGL_I3D_genlock */
    {   38,   90,    4 }, /* WGL_I3D_image_buffer */
    {   39,   94,    4 }, /* WGL_I3D_swap_frame_lock */
    {   40,   98,    4 }, /* WGL_I3D_swap_frame_usage */
    {   43,  102,    1 }, /* WGL_NV_copy_image */
    {   44,  103,    1 }, /* WGL_NV_delay_before_swap */
    {   41,  104,    8 }, /* WGL_NV_DX_interop */
    {   46,  112,    5 }, /* WGL_NV_gpu_affinity */
    {   49,  117,    3 }, /* WGL_NV_present_video */
    {   52,  120,    6 }, /* WGL_NV_swap_group */
    {   54,  126,    5 }, /* WGL_NV_video_capture */
    {   55,  131,    6 }, /* WGL_NV_video_output */
    {   53,  137,    2 }, /* WGL_NV_vertex_array_range */
    {   56,  139,    6 }, /* WGL_OML_sync_control */
};

/* WGL: wglGetExtensionsStringARB / wglGetExtensionsStringEXT. */
static int gloam_wgl_get_extensions_wgl(GloamWGLContext *context, HDC hdc,
                                                              uint64_t **out_exts,
                                                              uint32_t *out_num_exts) {
    const char *ext_str = NULL, *cur, *next;
    uint64_t *exts = NULL;
    uint32_t num_exts = 0, j;
    if (context->GetExtensionsStringARB)
        ext_str = (const char *)context->GetExtensionsStringARB(hdc);
    if (!ext_str && context->GetExtensionsStringEXT)
        ext_str = (const char *)context->GetExtensionsStringEXT();
    if (!ext_str) return 0;
    for (j = 0; j < 2; ++j) {
        num_exts = 0;
        cur  = ext_str;
        next = cur + strcspn(cur, " ");
        while (1) {
            size_t len;
            cur += strspn(cur, " ");
            if (!cur[0]) break;
            len = (size_t)(next - cur);
            if (exts) exts[num_exts] = gloam_hash_string(cur, len);
            ++num_exts;
            cur  = next + strspn(next, " ");
            next = cur  + strcspn(cur,  " ");
        }
        if (!exts) {
            exts = (uint64_t *)calloc(num_exts, sizeof(uint64_t));
            if (!exts) return 0;
        }
    }
    gloam_sort_hashes(exts, num_exts);
    *out_exts     = exts;
    *out_num_exts = num_exts;
    return 1;
}

/* Search pre-baked kExtHashes_WGL against the sorted driver hash list and set
 * extArray flags for every matching extension. */
static int gloam_wgl_find_extensions_wgl(GloamWGLContext *context, HDC hdc) {
    uint64_t *exts = NULL;
    uint32_t  num_exts = 0, i;

    if (!gloam_wgl_get_extensions_wgl(context, hdc, &exts, &num_exts))
        return 0;

    for (i = 0; i < GLOAM_ARRAYSIZE(kExtIdx_wgl); ++i) {
        const uint16_t extIdx = kExtIdx_wgl[i];
        context->extArray[extIdx] = gloam_hash_search(exts, num_exts, kExtHashes_WGL[extIdx]);
    }

    free(exts);
    return 1;
}

/* Faux version detection on WGL */
static int gloam_wgl_find_core_wgl(GloamWGLContext *context) {
    int major = 1, minor = 0;
    unsigned short version_value;
    version_value = (unsigned short)((major << 8) | minor);

    context->VERSION_1_0 = (version_value >= 0x0100);

    return (int)version_value;
}int gloamLoadWGLContext(GloamWGLContext *context, HDC hdc, GloamLoadFunc getProcAddr) {
    int version;
    uint32_t i;
    GLOAM_UNUSED(kFnCount_WGL);

    memset(context, 0, sizeof(*context));

    /* WGL mandatory extensions must be loaded first for extension detection. */
    context->GetExtensionsStringARB = (PFNWGLGETEXTENSIONSSTRINGARBPROC)getProcAddr("wglGetExtensionsStringARB");
    context->GetExtensionsStringEXT = (PFNWGLGETEXTENSIONSSTRINGEXTPROC)getProcAddr("wglGetExtensionsStringEXT");

    version = gloam_wgl_find_core_wgl(context);
    if (!version) return 0;

    /* Load all PFNs upfront. */
    for (i = 0; i < kFnCount_WGL; ++i)
        context->pfnArray[i] = (void *)getProcAddr((kFnNameData_WGL + kFnNameOffsets_WGL[i]));

    /* Mark features based on PFN availability. */
    for (i = 0; i < GLOAM_ARRAYSIZE(kFeatPfnRanges_WGL); ++i) {
        const GloamPfnRange_t *r = &kFeatPfnRanges_WGL[i];
        uint16_t j; int ok = 1;
        for (j = r->start; j < (uint16_t)(r->start + r->count); ++j)
            ok &= (context->pfnArray[j] != NULL);
        if (ok) context->featArray[r->extension] = 1;
    }


    if (!gloam_wgl_find_extensions_wgl(context, hdc)) return 0;

    for (i = 0; i < GLOAM_ARRAYSIZE(kExtPfnRanges_wgl); ++i) {
        const GloamPfnRange_t *r = &kExtPfnRanges_wgl[i];
        if (context->extArray[r->extension])
            gloam_load_pfn_range_wgl(context, getProcAddr, r->start, r->count);
    }

    return 1;
}

int gloamLoadWGL(HDC hdc, GloamLoadFunc getProcAddr) {
    return gloamLoadWGLContext(&gloam_wgl_context, hdc, getProcAddr);
}

/* ==========================================================================
   Built-in loader (--loader)
   ========================================================================== */
#ifndef GLOAM_LOADER_LIBRARY_C_
#define GLOAM_LOADER_LIBRARY_C_

#if defined(_WIN32) || defined(__CYGWIN__)

static void *gloam_dlopen(const char *name) {
    return (void *)LoadLibraryA(name);
}
static void gloam_dlclose(void *handle) {
    FreeLibrary((HMODULE)handle);
}
static void *gloam_dlsym(void *handle, const char *name) {
    return (void *)GetProcAddress((HMODULE)handle, name);
}

#else /* POSIX */

static void *gloam_dlopen(const char *name) {
    return dlopen(name, RTLD_LAZY | RTLD_LOCAL);
}
static void gloam_dlclose(void *handle) {
    dlclose(handle);
}
static void *gloam_dlsym(void *handle, const char *name) {
    return dlsym(handle, name);
}

#endif /* _WIN32 */

/* Try each name in turn; return the first handle that opens successfully. */
static void *gloam_open_library(const char * const *names, int count) {
    int i;
    for (i = 0; i < count; ++i) {
        void *h = gloam_dlopen(names[i]);
        if (h) return h;
    }
    return NULL;
}

#endif /* GLOAM_LOADER_LIBRARY_C_ */

/* ---- WGL built-in loader ------------------------------------------------ */

static const char * const gloam_wgl_lib_names[] = { "opengl32.dll" };

/* wglGetProcAddress is WINAPI (__stdcall); must not be stored or called through
   a plain cdecl pointer.  Store with the correct type in a userptr struct. */
struct gloam_wgl_load_userptr {
    void *handle;
    GloamAPIProc (WINAPI *wgl_get_proc)(const char *);
};
static struct gloam_wgl_load_userptr gloam_wgl_load_state;

static GloamAPIProc gloam_wgl_get_proc(const char *name) {
    struct gloam_wgl_load_userptr *u = &gloam_wgl_load_state;
    GloamAPIProc result = NULL;
    if (u->wgl_get_proc) result = u->wgl_get_proc(name);
    if (!result)         result = (GloamAPIProc)gloam_dlsym(u->handle, name);
    return result;
}
int gloamLoaderLoadWGLContext(GloamWGLContext *context, HDC hdc) {
    int did_open = 0, version;
    if (!context->gloam_loader_handle) {
        context->gloam_loader_handle = gloam_open_library(
            gloam_wgl_lib_names, GLOAM_ARRAYSIZE(gloam_wgl_lib_names));
        did_open = 1;
    }
    if (!context->gloam_loader_handle) return 0;

    gloam_wgl_load_state.handle = context->gloam_loader_handle;
    gloam_wgl_load_state.wgl_get_proc =
        (GloamAPIProc (WINAPI *)(const char *))
            gloam_dlsym(context->gloam_loader_handle, "wglGetProcAddress");
    if (!gloam_wgl_load_state.wgl_get_proc) {
        if (did_open) { gloam_dlclose(context->gloam_loader_handle); context->gloam_loader_handle = NULL; }
        return 0;
    }

    version = gloamLoadWGLContext(context, hdc, gloam_wgl_get_proc);
    gloam_wgl_load_state.handle = NULL;
    if (!version && did_open) { gloam_dlclose(context->gloam_loader_handle); context->gloam_loader_handle = NULL; }
    return version;
}

int gloamLoaderLoadWGL(HDC hdc) {
    return gloamLoaderLoadWGLContext(&gloam_wgl_context, hdc);
}

void gloamLoaderUnloadWGLContext(GloamWGLContext *context) {
    if (context->gloam_loader_handle) {
        gloam_dlclose(context->gloam_loader_handle);
        context->gloam_loader_handle = NULL;
    }
    gloamLoaderResetWGLContext(context);
}

void gloamLoaderUnloadWGL(void) {
    gloamLoaderUnloadWGLContext(&gloam_wgl_context);
}

void gloamLoaderResetWGLContext(GloamWGLContext *context) {
    memset(context, 0, sizeof(*context));
}

void gloamLoaderResetWGL(void) {
    gloamLoaderResetWGLContext(&gloam_wgl_context);
}
#endif /* _WIN32 */

